install:
  - git submodule update --init --recursive
  - cinst php -y
  - set PATH=C:\tools\php;%PATH%

build_script:
  - cd gale2\build
  - CMake-VS2015-Win32.cmd
  - cmake --build "Visual Studio 14 2015"

artifacts:
  - path: gale2\bin\**\*.exe
