GALE: gale::math::Interpolator Class Reference
gale::math::Interpolator Class Reference
A collection of interpolation (and approximation) methods.
#include <interpolator.h>
Static Public Member Functions
template<class T >
static T Linear (global::DynamicArray< T > const &v, float s, bool const closed=false)
Piecewise linear interpolation of the values in v at position s.
template<class T >
static T Cosine (global::DynamicArray< T > const &v, float s, bool const closed=false)
Piecewise cosine interpolation of the values in v at position s.
template<class T >
static T Bezier (global::DynamicArray< T > const &v, global::DynamicArray< T > const &t, float s, bool const closed=false)
Piecewise cubic Bezier interpolation of the values in v and their corresponding tangents in t at position s.
template<class T >
static T BSpline (global::DynamicArray< T > const &v, float s, bool const closed=false)
Uniform cubic B-Spline approximation of the values in v ("de Boor" points) at position s.
template<class T >
static T CatmullRom (global::DynamicArray< T > const &v, float s, bool const closed=false)
Piecewise cubic Catmull-Rom interpolation of the values in v at position s.
template<class T >
static T Hermite (global::DynamicArray< T > const &v, global::DynamicArray< T > const &t, float s, bool const closed=false)
Piecewise cubic Hermite interpolation of the values in v and their corresponding tangents in t at position s.
Static Private Member Functions
static float getInterval (int const n, float const s, bool const closed, int &i0, int &i1)
Returns the indices i0 and i1 for position s into an array with maximum index n (the position in range [0,1] is mapped to the array size).
template<class T >
static T evalPolynomial (T const &v0, T const &v1, T const &v2, T const &v3, signed char const (&w)[16], float const f, float const s)
Evaluates the cubic polynomial constructed from the values v0, v1 v2, v3, the weights in w and the factor f, at position s.
Detailed Description
A collection of interpolation (and approximation) methods.
For a nice introduction, see http://altdevblogaday.org/2011/03/21/moving-beyond-the-linear-bezier/.
Member Function Documentation
Linear()
template<class T > static T gale::math::Interpolator::Linear (global::DynamicArray< T > const & v, float s, bool const closed = false) inline static
Piecewise linear interpolation of the values in v at position s.
The position in range [0,1] is mapped to the array size. If closed is true, the values are treated as being periodic, resulting in a closed curve. Also see http://local.wasp.uwa.edu.au/~pbourke/miscellaneous/interpolation/.
References getInterval(), gale::global::DynamicArray< T >::getSize(), and gale::math::lerp().
Cosine()
template<class T > static T gale::math::Interpolator::Cosine (global::DynamicArray< T > const & v, float s, bool const closed = false) inline static
Piecewise cosine interpolation of the values in v at position s.
The position in range [0,1] is mapped to the array size. If closed is true, the values are treated as being periodic, resulting in a closed curve. Also see http://local.wasp.uwa.edu.au/~pbourke/miscellaneous/interpolation/.
References getInterval(), gale::global::DynamicArray< T >::getSize(), gale::math::lerp(), and gale::math::Constants< T >::PI().
Bezier()
template<class T > static T gale::math::Interpolator::Bezier (global::DynamicArray< T > const & v, global::DynamicArray< T > const & t, float s, bool const closed = false) inline static
Piecewise cubic Bezier interpolation of the values in v and their corresponding tangents in t at position s.
The position in range [0,1] is mapped to the array size. If closed is true, the values are treated as being periodic, resulting in a closed curve. Also see http://local.wasp.uwa.edu.au/~pbourke/geometry/bezier/cubicbezier.html.
References evalPolynomial(), getInterval(), and gale::global::DynamicArray< T >::getSize().
BSpline()
template<class T > static T gale::math::Interpolator::BSpline (global::DynamicArray< T > const & v, float s, bool const closed = false) inline static
Uniform cubic B-Spline approximation of the values in v ("de Boor" points) at position s.
The position in range [0,1] is mapped to the array size. If closed is true, the values are treated as being periodic, resulting in a closed curve. Also see http://blackpawn.com/texts/splines/.
References evalPolynomial(), getInterval(), and gale::global::DynamicArray< T >::getSize().
CatmullRom()
template<class T > static T gale::math::Interpolator::CatmullRom (global::DynamicArray< T > const & v, float s, bool const closed = false) inline static
Piecewise cubic Catmull-Rom interpolation of the values in v at position s.
The position in range [0,1] is mapped to the array size. If closed is true, the values are treated as being periodic, resulting in a closed curve. Also see http://blackpawn.com/texts/splines/.
References evalPolynomial(), getInterval(), and gale::global::DynamicArray< T >::getSize().
Hermite()
template<class T > static T gale::math::Interpolator::Hermite (global::DynamicArray< T > const & v, global::DynamicArray< T > const & t, float s, bool const closed = false) inline static
Piecewise cubic Hermite interpolation of the values in v and their corresponding tangents in t at position s.
The position in range [0,1] is mapped to the array size. If closed is true, the values are treated as being periodic, resulting in a closed curve. Also see http://www.cubic.org/docs/hermite.htm.
References evalPolynomial(), getInterval(), and gale::global::DynamicArray< T >::getSize().
getInterval()
static float gale::math::Interpolator::getInterval (int const n, float const s, bool const closed, int & i0, int & i1) inline static private
Returns the indices i0 and i1 for position s into an array with maximum index n (the position in range [0,1] is mapped to the array size).
If closed is true, the array is treated as being periodic, resulting in the indices to wrap. The return value equals the position scaled to range [0,1] relative to the interval.
References G_ASSERT, and gale::math::roundToZero().
Referenced by Bezier(), BSpline(), CatmullRom(), Cosine(), Hermite(), and Linear().
evalPolynomial()
template<class T > static T gale::math::Interpolator::evalPolynomial (T const & v0, T const & v1, T const & v2, T const & v3, signed char const (&) w[16], float const f, float const s) inline static private
Evaluates the cubic polynomial constructed from the values v0, v1 v2, v3, the weights in w and the factor f, at position s.
Referenced by Bezier(), BSpline(), CatmullRom(), and Hermite().
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/interpolator.h (Last modified in 5275de5)