GALE: gale::model::Plane Class Reference
gale::model::Plane Class Reference
Plane class implementation based on the equation required by glClipPlane():
#include <plane.h>
Public Member Functions
Constructors
Plane (math::Vec3d const &normal=-math::Vec3d::Z(), double const distance=0)
Constructs a plane from a normal and a distance to the origin.
Plane (math::Vec3d const &a, math::Vec3d const &b, math::Vec3d const &c)
Constructs a plane from three vectors a, b and c on that plane.
Element access methods
double * data ()
Returns a pointer to the internal plane equation.
double const * data () const
Returns a constant pointer to the internal plane equation.
operator double * ()
Casts this plane to a double pointer, e.g.
operator double const * () const
Casts this plane to a double const pointer, e.g.
Component access methods
math::Vec3d const & getNormal () const
Returns the plane's normal vector.
void setNormal (math::Vec3d const &normal)
Sets the plane's normal vector.
double getDistance () const
Returns the plane's distance to the origin.
void setDistance (double const distance)
Sets the plane's distance to the origin.
Miscellaneous methods
double distanceTo (math::Vec3d const &v) const
Returns the distance of v to the plane along the normal vector.
double normalize ()
Normalizes the plane equation so its normal vector length equals 1.
Private Attributes
math::Vec3d m_normal
The plane's normal vector (A, B, C in the formula).
double m_distance
Negative distance to the origin (D in the formula).
Detailed Description
Plane class implementation based on the equation required by glClipPlane():
1) A*x + B*y + C*z + D = 0
Here, A, B, C are the components of the normal vector, and D is the negative distance to the plane for any point x, y, z on the plane. Note that in the Hessian Normal Form (HNF), D is changed in sign so it becomes the positive distance to the plane:
2) A*x + B*y + C*z = D
While internally equation 1) is used, all public methods assume the HNF, i.e. equation 2) to be used, as it is more natural to deal with positive distances.
OpenGL example usage:
Plane p(Vec3d(0,1,-1),0.5);
glClipPlane(GL_CLIP_PLANE0,p);
Member Function Documentation
operator double *()
gale::model::Plane::operator double * () inline
Casts this plane to a double pointer, e.g.
for use with glClipPlane(). As an intended side effect, this also provides indexed data access.
References data().
operator double const *()
gale::model::Plane::operator double const * () const inline
Casts this plane to a double const pointer, e.g.
for use with glClipPlane(). As an intended side effect, this also provides indexed data access.
References data().
normalize()
double gale::model::Plane::normalize () inline
Normalizes the plane equation so its normal vector length equals 1.
Returns the length before normalization.
References gale::math::Vector< N, T >::length(), m_distance, and m_normal.
Referenced by Plane().
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/model/plane.h (Last modified in a6c7904)