GALE: gale::system::Timer Class Reference
gale::system::Timer Class Reference
Simple timing class with resume capability.
#include <timer.h>
Public Member Functions
Timer ()
The default constructor resets the timing, so there no need to call reset() manually.
~Timer ()
On Windows, the last destructor of any Timer instance unlocks the current from running on the first CPU only.
bool reset ()
Resets the timing to start from zero.
bool start ()
Sets a new start time for the timer.
bool stop (double &seconds)
Returns the elapsed time in seconds since reset() was called and stops the timing.
bool elapsed (double &seconds)
Returns the elapsed time in seconds since reset() was called without stopping the timing.
Static Public Member Functions
static void sleep (unsigned int const milliseconds)
Suspends the execution of the current thread for the given amount of milliseconds.
Private Attributes
long long m_offset
Stores the total time since the last reset.
LARGE_INTEGER m_start
Stores the last time when start() was called.
LARGE_INTEGER m_stop
Stores the last time when stop() was called.
Static Private Attributes
static unsigned int s_instances =0
This is a reference counter for the instances of this class.
static DWORD_PTR s_mask =0
Needed restore the affinity mask after the last instance's destruction.
Detailed Description
Simple timing class with resume capability.
Constructor & Destructor Documentation
Timer()
gale::system::Timer::Timer () inline
The default constructor resets the timing, so there no need to call reset() manually.
On Windows, this also locks the current thread to the first CPU for compatibility.
References reset(), s_instances, s_mask, and ~Timer().
~Timer()
gale::system::Timer::~Timer () inline
On Windows, the last destructor of any Timer instance unlocks the current from running on the first CPU only.
Referenced by Timer().
Member Function Documentation
sleep()
static void gale::system::Timer::sleep (unsigned int const milliseconds) inline static
Suspends the execution of the current thread for the given amount of milliseconds.
stop()
bool gale::system::Timer::stop (double & seconds) inline
Returns the elapsed time in seconds since reset() was called and stops the timing.
It may be resumed by calling start() again.
References m_offset, m_start, and m_stop.
Referenced by elapsed().
elapsed()
bool gale::system::Timer::elapsed (double & seconds) inline
Returns the elapsed time in seconds since reset() was called without stopping the timing.
References m_offset, m_start, m_stop, s_instances, start(), and stop().
Referenced by gale::wrapgl::MinimalWindow::processEvents().
Member Data Documentation
m_offset
gale::system::Timer::m_offset private
Stores the total time since the last reset.
Referenced by elapsed(), reset(), and stop().
m_start
gale::system::Timer::m_start private
Stores the last time when start() was called.
Referenced by elapsed(), start(), and stop().
m_stop
gale::system::Timer::m_stop private
Stores the last time when stop() was called.
Referenced by elapsed(), and stop().
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/system/timer.h (Last modified in 5275de5)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/timer.cpp (Last modified in a6c7904)