GALE: gale::wrapgl::Camera Class Reference
gale::wrapgl::Camera Class Reference
This class defines a camera with a projection matrix and modelview transformation that projects onto a given screen space portion of the render surface that it is attached to.
#include <camera.h>
Classes
class Frustum
A class to represent the camera's view frustum.
struct ScreenSpace
Stores the location and size of the render surface portion that the camera projects to.
Public Member Functions
Camera (RenderSurface const *surface=NULL, double const fov=math::Constd::PI() *0.25, double const clip_near=0.001, double const clip_far=1000.0)
Initializes the camera to perspective projection with a screen space that matches the dimensions of the given surface or, if not given, the current viewport.
Frustum & frustum ()
Returns a reference to the camera's view frustum.
bool isCurrent () const
Returns whether this the current (i.e. last applied) camera.
void apply (bool const force=false)
Applies all camera settings to the current render context.
Screen space related methods
ScreenSpace const & getScreenSpace () const
Returns the currently set screen space.
void setScreenSpaceOrigin (int const x, int const y)
Sets screen space origin to use.
void setScreenSpaceDimensions (int const width, int const height)
Sets screen space dimensions to use.
bool hasScreenSpaceChanged () const
Returns whether the screen space has changed since the camera was last made current.
Projection related methods
math::Mat4d const & getProjection () const
Returns the current projection matrix.
void setProjection (math::Mat4d const &projection)
Sets the projection matrix.
bool hasProjectionChanged () const
Returns whether the projection matrix has changed since the camera was last made current.
Perspective projection related methods
double getFOV () const
Returns the camera's current vertical field of view.
void setFOV (double const fov)
Sets the vertical field of view the camera should use.
double getNearClipping () const
Returns the camera's current near clipping plane distance.
void setNearClipping (double const clip_near)
Sets the near clipping plane distance the camera should use.
double getFarClipping () const
Returns the camera's current far clipping plane distance.
void setFarClipping (double const clip_far)
Sets the far clipping plane distance the camera should use.
Modelview transformation related methods
math::HMat4f const & getModelview () const
Returns the current modelview transformation.
void setModelview (math::HMat4f const &modelview)
Sets the modelview transformation.
bool hasModelviewChanged () const
Returns whether the modelview transformation has changed since the camera was last made current.
Absolute transformations in the world coordinate system
void align (model::AABB const &box)
Transforms the camera so that it looks along the negative z-axis with the y-axis facing up and the given bounding box fitting into the frustum.
math::Vec3f const & getPosition () const
Sets the camera's location to the given position.
void setPosition (math::Vec3f const &position)
Sets the camera's location to the given position.
Relative transformations in the camera coordinate system
void strafe (float const distance)
Moves the camera right (for a positive distance) or left along its x-axis.
void elevate (float const distance)
Moves the camera up (for a positive distance) or down along its y-axis.
void approach (float const distance)
Moves the camera forward (for a positive distance) or backward along its z-axis.
void rotate (math::Vec3f const &axis, double const angle)
Rotates the camera around the given axis about the given angle.
void pitch (double const angle)
Rotates the camera about its x-axis.
void yaw (double const angle)
Rotates the camera about its y-axis.
void roll (double const angle)
Rotates the camera about its z-axis.
Static Public Member Functions
static Camera * getCurrent ()
Returns a pointer to the camera that was last made current, or NULL if there is no current camera.
Private Attributes
RenderSurface const * m_surface
The surface that the camera is attached to.
Frustum m_frustum
The camera's view frustum.
ScreenSpace m_screen
The camera's current screen space.
bool m_screen_changed
Dirty flag for the screen space.
double m_fov
The camera's vertical field of view.
double m_clip_near
The camera's near clipping plane distance.
double m_clip_far
The camera's far clipping plane distance.
math::Mat4d m_projection
Projection matrix of the camera.
bool m_projection_changed
Dirty flag for projection matrix.
math::HMat4f m_modelview
Modelview transformation of the camera.
math::HMat4f m_modelview_inv
Inverse modelview transformation of the camera.
bool m_modelview_changed
Dirty flag for the modelview transformation.
Static Private Attributes
static Camera * s_current =NULL
Common pointer to the current camera.
Detailed Description
This class defines a camera with a projection matrix and modelview transformation that projects onto a given screen space portion of the render surface that it is attached to.
The camera's coordinate system equals OpenGL's, i.e. it is a right-handed coordinate system where the camera looks forward long the negative z-axis, the positive y-axis marks the "up" direction and the positive x-axis marks the "right" direction.
Constructor & Destructor Documentation
Camera()
gale::wrapgl::Camera::Camera (RenderSurface const * surface = NULL, double const fov = math::Constd::PI()*0.25, double const clip_near = 0.001, double const clip_far = 1000.0) inline
Initializes the camera to perspective projection with a screen space that matches the dimensions of the given surface or, if not given, the current viewport.
The camera's vertical field of view and clipping plane distances can be specified by fov, clip_near and clip_far respectively. The modelview matrix is set to identity, so the camera looks down the negative z-axis.
References G_ASSERT_OPENGL, gale::wrapgl::Camera::ScreenSpace::height, gale::math::HMatrix4< T >::IDENTITY(), m_clip_far, m_clip_near, m_fov, m_screen, m_screen_changed, gale::math::Matrix4< T >::Factory::PerspectiveProjection(), setModelview(), setProjection(), gale::wrapgl::Camera::ScreenSpace::width, gale::wrapgl::Camera::ScreenSpace::x, and gale::wrapgl::Camera::ScreenSpace::y.
Member Function Documentation
getCurrent()
static Camera* gale::wrapgl::Camera::getCurrent () inline static
Returns a pointer to the camera that was last made current, or NULL if there is no current camera.
References s_current.
Referenced by isCurrent().
apply()
void gale::wrapgl::Camera::apply (bool const force = false)
Applies all camera settings to the current render context.
If force is true, the camera settings are also applied if they did not change.
References gale::wrapgl::Camera::Frustum::calculate(), gale::wrapgl::RenderSurface::dimensions(), G_ASSERT_OPENGL, gale::wrapgl::RenderSurface::Dimensions::height, gale::wrapgl::Camera::ScreenSpace::height, m_frustum, m_modelview, m_modelview_changed, m_modelview_inv, m_projection, m_projection_changed, m_screen, m_screen_changed, m_surface, s_current, gale::wrapgl::RenderSurface::Dimensions::width, gale::wrapgl::Camera::ScreenSpace::width, gale::wrapgl::Camera::ScreenSpace::x, and gale::wrapgl::Camera::ScreenSpace::y.
Referenced by gale::wrapgl::Logo::draw(), and isCurrent().
hasScreenSpaceChanged()
bool gale::wrapgl::Camera::hasScreenSpaceChanged () const inline
Returns whether the screen space has changed since the camera was last made current.
References m_screen_changed.
hasProjectionChanged()
bool gale::wrapgl::Camera::hasProjectionChanged () const inline
Returns whether the projection matrix has changed since the camera was last made current.
References m_projection_changed.
hasModelviewChanged()
bool gale::wrapgl::Camera::hasModelviewChanged () const inline
Returns whether the modelview transformation has changed since the camera was last made current.
References m_modelview_changed.
align()
void gale::wrapgl::Camera::align (model::AABB const & box) inline
Transforms the camera so that it looks along the negative z-axis with the y-axis facing up and the given bounding box fitting into the frustum.
References gale::model::AABB::center(), gale::model::AABB::getDepth(), gale::model::AABB::getHeight(), gale::model::AABB::getWidth(), gale::math::HMatrix4< T >::Factory::LookAt(), m_fov, gale::math::max(), setModelview(), and gale::math::Vector< N, T >::Y().
strafe()
void gale::wrapgl::Camera::strafe (float const distance) inline
Moves the camera right (for a positive distance) or left along its x-axis.
References gale::math::HMatrix4< T >::getPositionVector(), gale::math::HMatrix4< T >::getRightVector(), m_modelview, and m_modelview_changed.
elevate()
void gale::wrapgl::Camera::elevate (float const distance) inline
Moves the camera up (for a positive distance) or down along its y-axis.
References gale::math::HMatrix4< T >::getPositionVector(), gale::math::HMatrix4< T >::getUpVector(), m_modelview, and m_modelview_changed.
approach()
void gale::wrapgl::Camera::approach (float const distance) inline
Moves the camera forward (for a positive distance) or backward along its z-axis.
References gale::math::HMatrix4< T >::getBackwardVector(), gale::math::HMatrix4< T >::getPositionVector(), m_modelview, and m_modelview_changed.
pitch()
void gale::wrapgl::Camera::pitch (double const angle) inline
Rotates the camera about its x-axis.
For a positive angle, the camera will look up.
References gale::math::HMatrix4< T >::getRightVector(), m_modelview, and rotate().
yaw()
void gale::wrapgl::Camera::yaw (double const angle) inline
Rotates the camera about its y-axis.
For a positive angle, the camera will look left.
References gale::math::HMatrix4< T >::getUpVector(), m_modelview, and rotate().
roll()
void gale::wrapgl::Camera::roll (double const angle) inline
Rotates the camera about its z-axis.
For a positive angle, the camera will tilt left.
References gale::math::HMatrix4< T >::getBackwardVector(), m_modelview, and rotate().
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/camera.h (Last modified in a6c7904)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/camera.cpp (Last modified in a6c7904)