GALE: gale::wrapgl::PreparedMesh Class Reference
gale::wrapgl::PreparedMesh Class Reference
A class to prepare a mesh for optimal rendering on the GPU.
#include <preparedmesh.h>
Public Member Functions
void compile (model::Mesh const &mesh)
Generates the primitive index arrays from the mesh data structure and calculates vertex normals from averaged face normals.
bool hasData () const
Returns whether the mesh contains something to render.
int numVertices () const
Returns the number of vertices in the mesh.
int numNormals () const
Returns the number of normals in the mesh.
model::Mesh::VectorArray::Type const * vertexAccess () const
Returns a pointer to the vertices as suitable for reading the data.
model::Mesh::VectorArray::Type const * normalAccess () const
Returns a pointer to the normals as suitable for reading the data.
model::Mesh::VectorArray::Type const * vertexPointer () const
Returns a pointer to the vertices as suitable for glVertexPointer().
model::Mesh::VectorArray::Type const * normalPointer () const
Returns a pointer to the normals as suitable for glNormalPointer().
int numPoints () const
Returns the number of points in this mesh.
int numLines () const
Returns the number of lines in this mesh.
int numTriangles () const
Returns the number of triangles in this mesh.
int numQuads () const
Returns the number of quadrilaterals in this mesh.
int numPolys () const
Returns the number of polygons in this mesh.
Public Attributes
model::AABB box
The mesh's axis-aligned bounding box.
Private Types
enum PrimitiveIndices {
PI_POINTS, PI_LINES, PI_TRIANGLES, PI_QUADS,
PI_COUNT
}
Names for the primitives stored in the indices table.
Private Attributes
model::Mesh::VectorArray m_vertices
Array of vertex positions.
model::Mesh::VectorArray m_normals
Array of vertex normals.
model::Mesh::IndexTable m_primitives
Table of vertex indices describing primitives.
model::Mesh::IndexTable m_polygons
Table of vertex indices describing polygons.
Static Private Attributes
static GLenum const GL_PRIM_TYPE [PI_COUNT]
OpenGL enums for the primitive types.
Friends
struct Renderer
Detailed Description
A class to prepare a mesh for optimal rendering on the GPU.
Member Enumeration Documentation
PrimitiveIndices
enum gale::wrapgl::PreparedMesh::PrimitiveIndices private
Names for the primitives stored in the indices table.
Enumerator
PI_POINTS
The first array of indices describes points.
PI_LINES
The second array of indices describes lines.
PI_TRIANGLES
The third array of indices describes triangles.
PI_QUADS
The fourth array of indices describes quadrilaterals.
PI_COUNT
Special entry to name the number of primitive enum entries.
Member Function Documentation
compile()
void gale::wrapgl::PreparedMesh::compile (model::Mesh const & mesh)
Generates the primitive index arrays from the mesh data structure and calculates vertex normals from averaged face normals.
References gale::global::DynamicArray< T >::getSize(), gale::math::Vector< N, T >::getX(), gale::math::Vector< N, T >::getY(), gale::math::Vector< N, T >::getZ(), gale::model::Mesh::neighbors, gale::math::Vector< N, T >::normalize(), gale::model::Mesh::orbit(), gale::global::DynamicArray< T >::setSize(), gale::math::Vector< N, T >::setX(), gale::model::Mesh::vertices, and gale::math::Vector< N, T >::ZERO().
Referenced by gale::wrapgl::Logo::Logo().
Member Data Documentation
GL_PRIM_TYPE
GLenum const gale::wrapgl::PreparedMesh::GL_PRIM_TYPE static private
Initial value:
={
    GL_POINTS
,   GL_LINES
,   GL_TRIANGLES
,   GL_QUADS
}
OpenGL enums for the primitive types.
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/preparedmesh.h (Last modified in a6c7904)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/preparedmesh.cpp (Last modified in a6c7904)