GALE: gale::wrapgl::DefaultWindow Class Reference
gale::wrapgl::DefaultWindow Class Reference
This class provides a convenient default window along with camera navigation using the mouse to be able to easily implement applications that require simple scene interaction.
#include <defaultwindow.h>
Public Types
enum MouseEvent {
ME_BUTTON_NONE = 0, ME_BUTTON_LEFT = 1 << 0, ME_BUTTON_MIDDLE = 1 << 1, ME_BUTTON_RIGHT = 1 << 2,
ME_WHEEL_SCROLL = 1 << 3
}
Defines bit masks for mouse events.
Public Types inherited from gale::wrapgl::RenderSurface
typedef HWND WindowHandle
Type definition for a window handle the render surface belongs to.
Public Member Functions
DefaultWindow (LPCTSTR title, int const client_width, int const client_height, global::AttributeListi const *const context_attr=NULL, global::AttributeListi const *const pixel_attr=NULL, int const samples=8)
Creates a window with reasonable defaults set.
bool toggleFullScreen (bool state)
Turns full screen mode on or off, returns whether it was successful.
void onResize (int width, int height)
Adjusts the camera if the window size changes.
void onPaint ()
Overrides the default paint event handler to draw a logo.
virtual void onRender ()
Applications that wish to benefit from extra stuff (like logos) being automatically rendered should override this method instead of onPaint().
virtual void onKeyEvent (char key)
Captures the Escape key to quit the application and Return to toggle full-screen mode.
virtual void onMouseEvent (int x, int y, int wheel, int event)
Translates mouse events into camera movements.
Public Member Functions inherited from gale::wrapgl::MinimalWindow
MinimalWindow (LPCTSTR title, int width, int height, global::AttributeListi const *const context_attr=NULL, global::AttributeListi const *const pixel_attr=NULL, int const samples=8)
Creates a window with the specified title, a client size of the given width and height, an OpenGL context with the attributes in context_attr attached to it and a pixel format that matches pixel_attr.
double getTimeout () const
Returns the currently set timeout value in seconds.
void setTimeout (double const timeout)
Sets the current timeout value in seconds.
void processEvents ()
Starts the event processing and does not return until the window gets closed.
void repaint ()
Invalidates the whole window and requests to repaint its contents.
virtual bool onIdle ()
Event handler that gets called when there are no messages to process.
virtual void onTimeout ()
Event handler that gets called when the timeout value has been reached.
virtual void onClose ()
Event handler that gets called when a window should terminate.
Public Member Functions inherited from gale::wrapgl::RenderSurface
RenderSurface (global::AttributeListi const *const context_attr=NULL, global::AttributeListi const *const pixel_attr=NULL, int const samples=8)
Creates a minimal render surface and current render context with the attributes in context_attr.
~RenderSurface ()
Destroys render surface.
WindowHandle const & windowHandle () const
Returns the handle to the window associated with this render surface.
ContextHandle const & contextHandle () const
Returns the handle to the OpenGL context associated with this render surface.
bool makeCurrent ()
Makes this the active OpenGL context for the current thread.
Dimensions dimensions () const
Returns the width and height of this render surface.
Protected Member Functions
LRESULT handleMessage (UINT const uMsg, WPARAM const wParam, LPARAM const lParam)
Handles window messages and forwards them to the event methods.
Protected Member Functions inherited from gale::wrapgl::MinimalWindow
LRESULT handleMessage (UINT const uMsg, WPARAM const wParam, LPARAM const lParam)
Handles window messages and forwards them to the event methods.
Protected Member Functions inherited from gale::wrapgl::RenderSurface
bool createDeviceContext (int pixel_format=0)
Creates a minimal device context and associated window with either a default or the specified pixel_format.
void destroyDeviceContext ()
Releases the device context and destroys the associated window.
void destroyRenderContext ()
Deletes the render context only.
Protected Attributes
wrapgl::Camera m_camera
The window's default camera.
bool m_fullscreen
The current full screen state.
Logo m_logo
The overlay logo.
Protected Attributes inherited from gale::wrapgl::MinimalWindow
bool m_close_requested
Indicates whether the window should be closed.
double m_timeout
Timeout event value in seconds.
system::Timer m_timer
Timer to trigger the timeout event.
Protected Attributes inherited from gale::wrapgl::RenderSurface
WindowHandle m_window
Handle to the window owning the OpenGL context.
ContextHandle m_context
Handle to the OpenGL context.
Static Protected Attributes
static UINT_PTR const ID_ABOUT_DLG =0x00AB
Defines a custom ID for the About dialog menu entry.
Static Protected Attributes inherited from gale::wrapgl::RenderSurface
static PIXELFORMATDESCRIPTOR const s_pfd
Pixel format description for the default format.
Additional Inherited Members
Static Public Member Functions inherited from gale::wrapgl::RenderSurface
static ContextHandle getCurrent ()
Returns the active OpenGL context for the current thread.
static bool setCurrent (ContextHandle const &handle)
Sets the active OpenGL context for the current thread.
Static Public Attributes inherited from gale::wrapgl::RenderSurface
static int const DEFAULT_COLOR_BITS = 24
The color bits to use if not further specified.
static int const DEFAULT_DEPTH_BITS = 24
The depth bits to use if not further specified.
static int const DEFAULT_STENCIL_BITS = 8
The stencil bits to use if not further specified.
Detailed Description
This class provides a convenient default window along with camera navigation using the mouse to be able to easily implement applications that require simple scene interaction.
Member Enumeration Documentation
MouseEvent
enum gale::wrapgl::DefaultWindow::MouseEvent
Defines bit masks for mouse events.
Enumerator
ME_BUTTON_NONE
No mouse button was pressed.
ME_BUTTON_LEFT
The left mouse button was pressed.
ME_BUTTON_MIDDLE
The middle mouse button was pressed.
ME_BUTTON_RIGHT
The right mouse button was pressed.
ME_WHEEL_SCROLL
The mouse wheel was scrolled.
Member Function Documentation
onRender()
virtual void gale::wrapgl::DefaultWindow::onRender () inline virtual
Applications that wish to benefit from extra stuff (like logos) being automatically rendered should override this method instead of onPaint().
Referenced by onPaint().
onKeyEvent()
virtual void gale::wrapgl::DefaultWindow::onKeyEvent (char key) inline virtual
Captures the Escape key to quit the application and Return to toggle full-screen mode.
References m_fullscreen, onMouseEvent(), and toggleFullScreen().
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/defaultwindow.h (Last modified in a6c7904)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/defaultwindow.cpp (Last modified in a6c7904)