GALE: gale::math::Color< N, T > Class Template Reference
gale::math::Color< N, T > Class Template Reference
Color representation based on an RGB(A)-tuple.
#include <color.h>
Public Types
typedef T Type
The data type of this template instance.
Public Member Functions
RGB(A) color model channel access methods
T getR ()
Returns the red channel.
T const & getR () const
Returns a constant reference to the red channel.
void setR (T const r)
Assigns a new value to the red channel.
T getG ()
Returns the green channel.
T const & getG () const
Returns a constant reference to the green channel.
void setG (T const g)
Assigns a new value to the green channel.
T getB ()
Returns the blue channel.
T const & getB () const
Returns a constant reference to the blue channel.
void setB (T const b)
Assigns a new value to the blue channel.
T getA ()
Returns the alpha channel.
T const & getA () const
Returns a constant reference to the alpha channel.
void setA (T const a)
Assigns a new value to the alpha channel.
Miscellaneous methods
Color complement () const
Returns the color's complementary color.
Mixing methods, see <http://en.wikipedia.org/wiki/Color_mixing>.
Color mixAdd (Color const &c, double s=0.5) const
Returns the additive mix between this color and color c in ratio s.
Color mixSub (Color const &c, double s=0.5) const
Returns the subtractive mix between this color and color c in ratio s.
Public Member Functions inherited from gale::math::TupleBase< N, T, Color< N, T > >
TupleBase ()
Create a tuple whose elements are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
TupleBase (T const e0, T const e1)
Allows to initialize 2-tuples directly.
TupleBase (T const e0, T const e1, T const e2)
Allows to initialize 3-tuples directly.
TupleBase (T const e0, T const e1, T const e2, T const e3)
Allows to initialize 4-tuples directly.
T * data ()
Returns a pointer to the internal data array.
T const * data () const
Returns a constant pointer to the internal data array.
operator T * ()
Casts this tuple to a pointer of type T.
operator T const * () const
Casts this tuple to a pointer of type T const.
void set (T const e0, T const e1)
Assigns new values to the first two tuple elements.
void set (T const e0, T const e1, T const e2)
Assigns new values to the first three tuple elements.
void set (T const e0, T const e1, T const e2, T const e3)
Assigns new values to the first four tuple elements.
T minElement () const
Determines the minimum element of this tuple.
T maxElement () const
Determines the maximum element of this tuple.
T absMinElement () const
Determines the absolute minimum element of this tuple.
T absMaxElement () const
Determines the absolute maximum element of this tuple.
Color< N, T > minElements (Color< N, T >const &t) const
Calculates the element-wise minimum of this tuple and tuple t.
Color< N, T > maxElements (Color< N, T >const &t) const
Calculates the element-wise maximum of this tuple and tuple t.
Color< N, T >const & operator+= (Color< N, T >const &t)
Element-wise increments this tuple by tuple t.
Color< N, T >const & operator-= (Color< N, T >const &t)
Element-wise decrements this tuple by tuple t.
Color< N, T >const & operator*= (Color< N, T >const &t)
Element-wise multiplies this tuple by tuple t.
Color< N, T >const & operator/= (Color< N, T >const &t)
Element-wise divides this tuple by tuple t.
Color< N, T >const & operator*= (T const s)
Multiplies each element of this tuple by a scalar s.
Color< N, T >const & operator/= (T const s)
Divides each element of this tuple by a scalar s.
Static Public Member Functions
template<typename RT , class RI >
static Color random (RandomBase< RT, RI > &r)
Returns a random color generated by r.
Predefined constants
In order to avoid the so called "static initialization order fiasco", static methods instead of static variables are used here, see http://www.parashift.com/c++-faq-lite/ctors.html#faq-10.14.
static Color const & BLACK ()
Returns a color which represents black.
static Color const & BLUE ()
Returns a color which represents blue.
static Color const & GREEN ()
Returns a color which represents green.
static Color const & CYAN ()
Returns a color which represents cyan.
static Color const & RED ()
Returns a color which represents red.
static Color const & MAGENTA ()
Returns a color which represents magenta.
static Color const & YELLOW ()
Returns a color which represents yellow.
static Color const & WHITE ()
Returns a color which represents white.
Static Public Member Functions inherited from gale::math::ColorChannel< T >
static T MIN_VALUE ()
Returns the minimum value allowed for a color channel.
static T MAX_VALUE ()
Returns the maximum value allowed for a color channel.
static double RANGE ()
Returns the value range allowed for a color channel.
Static Public Attributes
static int const Channels =N
The number of channels of this template instance.
Private Types
typedef TupleBase< N, T, Color
< N, T > > Base
This type definition simplifies base class access to identifiers that are not visible until instantiation time because they do not dependent on template arguments.
Friends
Convenience operators for named methods
Color operator! (Color const &c)
Returns the complementary color of color c.
Color operator& (Color const &a, Color const &b)
Returns the additive mix between colors a and b.
Color operator| (Color const &a, Color const &b)
Returns the subtractive mix between colors a and b.
Friends inherited from gale::math::TupleBase< N, T, Color< N, T > >
Constructors
Color (unsigned int const mask)
Sets each color channel to either the maximum or minimum value depending on the bits set in mask.
Color ()
Initialize to black by default.
Color (T const r, T const g, T const b)
Allows to initialize 3-channel colors directly.
Color (T const r, T const g, T const b, T const a)
Allows to initialize 4-channel colors directly.
template<typename U >
Color (Color< N, U > const &v)
Converts a color of different type but with the same amount of channels to this type with correct range mapping applied.
Additional Inherited Members
Protected Attributes inherited from gale::math::TupleBase< N, T, Color< N, T > >
T m_data [N]
Tightly packed array of N elements of type T.
Detailed Description
template<unsigned int N, typename T>
class gale::math::Color< N, T >
Color representation based on an RGB(A)-tuple.
It features predefined constants for commonly used colors and useful operators.
OpenGL example usage:
glColor4ubv(Col4ub::RED());
RGB is an additive color model with primary colors red, green and blue, secondary colors cyan, magenta and yellow, and neutral color white (for fully saturated colors).
Member Typedef Documentation
template<unsigned int N, typename T> typedef TupleBase<N,T,Color<N,T> > gale::math::Color< N, T >::Base private
This type definition simplifies base class access to identifiers that are not visible until instantiation time because they do not dependent on template arguments.
Constructor & Destructor Documentation
template<unsigned int N, typename T> gale::math::Color< N, T >::Color (unsigned int const mask) inline explicit protected
Sets each color channel to either the maximum or minimum value depending on the bits set in mask.
Bit 0 maps to the first channel, bit 1 to second one and so on. This constructor is required to initialize the static class constants.
References gale::math::TupleBase< N, T, Color< N, T > >::data(), G_ASSERT, gale::meta::LoopFwd< NUM, OP >::iterateIndexMask(), gale::math::ColorChannel< T >::MAX_VALUE(), and gale::math::ColorChannel< T >::MIN_VALUE().
template<unsigned int N, typename T> template<typename U > gale::math::Color< N, T >::Color (Color< N, U > const & v) inline
Converts a color of different type but with the same amount of channels to this type with correct range mapping applied.
References gale::math::TupleBase< N, T, Color< N, T > >::data(), G_ASSERT, gale::meta::LoopFwd< NUM, OP >::iterate(), gale::math::ColorChannel< T >::MIN_VALUE(), and gale::math::ColorChannel< T >::RANGE().
Member Function Documentation
template<unsigned int N, typename T> Color gale::math::Color< N, T >::complement () const inline
Returns the color's complementary color.
As not only hue, but also saturation and value are taken into account, different tints or shades of the same pure color return different complementary colors. An alpha channel is ignored, if present. See http://en.wikipedia.org/wiki/Complementary_color.
References gale::math::Color< N, T >::BLACK(), gale::math::Color< N, T >::getA(), gale::math::Color< N, T >::setA(), and gale::math::Color< N, T >::WHITE().
Referenced by gale::math::Color< N, T >::mixSub().
The documentation for this class was generated from the following file:
include/gale/math/color.h (Last modified in b7b3e5b)
Donations are appreciated via
GALE is generously hosted by