GALE: gale::math::ColorSpaceHSV Class Reference
gale::math::ColorSpaceHSV Class Reference
An HSV (also known as HSB) color space representation, see http://en.wikipedia.org/wiki/List_of_color_spaces_and_their_uses#HSV.
#include <colorspace.h>
Public Member Functions
ColorSpaceHSV (double const hue=0, double const saturation=0, double const value=0)
Initializes the color space to the given hue, saturation and value, or to black by default.
template<unsigned int N, typename T >
ColorSpaceHSV (Color< N, T > const &color)
Initializes the color space to the specified RGB color.
void fromRGB (double const r, double const g, double const b)
Sets the color space to match the given r, g, b values, where all values need to be in range [0,1].
void toRGB (double &r, double &g, double &b) const
Gets the r, g, b values from the color space, where all values are in range [0,1].
Color space access methods
double const & getH () const
Returns a constant reference to the hue.
void setH (double const hue)
Assigns a new hue.
double const & getS () const
Returns a constant reference to the saturation.
void setS (double const saturation)
Assigns a new saturation.
double const & getV () const
Returns a constant reference to the value.
void setV (double const value)
Assigns a new value.
Public Member Functions inherited from gale::math::ColorSpace
template<unsigned int N, typename T >
void setRGB (Color< N, T > const &color)
Sets the color space to the specified RGB color.
template<class C >
C getRGB () const
Gets the RGB representation of the color space for color class C.
Private Attributes
double m_h
The color's hue in range [0,360[.
double m_s
The color's saturation in range [0,100].
double m_v
The color's value in range [0,100].
Detailed Description
An HSV (also known as HSB) color space representation, see http://en.wikipedia.org/wiki/List_of_color_spaces_and_their_uses#HSV.
Constructor & Destructor Documentation
gale::math::ColorSpaceHSV::ColorSpaceHSV (double const hue = 0, double const saturation = 0, double const value = 0) inline
Initializes the color space to the given hue, saturation and value, or to black by default.
Member Function Documentation
void gale::math::ColorSpaceHSV::fromRGB (double const r, double const g, double const b) inline virtual
Sets the color space to match the given r, g, b values, where all values need to be in range [0,1].
Implements gale::math::ColorSpace.
References m_h, m_s, m_v, gale::math::max(), gale::math::min(), and gale::math::wrap().
Referenced by gale::math::ColorModelRYB::RYBHueToRGBHue().
void gale::math::ColorSpaceHSV::toRGB (double & r, double & g, double & b) const inline virtual
Gets the r, g, b values from the color space, where all values are in range [0,1].
Implements gale::math::ColorSpace.
References gale::math::clamp(), m_h, m_s, m_v, gale::math::roundToZero(), and gale::math::wrap().
Referenced by gale::math::ColorModelRYB::RYBHueToRGBHue().
The documentation for this class was generated from the following file:
include/gale/math/colorspace.h (Last modified in b7b3e5b)
Donations are appreciated via
GALE is generously hosted by