GALE: gale::math::ColorModelRYB Class Reference
gale::math::ColorModelRYB Class Reference
An RYB color model representation, see http://threekings.tk/mirror/ryb_TR.pdf.
#include <colormodel.h>
Public Member Functions
ColorModelRYB (double const red=1, double const yellow=1, double const blue=1)
Initializes the color model to the given red, yellow and blue percentages, or to black by default.
template<unsigned int N, typename T >
ColorModelRYB (Color< N, T > const &color)
Initializes the color model to the specified RGB color.
void fromRGB (double const r, double const g, double const b)
Sets the color model to match the given r, g, b values, where all values need to be in range [0,1].
void toRGB (double &r, double &g, double &b) const
Gets the r, g, b values from the color model, where all values are in range [0,1].
Color model access methods
double const & getR () const
Returns a constant reference to the red percentage.
void setR (double const red)
Assigns a new red percentage.
double const & getY () const
Returns a constant reference to the yellow percentage.
void setY (double const yellow)
Assigns a new yellow percentage.
double const & getB () const
Returns a constant reference to the blue percentage.
void setB (double const blue)
Assigns a new blue percentage.
Public Member Functions inherited from gale::math::ColorModel
template<unsigned int N, typename T >
void setRGB (Color< N, T > const &color)
Sets the color model to the specified RGB color.
template<class C >
C getRGB () const
Gets the RGB representation of the color model for color class C.
Static Public Member Functions
Hue conversion methods, see
http://www.daleroose.com/web_design/color_chart/.
static void RYBHueToRGBHue (double const h_ryb, double &h_rgb)
Returns the hue h_rgb in the RGB color model for the color given by the hue h_ryb in the RYB color model.
static void RGBHueToRYBHue (double const h_rgb, double &h_ryb, double const a=0, double const b=360)
Returns the hue h_ryb in the RYB color model for the color given by the hue h_rgb in the RGB color model.
Static Private Member Functions
static Tup3d const & WHITE ()
Returns the RGB coordinates for the white corner in the RYB interpolation cube.
static Tup3d const & RED ()
Returns the RGB coordinates for the red corner in the RYB interpolation cube.
static Tup3d const & YELLOW ()
Returns the RGB coordinates for the yellow corner in the RYB interpolation cube.
static Tup3d const & BLUE ()
Returns the RGB coordinates for the blue corner in the RYB interpolation cube.
static Tup3d const & BLACK ()
Returns the RGB coordinates for the black corner in the RYB interpolation cube.
static Tup3d const & GREEN ()
Returns the RGB coordinates for the green corner in the RYB interpolation cube.
static Tup3d const & PURPLE ()
Returns the RGB coordinates for the purple corner in the RYB interpolation cube.
static Tup3d const & ORANGE ()
Returns the RGB coordinates for the orange corner in the RYB interpolation cube.
Private Attributes
double m_r
The color's red percentage in range [0,1].
double m_y
The color's yellow percentage in range [0,1].
double m_b
The color's blue percentage in range [0,1].
Detailed Description
An RYB color model representation, see http://threekings.tk/mirror/ryb_TR.pdf.
Constructor & Destructor Documentation
ColorModelRYB()
gale::math::ColorModelRYB::ColorModelRYB (double const red = 1, double const yellow = 1, double const blue = 1) inline
Initializes the color model to the given red, yellow and blue percentages, or to black by default.
Member Function Documentation
RYBHueToRGBHue()
static void gale::math::ColorModelRYB::RYBHueToRGBHue (double const h_ryb, double & h_rgb) inline static
Returns the hue h_rgb in the RGB color model for the color given by the hue h_ryb in the RYB color model.
References gale::math::ColorModelHSV::fromRGB(), gale::math::ColorModelHSV::getH(), gale::math::ColorModelHSV::toRGB(), and toRGB().
RGBHueToRYBHue()
static void gale::math::ColorModelRYB::RGBHueToRYBHue (double const h_rgb, double & h_ryb, double const a = 0, double const b = 360) inline static
Returns the hue h_ryb in the RYB color model for the color given by the hue h_rgb in the RGB color model.
Arguments a and b are only used internally for the approximation using nested intervals.
References abs(), and gale::math::Numerics< T >::ZERO_TOLERANCE().
fromRGB()
void gale::math::ColorModelRYB::fromRGB (double const r, double const g, double const b) inline virtual
Sets the color model to match the given r, g, b values, where all values need to be in range [0,1].
Implements gale::math::ColorModel.
References gale::math::ColorModelHSV::fromRGB(), gale::math::ColorModelHSV::getH(), gale::math::ColorModelHSV::getS(), gale::math::ColorModelHSV::getV(), and gale::math::lerp().
toRGB()
void gale::math::ColorModelRYB::toRGB (double & r, double & g, double & b) const inline virtual
Gets the r, g, b values from the color model, where all values are in range [0,1].
Implements gale::math::ColorModel.
References gale::math::cubic().
Referenced by RYBHueToRGBHue().
WHITE()
static Tup3d const& gale::math::ColorModelRYB::WHITE () inline static private
Returns the RGB coordinates for the white corner in the RYB interpolation cube.
RED()
static Tup3d const& gale::math::ColorModelRYB::RED () inline static private
Returns the RGB coordinates for the red corner in the RYB interpolation cube.
YELLOW()
static Tup3d const& gale::math::ColorModelRYB::YELLOW () inline static private
Returns the RGB coordinates for the yellow corner in the RYB interpolation cube.
BLUE()
static Tup3d const& gale::math::ColorModelRYB::BLUE () inline static private
Returns the RGB coordinates for the blue corner in the RYB interpolation cube.
BLACK()
static Tup3d const& gale::math::ColorModelRYB::BLACK () inline static private
Returns the RGB coordinates for the black corner in the RYB interpolation cube.
GREEN()
static Tup3d const& gale::math::ColorModelRYB::GREEN () inline static private
Returns the RGB coordinates for the green corner in the RYB interpolation cube.
PURPLE()
static Tup3d const& gale::math::ColorModelRYB::PURPLE () inline static private
Returns the RGB coordinates for the purple corner in the RYB interpolation cube.
ORANGE()
static Tup3d const& gale::math::ColorModelRYB::ORANGE () inline static private
Returns the RGB coordinates for the orange corner in the RYB interpolation cube.
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/colormodel.h (Last modified in 5275de5)