GALE: gale::math::ColorModelHSV Class Reference
gale::math::ColorModelHSV Class Reference
An HSV (also known as HSB) color model representation, see http://en.wikipedia.org/wiki/HSL_and_HSV.
#include <colormodel.h>
Public Member Functions
ColorModelHSV (double const hue=0, double const saturation=0, double const value=0)
Initializes the color model to the given hue, saturation and value, or to black by default.
template<unsigned int N, typename T >
ColorModelHSV (Color< N, T > const &color)
Initializes the color model to the specified RGB color.
void fromRGB (double const r, double const g, double const b)
Sets the color model to match the given r, g, b values, where all values need to be in range [0,1].
void toRGB (double &r, double &g, double &b) const
Gets the r, g, b values from the color model, where all values are in range [0,1].
Color model access methods
double const & getH () const
Returns a constant reference to the hue.
void setH (double const hue)
Assigns a new hue.
double const & getS () const
Returns a constant reference to the saturation.
void setS (double const saturation)
Assigns a new saturation.
double const & getV () const
Returns a constant reference to the value.
void setV (double const value)
Assigns a new value.
Public Member Functions inherited from gale::math::ColorModel
template<unsigned int N, typename T >
void setRGB (Color< N, T > const &color)
Sets the color model to the specified RGB color.
template<class C >
C getRGB () const
Gets the RGB representation of the color model for color class C.
Private Attributes
double m_h
The color's hue in range [0,360[.
double m_s
The color's saturation in range [0,100].
double m_v
The color's value in range [0,100].
Detailed Description
An HSV (also known as HSB) color model representation, see http://en.wikipedia.org/wiki/HSL_and_HSV.
Constructor & Destructor Documentation
ColorModelHSV()
gale::math::ColorModelHSV::ColorModelHSV (double const hue = 0, double const saturation = 0, double const value = 0) inline
Initializes the color model to the given hue, saturation and value, or to black by default.
Member Function Documentation
fromRGB()
void gale::math::ColorModelHSV::fromRGB (double const r, double const g, double const b) inline virtual
Sets the color model to match the given r, g, b values, where all values need to be in range [0,1].
Implements gale::math::ColorModel.
References gale::math::max(), gale::math::min(), and gale::math::wrap().
Referenced by gale::math::ColorModelRYB::fromRGB(), and gale::math::ColorModelRYB::RYBHueToRGBHue().
toRGB()
void gale::math::ColorModelHSV::toRGB (double & r, double & g, double & b) const inline virtual
Gets the r, g, b values from the color model, where all values are in range [0,1].
Implements gale::math::ColorModel.
References gale::math::clamp(), gale::math::roundToZero(), and gale::math::wrap().
Referenced by gale::math::ColorModelRYB::RYBHueToRGBHue().
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/colormodel.h (Last modified in 5275de5)