GALE: gale::model::Mesh::Factory Class Reference
gale::model::Mesh::Factory Class Reference
Factory class to create procedural meshes.
#include <mesh.h>
Classes
struct Shape
Methods to create shapes, e.g. for use as extrusion contours.
Static Public Member Functions
static Mesh * Sphere (float const r, int const steps)
Returns a uniformly tesselated sphere of radius r, created using a number of polyhedral subdivision steps from an Icosahedron.
Platonic Solids
Methods to create the five Platonic Solids, each with unit edge length, see http://mathworld.wolfram.com/PlatonicSolid.html.
static Mesh * Tetrahedron ()
Returns a Tetrahedron consisting of 4 vertices, 6 edges and 4 triangle faces.
static Mesh * Octahedron ()
Returns a Octahedron consisting of 6 vertices, 12 edges and 8 triangle faces.
static Mesh * Hexahedron ()
Returns a Hexahedron consisting of 8 vertices, 12 edges and 6 quadrilateral faces.
static Mesh * Icosahedron ()
Returns a Icosahedron consisting of 12 vertices, 30 edges and 20 triangle faces.
static Mesh * Dodecahedron ()
Returns a Dodecahedron consisting of 20 vertices, 30 edges and 12 pentagonal faces.
Ellipse-based meshes
Methods to create meshes that are based on extruded ellipses.
static Mesh * Torus (float const rr, float const rt, int const sr, int const st)
Returns a torus with ring radius rr and tube radius rt.
static Mesh * TorusKnot (float const rk, float const rt, int const sk, int const st, int const p, int const q, float const w=1.0f, float const h=1.0f)
Returns a torus knot with knot radius rk and tube radius rt.
static Mesh * MoebiusStrip (float const rrw, float const rrh, float const rtw, float const rth, int const sr, int const st)
Returns a Möbius Strip with a ring radius width rrw and height rrh, and tube radius width rtw and height rth, where the ring and tube ellipses are divided into sr and st segments respectively.
Miscellaneous surfaces
Methods creating meshes mainly by wrapping a surface grid in space.
static Mesh * Shell (float const rs, float const rt, int const ss, int const st, float const h, int const n)
Generates a shell with shell radius rs and tube radius rt at opening, consisting of ss segments along the shell and.
Product meshes
Methods based on multiplying formulas to yield a 3D composite, see e.g.
http://local.wasp.uwa.edu.au/~pbourke/geometry/supershape3d/. On Paul Bourke's site, "SuperShape 1" is the longitudinal shape, and "SuperShape 2" is the latitudinal shape.
static Mesh * SphericalMapper (math::Formula const &long_form, int const long_segs, math::Formula const &lat_form, int const lat_segs)
Generates a mesh's surface by calculating the spherical product of the formulas long_form and lat_form, evaluated at long_segs and lat_segs samples along the longitude and latitude, respectively.
static Mesh * ToroidalMapper (math::Formula const &long_form, int const long_segs, math::Formula const &lat_form, int const lat_segs)
Generates a mesh's surface by calculating the toroidal product of the formulas long_form and lat_form, evaluated at long_segs and lat_segs samples along the longitude and latitude, respectively.
Static Private Member Functions
static void populateNeighborhood (Mesh *const mesh, float distance, int const valence)
Makes all vertices in the given mesh neighbors that have the specified distance, up to the specified vertex valence.
Helper and debug meshes
Methods to create meshes that are not particularly useful on their own, but are used by other factory methods or for debugging.
typedef global::DynamicArray
< math::HMat4f > MatrixArray
Array of transformation matrices.
static Mesh * Extruder (VectorArray const &path, VectorArray const &contour, bool const closed=true, MatrixArray const *const trans=NULL)
Generates a mesh by extruding the line loop defined by contour along the given path.
static Mesh * GridMapper (math::FormulaR2R3 const &eval, float const s_min, float const s_max, int const s_segs, bool const s_closed, float const t_min, float const t_max, int const t_segs, bool const t_closed)
Generates a mesh's surface by calculating eval at every point on the grid of size s_segs by t_segs which is defined by walking from s_min to s_max in x-direction and from t_min to t_max in y-direction.
static Mesh * Normals (int n, math::Vec3f const *vertices, math::Vec3f const *normals, float const scale=1.0f)
Generates a mesh representing the given normals by n lines starting at the given vertices, optionally with the given scale applied.
Detailed Description
Factory class to create procedural meshes.
Member Function Documentation
Mesh * gale::model::Mesh::Factory::Tetrahedron () static
Returns a Tetrahedron consisting of 4 vertices, 6 edges and 4 triangle faces.
Mesh * gale::model::Mesh::Factory::Octahedron () static
Returns a Octahedron consisting of 6 vertices, 12 edges and 8 triangle faces.
Mesh * gale::model::Mesh::Factory::Hexahedron () static
Returns a Hexahedron consisting of 8 vertices, 12 edges and 6 quadrilateral faces.
Referenced by gale::wrapgl::Logo::Logo().
Mesh * gale::model::Mesh::Factory::Icosahedron () static
Returns a Icosahedron consisting of 12 vertices, 30 edges and 20 triangle faces.
References gale::math::Constants< T >::GOLDEN_RATIO().
Mesh * gale::model::Mesh::Factory::Dodecahedron () static
Returns a Dodecahedron consisting of 20 vertices, 30 edges and 12 pentagonal faces.
References gale::math::Constants< T >::GOLDEN_RATIO().
Mesh * gale::model::Mesh::Factory::Sphere (float const r, int const steps) static
Returns a uniformly tesselated sphere of radius r, created using a number of polyhedral subdivision steps from an Icosahedron.
References gale::global::DynamicArray< T >::getSize(), and gale::model::Mesh::vertices.
Mesh * gale::model::Mesh::Factory::Torus (float const rr, float const rt, int const sr, int const st) static
Returns a torus with ring radius rr and tube radius rt.
The ring and tube circles are divided into sr and st segments respectively.
Mesh * gale::model::Mesh::Factory::TorusKnot (float const rk, float const rt, int const sk, int const st, int const p, int const q, float const w = 1.0f, float const h = 1.0f) static
Returns a torus knot with knot radius rk and tube radius rt.
The tube consist of sk and st segments along the knot and tube respectively. w and h specify the width and height of the knot's spiral, which is obtained by looping through the hole p times with q revolutions before joining its ends, where p and q have to be relatively prime.
References gale::math::Constants< T >::PI().
Mesh * gale::model::Mesh::Factory::MoebiusStrip (float const rrw, float const rrh, float const rtw, float const rth, int const sr, int const st) static
Returns a Möbius Strip with a ring radius width rrw and height rrh, and tube radius width rtw and height rth, where the ring and tube ellipses are divided into sr and st segments respectively.
References gale::math::Constants< T >::PI(), and gale::math::HMatrix4< T >::Factory::RotationZ().
Mesh * gale::model::Mesh::Factory::Shell (float const rs, float const rt, int const ss, int const st, float const h, int const n) static
Generates a shell with shell radius rs and tube radius rt at opening, consisting of ss segments along the shell and.
is given by h, the number of spiral turns by n. For details, see http://local.wasp.uwa.edu.au/~pbourke/geometry/shell/.
References gale::math::Vector< N, T >::getX(), gale::math::Vector< N, T >::getY(), and gale::math::Constants< T >::PI().
Mesh * gale::model::Mesh::Factory::SphericalMapper (math::Formula const & long_form, int const long_segs, math::Formula const & lat_form, int const lat_segs) static
Generates a mesh's surface by calculating the spherical product of the formulas long_form and lat_form, evaluated at long_segs and lat_segs samples along the longitude and latitude, respectively.
References gale::math::Constants< T >::PI().
Mesh * gale::model::Mesh::Factory::ToroidalMapper (math::Formula const & long_form, int const long_segs, math::Formula const & lat_form, int const lat_segs) static
Generates a mesh's surface by calculating the toroidal product of the formulas long_form and lat_form, evaluated at long_segs and lat_segs samples along the longitude and latitude, respectively.
References gale::math::Constants< T >::PI().
Mesh * gale::model::Mesh::Factory::Extruder (VectorArray const & path, VectorArray const & contour, bool const closed = true, MatrixArray const *const trans = NULL) static
Generates a mesh by extruding the line loop defined by contour along the given path.
If close is true, the end of the path is connected to its beginning, else cut faces are created.
References gale::global::DynamicArray< T >::find(), gale::global::DynamicArray< T >::getSize(), gale::math::Vector< N, T >::isCollinear(), gale::model::Mesh::neighbors, gale::global::DynamicArray< T >::setSize(), gale::model::Mesh::vertices, and gale::math::Vector< N, T >::X().
Mesh * gale::model::Mesh::Factory::GridMapper (math::FormulaR2R3 const & eval, float const s_min, float const s_max, int const s_segs, bool const s_closed, float const t_min, float const t_max, int const t_segs, bool const t_closed) static
Generates a mesh's surface by calculating eval at every point on the grid of size s_segs by t_segs which is defined by walking from s_min to s_max in x-direction and from t_min to t_max in y-direction.
s_closed and t_closed denote whether start and end vertices should be shared to close the mesh in the respective direction.
References gale::global::DynamicArray< T >::setSize(), gale::math::Vector< N, T >::setX(), and gale::math::Vector< N, T >::setY().
Mesh * gale::model::Mesh::Factory::Normals (int n, math::Vec3f const * vertices, math::Vec3f const * normals, float const scale = 1.0f) static
Generates a mesh representing the given normals by n lines starting at the given vertices, optionally with the given scale applied.
References gale::model::Mesh::neighbors, gale::global::DynamicArray< T >::setSize(), and gale::model::Mesh::vertices.
void gale::model::Mesh::Factory::populateNeighborhood (Mesh *const mesh, float distance, int const valence) static private
Makes all vertices in the given mesh neighbors that have the specified distance, up to the specified vertex valence.
References gale::meta::OpCmpEqual::evaluate(), gale::global::DynamicArray< T >::getSize(), gale::math::Vector< N, T >::length2(), gale::model::Mesh::neighbors, gale::math::Vector< N, T >::orientedAngle(), gale::math::Vector< N, T >::orthoProjection(), gale::math::Constants< T >::RAD_TO_DEG(), gale::global::DynamicArray< T >::setSize(), and gale::model::Mesh::vertices.
The documentation for this class was generated from the following files:
include/gale/model/mesh.h (Last modified in b7b3e5b)
source/mesh_factory.cpp (Last modified in b7b3e5b)
Donations are appreciated via
GALE is generously hosted by