GALE: gale::math::Quaternion< T > Class Template Reference
gale::math::Quaternion< T > Class Template Reference
Quaternion implementation based on a scalar for the real number part and a vector for the imaginary number part.
#include <quaternion.h>
Public Types
typedef T Type
Definition for external access to the data type.
typedef Vector< 3, T > Vec
Definition of the type of vector used to store the imaginary number parts.
typedef HMatrix4< T > HMat
Definition of the type of matrix used to represent the rotation.
typedef Quaternion(* Interpolator) (Quaternion const &, Quaternion const &, float const)
Function pointer definition for interpolating quaternions.
Public Member Functions
Constructors
Quaternion ()
Create a quaternion whose components are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
Quaternion (T const real, Vec const &imag)
Initialized the quaternion to the given real number part and the imaginary number parts given as imag.
Quaternion (Vec const &axis, double const angle)
Creates a quaternion that matches the rotation represented by the given normalized rotation axis vector and rotation angle in radians.
Quaternion (HMat const &m)
Creates a quaternion that matches the rotation represented by the given homogeneous matrix m, which needs to be orthonormalized.
Element access methods
T * data ()
Returns a pointer to the internal data representation.
T const * data () const
Returns a constant pointer to the internal data representation.
operator T* ()
Casts this quaternion to a pointer of type T.
operator T const * () const
Casts this quaternion to a pointer of type T const.
Magnitude related methods
T length2 () const
Returns the squared Cartesian length of this quaternion.
double length () const
Returns the Cartesian length of this quaternion.
double normalize ()
Normalizes this quaternion so its length equals 1 (if it is not very small).
Angle related methods
T dot (Quaternion const &q) const
Calculates the dot product between this quaternion and quaternion q.
T angleCosine (Quaternion const &q) const
Returns the cosine of the angle between this quaternion and quaternion q, which do not need to be normalized.
double angle (Quaternion const &q) const
Returns the angle between this quaternion and quaternion v, which do not need to be normalized, in radians.
Miscellaneous methods
void setAxisAngle (Vec const &axis, double const angle)
Sets this quaternion to match the rotation represented by the given normalized rotation axis vector and rotation angle in radians.
void getAxisAngle (Vec &axis, double &angle)
Returns a rotation axis vector and rotation angle in radians that match the rotation represented by this quaternion, which needs to be normalized.
void setMatrix (HMat const &m)
Sets this quaternion to match the rotation represented by the given homogeneous matrix m, which needs to be orthonormalized.
void getMatrix (HMat &m) const
Returns a homogeneous matrix m that matches the rotation represented by this quaternion, which needs to be normalized.
Quaternion tangent (Quaternion const &a, Quaternion const &b) const
Returns the tangent for this quaternion given the predecessor a and the successor b, which all need to be normalized.
void conjugate ()
Conjugates this quaternion, i.e. negates its imaginary part.
void invert ()
Inverts this quaternion; the product of a quaternion and its inverse equals the identity quaternion.
Static Public Member Functions
template<typename RT , class RI >
static Quaternion random (RandomBase< RT, RI > &r)
Returns a random normalized quaternion generated by r.
Predefined constants
In order to avoid the so called "static initialization order fiasco", static methods instead of static variables are used here, see http://www.parashift.com/c++-faq-lite/ctors.html#faq-10.14.
static Quaternion const & ZERO ()
Returns a quaternion which has all components set to 0 (which is the identity quaternion regarding addition).
static Quaternion const & IDENTITY ()
Returns a quaternion with the real part set to 1 and the imaginary part set to 0 (which is the identity quaternion regarding multiplication).
Public Attributes
T real
Real number part of the quaternion.
Vec imag
Imaginary number parts of the quaternion.
Friends
Arithmetic quaternion / vector operators
Vec operator* (Quaternion const &q, Vec const &v)
Multiplies quaternion q with vector v.
Element-wise comparison operators
bool operator== (Quaternion const &q, Quaternion const &r)
Returns whether all elements in q equal their counterpart in r with regard to a tolerance depending on the precision of data type T.
bool operator!= (Quaternion const &q, Quaternion const &r)
Returns whether the elements in q are not equal to their counterparts in r with regard to a tolerance depending on the precision of data type T.
Convenience operators for named methods
Quaternion operator~ (Quaternion const &q)
Returns a normalized copy of quaternion q.
T operator% (Quaternion const &q, Quaternion const &r)
Returns the dot product between quaternions q and r.
Quaternion operator! (Quaternion const &q)
Returns the inverse of quaternion q.
Interpolation related methods, see
http://number-none.com/product/Understanding%20Slerp,%20Then%20Not%20Using%20It/
Quaternion lerp (Quaternion const &q, Quaternion const &r, float const s)
This is an alias for nlerp().
Quaternion nlerp (Quaternion const &q, Quaternion const &r, float const s)
Performs a normalized linear interpolation between the quaternions q and r based on a scalar s with the following properties:
Quaternion slerp (Quaternion const &q, Quaternion const &r, float const s)
Performs a spherical-linear interpolation between the quaternions q and r based on a scalar s with the following properties:
Quaternion exp (Quaternion const &q)
Calculates the complex exponential of a quaternion q.
Quaternion log (Quaternion const &q)
Calculates the complex logarithm of a quaternion q.
Quaternion squad (Quaternion const &q, Quaternion const &r, float const s, Quaternion const &a, Quaternion const &b, Interpolator const interpolator=Quaternion::slerp)
Performs a cubic Bezier interpolation between the quaternions q and r based on a scalar s within the quadrilateral defined together with the "tangent" quaternions a and b (the curve touches the midpoint of the "line" from a to b when s = 0.5).
Streaming input / output methods
std::istream & operator>> (std::istream &s, Quaternion &q)
Reads tuple values from an input stream.
std::ostream & operator<< (std::ostream &s, Quaternion const &q)
Writes tuple values to an output stream.
Arithmetic quaternion / quaternion operators
Quaternion const & operator+= (Quaternion const &q)
Increments this quaternion by another quaternion q.
Quaternion const & operator-= (Quaternion const &q)
Decrements this quaternion by another quaternion q.
Quaternion const & operator*= (Quaternion const &q)
Multiplies this quaternion with quaternion q.
Quaternion const & operator/= (Quaternion const &q)
Multiplies this quaternion with the inverse of quaternion q.
Quaternion const & operator+ (Quaternion const &q)
Returns quaternion q unchanged; provided for convenience.
Quaternion operator- (Quaternion const &q)
Returns the negation of quaternion q.
Quaternion operator+ (Quaternion const &q, Quaternion const &r)
Returns the sum of quaternions q and r.
Quaternion operator- (Quaternion const &q, Quaternion const &r)
Returns the difference of quaternions q and r.
Quaternion operator* (Quaternion const &q, Quaternion const &r)
Returns the product of quaternions q and r.
Quaternion operator/ (Quaternion const &q, Quaternion const &r)
Returns the product of quaternion q and the inverse of quaternion r.
Arithmetic quaternion / scalar operators
Quaternion const & operator*= (T const s)
Multiplies this quaternion by a scalar s.
Quaternion const & operator/= (T const s)
Divides this quaternion by a scalar s.
Quaternion operator* (Quaternion const &q, T const s)
Performs scalar multiplication from the right.
Quaternion operator* (T const s, Quaternion const &q)
Performs scalar multiplication from the left.
Quaternion operator/ (Quaternion const &q, T const s)
Performs scalar division from the right.
Quaternion operator/ (T const s, Quaternion const &q)
Performs scalar division from the left.
Detailed Description
template<typename T>
class gale::math::Quaternion< T >
Quaternion implementation based on a scalar for the real number part and a vector for the imaginary number part.
It has common linear algebra and math operations specialized on computer graphics.
OpenGL example usage:
Quatf q(Vec3f::Z(),45.0f*Constf::DEG_TO_RAD());
HMat4f m=q.getMatrix();
glMultMatrixf(m);
Constructor & Destructor Documentation
Quaternion() [1/4]
template<typename T > gale::math::Quaternion< T >::Quaternion () inline
Create a quaternion whose components are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
Quaternion() [2/4]
template<typename T > gale::math::Quaternion< T >::Quaternion (T const real, Vec const & imag) inline
Initialized the quaternion to the given real number part and the imaginary number parts given as imag.
Quaternion() [3/4]
template<typename T > gale::math::Quaternion< T >::Quaternion (Vec const & axis, double const angle) inline
Creates a quaternion that matches the rotation represented by the given normalized rotation axis vector and rotation angle in radians.
References gale::math::Quaternion< T >::setAxisAngle().
Quaternion() [4/4]
template<typename T > gale::math::Quaternion< T >::Quaternion (HMat const & m) inline
Creates a quaternion that matches the rotation represented by the given homogeneous matrix m, which needs to be orthonormalized.
References gale::math::Quaternion< T >::setMatrix().
Member Function Documentation
ZERO()
template<typename T > static Quaternion const& gale::math::Quaternion< T >::ZERO () inline static
Returns a quaternion which has all components set to 0 (which is the identity quaternion regarding addition).
References gale::math::Vector< 3, T >::ZERO().
IDENTITY()
template<typename T > static Quaternion const& gale::math::Quaternion< T >::IDENTITY () inline static
Returns a quaternion with the real part set to 1 and the imaginary part set to 0 (which is the identity quaternion regarding multiplication).
References gale::math::Vector< 3, T >::ZERO().
operator T*()
template<typename T > gale::math::Quaternion< T >::operator T* () inline
Casts this quaternion to a pointer of type T.
As an intended side effect, this also provides indexed data access.
References gale::math::Quaternion< T >::data().
operator T const *()
template<typename T > gale::math::Quaternion< T >::operator T const * () const inline
Casts this quaternion to a pointer of type T const.
As an intended side effect, this also provides indexed data access.
References gale::math::Quaternion< T >::data().
normalize()
template<typename T > double gale::math::Quaternion< T >::normalize () inline
Normalizes this quaternion so its length equals 1 (if it is not very small).
Returns the length before normalization.
References gale::math::Quaternion< T >::length2().
Referenced by gale::math::Quaternion< T >::random().
angleCosine()
template<typename T > T gale::math::Quaternion< T >::angleCosine (Quaternion< T > const & q) const inline
Returns the cosine of the angle between this quaternion and quaternion q, which do not need to be normalized.
Referenced by gale::math::Quaternion< T >::angle().
angle()
template<typename T > double gale::math::Quaternion< T >::angle (Quaternion< T > const & q) const inline
Returns the angle between this quaternion and quaternion v, which do not need to be normalized, in radians.
References gale::math::Quaternion< T >::angleCosine().
Referenced by gale::math::Quaternion< T >::setAxisAngle().
setAxisAngle()
template<typename T > void gale::math::Quaternion< T >::setAxisAngle (Vec const & axis, double const angle) inline
Sets this quaternion to match the rotation represented by the given normalized rotation axis vector and rotation angle in radians.
References gale::math::Quaternion< T >::angle(), gale::math::Quaternion< T >::imag, and gale::math::Quaternion< T >::real.
Referenced by gale::math::Quaternion< T >::Quaternion().
getAxisAngle()
template<typename T > void gale::math::Quaternion< T >::getAxisAngle (Vec & axis, double & angle) inline
Returns a rotation axis vector and rotation angle in radians that match the rotation represented by this quaternion, which needs to be normalized.
References gale::math::Quaternion< T >::dot(), gale::math::Quaternion< T >::imag, gale::math::Vector< N, T >::length2(), gale::math::Quaternion< T >::real, and gale::math::Vector< 3, T >::X().
setMatrix()
template<typename T > void gale::math::Quaternion< T >::setMatrix (HMat const & m) inline
Sets this quaternion to match the rotation represented by the given homogeneous matrix m, which needs to be orthonormalized.
References gale::math::Quaternion< T >::imag, gale::math::mod3(), and gale::math::Quaternion< T >::real.
Referenced by gale::math::Quaternion< T >::Quaternion().
getMatrix()
template<typename T > void gale::math::Quaternion< T >::getMatrix (HMat & m) const inline
Returns a homogeneous matrix m that matches the rotation represented by this quaternion, which needs to be normalized.
References gale::math::HMatrix4< T >::c0, gale::math::HMatrix4< T >::c1, gale::math::HMatrix4< T >::c2, gale::math::HMatrix4< T >::c3, gale::math::Vector< N, T >::getX(), gale::math::Vector< N, T >::getY(), gale::math::Vector< N, T >::getZ(), gale::math::Quaternion< T >::imag, gale::math::Quaternion< T >::real, and gale::math::Vector< 3, T >::ZERO().
tangent()
template<typename T > Quaternion gale::math::Quaternion< T >::tangent (Quaternion< T > const & a, Quaternion< T > const & b) const inline
Returns the tangent for this quaternion given the predecessor a and the successor b, which all need to be normalized.
References gale::math::Quaternion< T >::conjugate(), gale::math::Quaternion< T >::exp, and gale::math::Quaternion< T >::log.
invert()
template<typename T > void gale::math::Quaternion< T >::invert () inline
Inverts this quaternion; the product of a quaternion and its inverse equals the identity quaternion.
References gale::math::Quaternion< T >::conjugate(), and gale::math::Quaternion< T >::length2().
Friends And Related Function Documentation
operator*
template<typename T > Vec operator* (Quaternion< T > const & q, Vec const & v) friend
Multiplies quaternion q with vector v.
If the quaternion is normalized, this results in a rotation of v about q.
operator==
template<typename T > bool operator== (Quaternion< T > const & q, Quaternion< T > const & r) friend
Returns whether all elements in q equal their counterpart in r with regard to a tolerance depending on the precision of data type T.
operator!=
template<typename T > bool operator!= (Quaternion< T > const & q, Quaternion< T > const & r) friend
Returns whether the elements in q are not equal to their counterparts in r with regard to a tolerance depending on the precision of data type T.
nlerp
template<typename T > Quaternion nlerp (Quaternion< T > const & q, Quaternion< T > const & r, float const s) friend
Performs a normalized linear interpolation between the quaternions q and r based on a scalar s with the following properties:
The operation is commutative,
the rotation does not have constant speed,
the interpolation is torque-minimal. For performance reasons, s is not clamped to [0,1].
slerp
template<typename T > Quaternion slerp (Quaternion< T > const & q, Quaternion< T > const & r, float const s) friend
Performs a spherical-linear interpolation between the quaternions q and r based on a scalar s with the following properties:
The operation is not commutative,
the rotation has constant speed (tangential acceleration is zero),
the interpolation is torque-minimal. For performance reasons, s is not clamped to [0,1].
squad
template<typename T > Quaternion squad (Quaternion< T > const & q, Quaternion< T > const & r, float const s, Quaternion< T > const & a, Quaternion< T > const & b, Interpolator const interpolator = Quaternion< T >::slerp) friend
Performs a cubic Bezier interpolation between the quaternions q and r based on a scalar s within the quadrilateral defined together with the "tangent" quaternions a and b (the curve touches the midpoint of the "line" from a to b when s = 0.5).
Optionally, an interpolator may be specified. For performance reasons, s is not clamped to [0,1].
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/quaternion.h (Last modified in 6bdf1c2)