GALE: gale::wrapgl::MinimalWindow Class Reference
gale::wrapgl::MinimalWindow Class Reference
This class creates minimal window suitable for OpenGL rendering.
#include <minimalwindow.h>
Public Member Functions
MinimalWindow (LPCTSTR title, int width, int height, global::AttributeListi const *const context_attr=NULL, global::AttributeListi const *const pixel_attr=NULL, int const samples=8)
Creates a window with the specified title, a client size of the given width and height, an OpenGL context with the attributes in context_attr attached to it and a pixel format that matches pixel_attr.
double getTimeout () const
Returns the currently set timeout value in seconds.
void setTimeout (double const timeout)
Sets the current timeout value in seconds.
void processEvents ()
Starts the event processing and does not return until the window gets closed.
void repaint ()
Invalidates the whole window and requests to repaint its contents.
virtual bool onIdle ()
Event handler that gets called when there are no messages to process.
virtual void onTimeout ()
Event handler that gets called when the timeout value has been reached.
virtual void onResize (int width, int height)
Event handler that gets called after a window has changed its size.
virtual void onPaint ()
Event handler that gets called when a window portion should be painted.
virtual void onClose ()
Event handler that gets called when a window should terminate.
Public Member Functions inherited from gale::wrapgl::RenderSurface
RenderSurface (global::AttributeListi const *const context_attr=NULL, global::AttributeListi const *const pixel_attr=NULL, int const samples=8)
Creates a minimal render surface and current render context with the attributes in context_attr.
~RenderSurface ()
Destroys render surface.
WindowHandle const & windowHandle () const
Returns the handle to the window associated with this render surface.
ContextHandle const & contextHandle () const
Returns the handle to the OpenGL context associated with this render surface.
bool makeCurrent ()
Makes this the active OpenGL context for the current thread.
Dimensions dimensions () const
Returns the width and height of this render surface.
Protected Member Functions
LRESULT handleMessage (UINT const uMsg, WPARAM const wParam, LPARAM const lParam)
Handles window messages and forwards them to the event methods.
Protected Member Functions inherited from gale::wrapgl::RenderSurface
bool createDeviceContext (int pixel_format=0)
Creates a minimal device context and associated window with either a default or the specified pixel_format.
void destroyDeviceContext ()
Releases the device context and destroys the associated window.
void destroyRenderContext ()
Deletes the render context only.
Protected Attributes
bool m_close_requested
Indicates whether the window should be closed.
double m_timeout
Timeout event value in seconds.
system::Timer m_timer
Timer to trigger the timeout event.
Protected Attributes inherited from gale::wrapgl::RenderSurface
WindowHandle m_window
Handle to the window owning the OpenGL context.
ContextHandle m_context
Handle to the OpenGL context.
Additional Inherited Members
Public Types inherited from gale::wrapgl::RenderSurface
typedef HWND WindowHandle
Type definition for a window handle the render surface belongs to.
Static Public Member Functions inherited from gale::wrapgl::RenderSurface
static ContextHandle getCurrent ()
Returns the active OpenGL context for the current thread.
static bool setCurrent (ContextHandle const &handle)
Sets the active OpenGL context for the current thread.
Static Public Attributes inherited from gale::wrapgl::RenderSurface
static int const DEFAULT_COLOR_BITS = 24
The color bits to use if not further specified.
static int const DEFAULT_DEPTH_BITS = 24
The depth bits to use if not further specified.
static int const DEFAULT_STENCIL_BITS = 8
The stencil bits to use if not further specified.
Static Protected Attributes inherited from gale::wrapgl::RenderSurface
static PIXELFORMATDESCRIPTOR const s_pfd
Pixel format description for the default format.
Detailed Description
This class creates minimal window suitable for OpenGL rendering.
Constructor & Destructor Documentation
MinimalWindow()
gale::wrapgl::MinimalWindow::MinimalWindow (LPCTSTR title, int width, int height, global::AttributeListi const *const context_attr = NULL, global::AttributeListi const *const pixel_attr = NULL, int const samples = 8)
Creates a window with the specified title, a client size of the given width and height, an OpenGL context with the attributes in context_attr attached to it and a pixel format that matches pixel_attr.
The window will be hidden initially, but it will become the current render context.
References G_ASSERT_CALL, and gale::wrapgl::RenderSurface::windowHandle().
Member Function Documentation
setTimeout()
void gale::wrapgl::MinimalWindow::setTimeout (double const timeout) inline
Sets the current timeout value in seconds.
Any non-positive value (which includes 0) disables the timeout handler.
References m_timeout, and processEvents().
processEvents()
void gale::wrapgl::MinimalWindow::processEvents ()
Starts the event processing and does not return until the window gets closed.
Event handlers are called accordingly.
References gale::system::Timer::elapsed(), m_close_requested, m_timeout, m_timer, gale::wrapgl::RenderSurface::m_window, onIdle(), onTimeout(), repaint(), and gale::system::Timer::reset().
Referenced by setTimeout().
onIdle()
virtual bool gale::wrapgl::MinimalWindow::onIdle () inline virtual
Event handler that gets called when there are no messages to process.
When it returns true a repaint will be triggered, on false the thread's remaining time slice will be relinquished.
Referenced by processEvents().
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/minimalwindow.h (Last modified in a6c7904)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/minimalwindow.cpp (Last modified in 5275de5)