GALE: gale::math::Vector< N, T > Class Template Reference
gale::math::Vector< N, T > Class Template Reference
Vector class implementation based on a tuple, featuring common linear algebra and math operations specialized on computer graphics.
#include <vector.h>
Public Types
typedef T Type
The data type of this template instance.
Public Member Functions
Component access methods
T getX ()
Returns the x-component.
T const & getX () const
Returns a constant reference to the x-component.
void setX (T const &x)
Assigns a new value to the x-component.
T getY ()
Returns the y-component.
T const & getY () const
Returns a constant reference to the y-component.
void setY (T const &y)
Assigns a new value to the y-component.
T getZ ()
Returns the z-component.
T const & getZ () const
Returns a constant reference to the z-component.
void setZ (T const &z)
Assigns a new value to the z-component.
T getW ()
Returns the w-component.
T const & getW () const
Returns a constant reference to the w-component.
void setW (T const &w)
Assigns a new value to the w-component.
Magnitude related methods
T length2 () const
Returns the squared Cartesian length of this vector.
double length () const
Returns the Cartesian length of this vector.
double normalize ()
Normalizes this vector so its length equals 1 (if it is not very small).
bool equals (Vector const &v, T const t=T(1e-6))
Returns whether all elements equal their counterpart in v with regard to the tolerance t.
Angle related methods
T dot (Vector const &v) const
Returns the dot product between vectors v and w.
T angleCosine (Vector const &v) const
Returns the cosine of the angle between this vector and vector v.
double angle (Vector const &v) const
Returns the smallest angle between this vector and vector v in radians.
double orientedAngle (Vector const &v, Vector const &r) const
Returns the oriented angle between this vector and vector v in radians.
Vector orthoProjection (Vector const &v) const
Returns the orthogonal projection of this vector onto the vector v.
void crossWith (Vector const &v)
Calculates the cross product between this vector and vector v.
Vector orthoVector () const
Returns an arbitrary vector which is orthogonal to this vector.
bool isCollinear (Vector const &v) const
Returns whether this vector is collinear to vector v.
Public Member Functions inherited from gale::math::TupleBase< N, T, Vector< N, T > >
TupleBase ()
Create a tuple whose elements are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
TupleBase (T const e0, T const e1)
Allows to initialize 2-tuples directly.
TupleBase (T const e0, T const e1, T const e2)
Allows to initialize 3-tuples directly.
TupleBase (T const e0, T const e1, T const e2, T const e3)
Allows to initialize 4-tuples directly.
T * data ()
Returns a pointer to the internal data array.
T const * data () const
Returns a constant pointer to the internal data array.
operator T* ()
Casts this tuple to a pointer of type T.
operator T const * () const
Casts this tuple to a pointer of type T const.
void set (T const e0, T const e1)
Assigns new values to the first two tuple elements.
void set (T const e0, T const e1, T const e2)
Assigns new values to the first three tuple elements.
void set (T const e0, T const e1, T const e2, T const e3)
Assigns new values to the first four tuple elements.
T minElement () const
Determines the minimum element of this tuple.
T maxElement () const
Determines the maximum element of this tuple.
T absMinElement () const
Determines the absolute minimum element of this tuple.
T absMaxElement () const
Determines the absolute maximum element of this tuple.
Vector< N, T > minElements (Vector< N, T > const &t) const
Calculates the element-wise minimum of this tuple and tuple t.
Vector< N, T > maxElements (Vector< N, T > const &t) const
Calculates the element-wise maximum of this tuple and tuple t.
Vector< N, T > const & operator+= (Vector< N, T > const &t)
Element-wise increments this tuple by tuple t.
Vector< N, T > const & operator-= (Vector< N, T > const &t)
Element-wise decrements this tuple by tuple t.
Vector< N, T > const & operator*= (Vector< N, T > const &t)
Element-wise multiplies this tuple by tuple t.
Vector< N, T > const & operator/= (Vector< N, T > const &t)
Element-wise divides this tuple by tuple t.
Vector< N, T > const & operator*= (T const s)
Multiplies each element of this tuple by a scalar s.
Vector< N, T > const & operator/= (T const s)
Divides each element of this tuple by a scalar s.
Static Public Member Functions
template<typename RT , class RI >
static Vector random (RandomBase< RT, RI > &r)
Returns a random normalized vector generated by r.
Predefined constants
In order to avoid the so called "static initialization order fiasco", static methods instead of static variables are used here, see http://www.parashift.com/c++-faq-lite/ctors.html#faq-10.14.
static Vector const & ZERO ()
Returns a vector which has all components set to 0.
static Vector const & X ()
Returns a vector which has the x-component set to 1, all others to 0.
static Vector const & Y ()
Returns a vector which has the y-component set to 1, all others to 0.
static Vector const & Z ()
Returns a vector which has the z-component set to 1, all others to 0.
static Vector const & W ()
Returns a vector which has the w-component set to 1, all others to 0.
Static Public Attributes
static int const Components =N
The number of components of this template instance.
Private Types
typedef TupleBase< N, T, Vector< N, T > > Base
This type definition simplifies base class access to identifiers that are not visible until instantiation time because they do not dependent on template arguments.
Friends
Convenience operators for named methods
Vector operator~ (Vector const &v)
Returns a normalized copy of vector v.
T operator% (Vector const &v, Vector const &w)
Returns the dot product between vectors v and w.
Vector operator^ (Vector const &v, Vector const &w)
Returns the cross product between vectors v and w.
Friends inherited from gale::math::TupleBase< N, T, Vector< N, T > >
Constructors
Vector (unsigned int const mask)
Sets each component in the vector to either 0 or 1 depending on the bits set in mask.
Vector ()
Create a vector whose components are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
Vector (T const x, T const y)
Allows to initialize 2-vectors directly.
Vector (T const x, T const y, T const z)
Allows to initialize 3-vectors directly.
Vector (T const x, T const y, T const z, T const w)
Allows to initialize 4-vectors directly.
template<typename U >
Vector (Vector< N, U > const &v)
Converts a vector of different type but with the same amount of components to this type.
Additional Inherited Members
Protected Attributes inherited from gale::math::TupleBase< N, T, Vector< N, T > >
T m_data [N]
Tightly packed array of N elements of type T.
Detailed Description
template<unsigned int N, typename T>
class gale::math::Vector< N, T >
Vector class implementation based on a tuple, featuring common linear algebra and math operations specialized on computer graphics.
OpenGL example usage:
glBegin(GL_LINE_LOOP);
    glVertex3fv(Vec3f::X());
    glVertex3fv(Vec3f::Y());
    glVertex3fv(Vec3f::Z());
glEnd();
Member Typedef Documentation
Base
template<unsigned int N, typename T> typedef TupleBase<N,T,Vector<N,T> > gale::math::Vector< N, T >::Base private
This type definition simplifies base class access to identifiers that are not visible until instantiation time because they do not dependent on template arguments.
Constructor & Destructor Documentation
Vector() [1/3]
template<unsigned int N, typename T> gale::math::Vector< N, T >::Vector (unsigned int const mask) inline explicit protected
Sets each component in the vector to either 0 or 1 depending on the bits set in mask.
Bit 0 maps to the first component, bit 1 to second one and so on. This constructor is required to initialize the static class constants.
Vector() [2/3]
template<unsigned int N, typename T> gale::math::Vector< N, T >::Vector () inline
Create a vector whose components are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
Vector() [3/3]
template<unsigned int N, typename T> template<typename U > gale::math::Vector< N, T >::Vector (Vector< N, U > const & v) inline
Converts a vector of different type but with the same amount of components to this type.
Member Function Documentation
normalize()
template<unsigned int N, typename T> double gale::math::Vector< N, T >::normalize () inline
Normalizes this vector so its length equals 1 (if it is not very small).
Returns the length before normalization.
Referenced by gale::wrapgl::PreparedMesh::compile(), gale::math::HMatrix4< T >::orthonormalize(), and gale::math::Vector< 3, T >::random().
equals()
template<unsigned int N, typename T> bool gale::math::Vector< N, T >::equals (Vector< N, T > const & v, T const t = T(1e-6)) inline
Returns whether all elements equal their counterpart in v with regard to the tolerance t.
orientedAngle()
template<unsigned int N, typename T> double gale::math::Vector< N, T >::orientedAngle (Vector< N, T > const & v, Vector< N, T > const & r) const inline
Returns the oriented angle between this vector and vector v in radians.
The angle is measured in positive rotation direction around the reference vector r.
Referenced by gale::model::Mesh::Factory::populateNeighborhood().
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/vector.h (Last modified in 5275de5)