GALE: gale::model::Mesh::Subdivider Class Reference
gale::model::Mesh::Subdivider Class Reference
Class to subdivide meshes using different algorithms, for an overview see http://en.wikipedia.org/wiki/Subdivision_surface.
#include <mesh.h>
Public Types
typedef void(* Scheme)(Mesh &mesh, int steps)
Function pointer type definition for subdivision schemes that perform the given number of subdivision steps on mesh.
Static Public Member Functions
Interpolating schemes
This type of subdivision does not modify the vertices of the base mesh.
Newly generated vertices are interpolated on the limit surface.
static void Polyhedral (Mesh &mesh, int steps, float const scale)
Divides the triangular faces of a mesh into further triangles.
static void Polyhedral (Mesh &mesh, int const steps=1)
Convenience wrapper for use with a function pointer that calls Polyhedral() with scale set to 0.
static void Butterfly (Mesh &mesh, int steps=1)
Divides the triangular faces of a mesh as described by Dyn et al.
Approximating schemes
This type of subdivision modifies both the vertices of the base mesh and newly generated vertices to approximate the limit surface.
static void Loop (Mesh &mesh, int steps, bool const move)
Divides the triangular faces of a mesh as described by C.
static void Loop (Mesh &mesh, int const steps=1)
Convenience wrapper for use with a function pointer that calls Loop() with move set to true.
static void Sqrt3 (Mesh &mesh, int steps, bool const move)
Divides the triangular faces of a mesh as described by L.
static void Sqrt3 (Mesh &mesh, int const steps=1)
Convenience wrapper for use with a function pointer that calls Sqrt3() with move set to true.
static void CatmullClark (Mesh &mesh, int steps=1)
Divides the quadrangular faces of a mesh as described by E.
static void DooSabin (Mesh &mesh, int steps=1)
Divides the faces of a mesh as described by D.
Static Private Member Functions
static void assignNeighbors (Mesh const &orig, Mesh &mesh, int const x0i)
Adds the missing neighbors of newly inserted vertices after a subdivision step.
Detailed Description
Class to subdivide meshes using different algorithms, for an overview see http://en.wikipedia.org/wiki/Subdivision_surface.
Member Typedef Documentation
typedef void(* gale::model::Mesh::Subdivider::Scheme)(Mesh &mesh, int steps)
Function pointer type definition for subdivision schemes that perform the given number of subdivision steps on mesh.
Member Function Documentation
void gale::model::Mesh::Subdivider::Polyhedral (Mesh & mesh, int steps, float const scale) static
Divides the triangular faces of a mesh into further triangles.
If scale is non-zero, the new vertices are scaled to have that length.
References gale::global::DynamicArray< T >::getSize(), gale::model::Mesh::insert(), gale::model::Mesh::neighbors, and gale::model::Mesh::vertices.
Referenced by Polyhedral().
static void gale::model::Mesh::Subdivider::Polyhedral (Mesh & mesh, int const steps = 1) inline static
Convenience wrapper for use with a function pointer that calls Polyhedral() with scale set to 0.
References Polyhedral().
void gale::model::Mesh::Subdivider::Butterfly (Mesh & mesh, int steps = 1) static
Divides the triangular faces of a mesh as described by Dyn et al.
in http://www.math.tau.ac.il/~niradyn/papers/butterfly.pdf.
References gale::global::DynamicArray< T >::getSize(), gale::model::Mesh::insert(), gale::model::Mesh::neighbors, gale::model::Mesh::nextTo(), gale::model::Mesh::prevTo(), and gale::model::Mesh::vertices.
void gale::model::Mesh::Subdivider::Loop (Mesh & mesh, int steps, bool const move) static
Divides the triangular faces of a mesh as described by C.
T. Loop in http://research.microsoft.com/~cloop/thesis.pdf.
References gale::global::DynamicArray< T >::getSize(), gale::model::Mesh::insert(), gale::math::lerp(), gale::model::Mesh::neighbors, gale::model::Mesh::nextTo(), gale::math::Constants< T >::PI(), gale::model::Mesh::prevTo(), gale::model::Mesh::vertices, and gale::math::Vector< N, T >::ZERO().
Referenced by Loop().
static void gale::model::Mesh::Subdivider::Loop (Mesh & mesh, int const steps = 1) inline static
Convenience wrapper for use with a function pointer that calls Loop() with move set to true.
References Loop().
void gale::model::Mesh::Subdivider::Sqrt3 (Mesh & mesh, int steps, bool const move) static
Divides the triangular faces of a mesh as described by L.
Kobbelt in http://www.graphics.rwth-aachen.de/uploads/media/sqrt3.pdf.
References gale::model::Mesh::erase(), gale::global::DynamicArray< T >::getSize(), gale::global::DynamicArray< T >::insert(), gale::model::Mesh::neighbors, gale::model::Mesh::nextTo(), gale::math::Constants< T >::PI(), gale::model::Mesh::prevTo(), gale::model::Mesh::splice(), and gale::model::Mesh::vertices.
Referenced by Sqrt3().
static void gale::model::Mesh::Subdivider::Sqrt3 (Mesh & mesh, int const steps = 1) inline static
Convenience wrapper for use with a function pointer that calls Sqrt3() with move set to true.
References Sqrt3().
void gale::model::Mesh::Subdivider::CatmullClark (Mesh & mesh, int steps = 1) static
Divides the quadrangular faces of a mesh as described by E.
Catmull and J. Clark in http://www.cs.berkeley.edu/~sequin/CS284/PAPERS/CatmullClark_SDSurf.pdf.
References gale::global::DynamicArray< T >::getSize(), gale::global::DynamicArray< T >::insert(), gale::model::Mesh::insert(), gale::model::Mesh::neighbors, gale::model::Mesh::nextTo(), gale::model::Mesh::prevTo(), gale::model::Mesh::splice(), and gale::model::Mesh::vertices.
void gale::model::Mesh::Subdivider::DooSabin (Mesh & mesh, int steps = 1) static
Divides the faces of a mesh as described by D.
Doo and M. Sabin in http://trac2.assembla.com/DooSabinSurfaces/export/12/trunk/docs/Doo%201978%20Subdivision%20algorithm.pdf.
References gale::global::DynamicArray< T >::getSize(), gale::global::DynamicArray< T >::insert(), gale::model::Mesh::neighbors, gale::model::Mesh::nextTo(), gale::model::Mesh::orbit(), gale::math::Constants< T >::PI(), gale::model::Mesh::prevTo(), gale::global::DynamicArray< T >::remove(), gale::model::Mesh::splice(), and gale::model::Mesh::vertices.
void gale::model::Mesh::Subdivider::assignNeighbors (Mesh const & orig, Mesh & mesh, int const x0i) static private
Adds the missing neighbors of newly inserted vertices after a subdivision step.
Starting from vertex index x0i, neighbors missing in the original mesh orig are inserted into the given mesh, which usually is a copy of orig.
References gale::global::DynamicArray< T >::getSize(), gale::global::DynamicArray< T >::insert(), gale::model::Mesh::neighbors, gale::model::Mesh::nextTo(), gale::model::Mesh::prevTo(), gale::global::DynamicArray< T >::setCapacity(), and gale::model::Mesh::vertices.
The documentation for this class was generated from the following files:
include/gale/model/mesh.h (Last modified in b7b3e5b)
source/mesh_subdivider.cpp (Last modified in b7b3e5b)
Donations are appreciated via
GALE is generously hosted by