GALE: gale::wrapgl::Logo Class Reference
gale::wrapgl::Logo Class Reference
A class to draw a logo into the current viewport.
#include <helpers.h>
Public Types
enum Corner { CORNER_LL, CORNER_LR, CORNER_UR, CORNER_UL }
Identifiers for the corner to draw the logo into.
Public Member Functions
Logo (double const fov=90 *math::Constd::DEG_TO_RAD(), float const distance=3.0f)
Prepares to draw a logo with the given camera fov and distance.
~Logo ()
Frees the logo's render resources.
void draw (Corner corner=CORNER_LL)
Draws a logo into the specified viewport corner, similar to a TV overlay logo.
Private Types
enum List { LIST_PROLOGUE, LIST_EPILOGUE, LIST_FRAME, LIST_COUNT }
Identifiers for the display lists.
Private Attributes
Camera m_camera
The logo's camera.
GLuint m_list_range
Start number of the range of display list IDs.
PreparedMesh m_cube_prep
The cube mesh prepared for rendering.
Detailed Description
A class to draw a logo into the current viewport.
Member Enumeration Documentation
Corner
enum gale::wrapgl::Logo::Corner
Identifiers for the corner to draw the logo into.
Enumerator
CORNER_LL
Lower Left.
CORNER_LR
Lower Right.
CORNER_UR
Upper Right.
CORNER_UL
Upper Left.
List
enum gale::wrapgl::Logo::List private
Identifiers for the display lists.
Enumerator
LIST_PROLOGUE
Prologue display list (use before rendering).
LIST_EPILOGUE
Epilogue display list (use after rendering).
LIST_FRAME
Display list to draw the logo's frame.
LIST_COUNT
Special entry to name the number of enum entries.
Member Function Documentation
draw()
void gale::wrapgl::Logo::draw (Corner corner = CORNER_LL)
Draws a logo into the specified viewport corner, similar to a TV overlay logo.
References gale::wrapgl::Camera::apply(), CORNER_LR, CORNER_UL, CORNER_UR, gale::wrapgl::Renderer::draw(), G_ASSERT_OPENGL, gale::wrapgl::Camera::getFarClipping(), gale::wrapgl::Camera::getFOV(), gale::wrapgl::Camera::getNearClipping(), LIST_EPILOGUE, LIST_FRAME, LIST_PROLOGUE, m_camera, m_cube_prep, m_list_range, gale::math::min(), gale::wrapgl::Camera::setProjection(), gale::wrapgl::Camera::setScreenSpaceDimensions(), and gale::wrapgl::Camera::setScreenSpaceOrigin().
Referenced by gale::wrapgl::DefaultWindow::onPaint().
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/helpers.h (Last modified in a6c7904)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/helpers.cpp (Last modified in a6c7904)