GALE: gale::math::Matrix4< T > Class Template Reference
gale::math::Matrix4< T > Class Template Reference
Matrix class implementation based on column vectors.
#include <matrix4.h>
Classes
struct Factory
Factory methods to easily create commonly used matrices.
Public Types
typedef T Type
Definition for external access to the data type.
typedef Vector< 4, T > Vec
Definition of the type of vector used as the columns for the matrix.
Public Member Functions
Constructors
Matrix4 ()
Create a matrix whose components are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
Matrix4 (Vec const &c0, Vec const &c1, Vec const &c2, Vec const &c3)
Initialize the column vectors with vectors c0 to c3.
Matrix4 (Vec const &c, Vec const &r)
Creates a matrix from multiplying column vector c with row vector r.
Element access methods
T * data ()
Returns a pointer to the matrix data in memory.
T const * data () const
Returns a constant pointer to the matrix data in memory.
operator T* ()
Casts this matrix to a pointer of type T.
operator T const * () const
Casts this matrix to a pointer of type T const.
T & operator() (unsigned int const row, unsigned int const column)
Returns a reference to the data element located at row and column.
T const & operator() (unsigned int const row, unsigned int const column) const
Returns a constant reference to the data element located at row and column.
Arithmetic matrix / vector operators
Vec mulMatVec (Vec const &v) const
Multiplies this matrix from the left to column vector v (resulting in a column vector).
Vec mulVecMat (Vec const &v) const
Multiplies this matrix from the right to row vector v (resulting in a row vector).
Vector< 3, T > mulMatVec (Vector< 3, T > const &v) const
Multiplies this matrix from the left to column vector v (resulting in a column vector) using homogeneous coordinates.
Vector< 3, T > mulVecMat (Vector< 3, T > const &v) const
Multiplies this matrix from the right to row vector v (resulting in a row vector) using homogeneous coordinates.
Miscellaneous methods
T determinant () const
Returns the determinant of this matrix.
Matrix4 adjoint () const
Returns the adjoint of this matrix.
void invert (bool *const result=NULL)
Inverts this matrix.
Static Public Member Functions
template<typename RT , class RI >
static Matrix4 random (RandomBase< RT, RI > &r)
Returns a random invertible 4x4 matrix generated by r.
Predefined constants
In order to avoid the so called "static initialization order fiasco", static methods instead of static variables are used here, see http://www.parashift.com/c++-faq-lite/ctors.html#faq-10.14.
static Matrix4 const & ZERO ()
Returns a matrix which has all components set to 0.
static Matrix4 const & IDENTITY ()
Returns the identity matrix (regarding multiplication).
Public Attributes
Vec c0
The first column vector.
Vec c1
The second column vector.
Vec c2
The third column vector.
Vec c3
The fourth column vector.
Private Member Functions
void interim (T(&a)[6], T(&b)[6]) const
Calculates interim results for determinant() and adjoint().
T determinant (T const a[6], T const b[6]) const
Returns the determinant based on the interim values in a and b.
Matrix4 adjoint (T const a[6], T const b[6]) const
Returns the adjoint based on the interim values in a and b.
Friends
Comparison operators
bool operator== (Matrix4 const &m, Matrix4 const &n)
Returns whether all elements in m equal their counterpart in n with regard to a tolerance depending on the precision of data type T.
bool operator!= (Matrix4 const &m, Matrix4 const &n)
Returns whether the elements in m are not equal to their counterparts in n with regard to a tolerance depending on the precision of data type T.
Convenience operators for named methods
Vec operator* (Matrix4 const &m, Vec const &v)
Multiplies matrix m from the left to column vector v (resulting in a column vector).
Vector< 3, T > operator* (Matrix4 const &m, Vector< 3, T > const &v)
Multiplies matrix m from the left to column vector v (resulting in a column vector) using homogeneous coordinates.
Matrix4 operator! (Matrix4 const &m)
Returns the inverse of matrix m.
Streaming input / output methods
std::istream & operator>> (std::istream &s, Matrix4 &m)
Reads a matrix from an input stream.
std::ostream & operator<< (std::ostream &s, Matrix4 const &m)
Writes a matrix to an output stream.
Arithmetic matrix / matrix operators
Matrix4 const & operator+= (Matrix4 const &m)
Element-wise increments this matrix by matrix m.
Matrix4 const & operator-= (Matrix4 const &m)
Element-wise decrements this matrix by matrix m.
Matrix4 const & operator*= (Matrix4 const &m)
Multiplies this matrix by matrix m from the right.
Matrix4 const & operator+ (Matrix4 const &m)
Returns matrix m unchanged; provided for convenience.
Matrix4 operator- (Matrix4 const &m)
Returns the element-wise negation of matrix m.
Matrix4 operator+ (Matrix4 const &m, Matrix4 const &n)
Returns the element-wise sum of matrices m and n.
Matrix4 operator- (Matrix4 const &m, Matrix4 const &n)
Returns the element-wise difference of matrices m and n.
Matrix4 operator* (Matrix4 const &m, Matrix4 const &n)
Returns matrix m multiplied by matrix n from the right.
Arithmetic matrix / scalar operators
Matrix4 const & operator*= (T const s)
Multiplies each element of this matrix by a scalar s.
Matrix4 const & operator/= (T const s)
Divides each element of this matrix by a scalar s.
Matrix4 operator* (Matrix4 const &m, T const s)
Multiplies each element of matrix m by a scalar s from the right.
Matrix4 operator* (T const s, Matrix4 const &m)
Multiplies each element of matrix m by a scalar s from the left.
Matrix4 operator/ (Matrix4 const &m, T const s)
Divides each element of matrix m by a scalar s.
Matrix4 operator/ (T const s, Matrix4 const &m)
Divides a scalar s by each element of matrix m.
Detailed Description
template<typename T>
class gale::math::Matrix4< T >
Matrix class implementation based on column vectors.
The matrix is stored as 4x4 numbers organized in column-major order in memory as required by OpenGL, i.e. the matrix entry at row r, 0 <= r <= 3, and column c, 0 <= c <= 3, is located at offset i = c*4 + r. For a nice article about column vs. row vectors see http://fgiesen.wordpress.com/2011/05/04/row-major-vs-column-major-and-gl-es/.
OpenGL example usage:
Mat4d m;
// ...
glMatrixMode(GL_PROJECTION);
glLoadMatrixd(m);
Constructor & Destructor Documentation
Matrix4()
template<typename T > gale::math::Matrix4< T >::Matrix4 () inline
Create a matrix whose components are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
Referenced by gale::math::Matrix4< T >::adjoint(), gale::math::Matrix4< T >::Factory::OrthographicProjection(), and gale::math::Matrix4< T >::Factory::PerspectiveProjection().
Member Function Documentation
operator T*()
template<typename T > gale::math::Matrix4< T >::operator T* () inline
Casts this matrix to a pointer of type T.
As an intended side effect, this also provides indexed data access.
References gale::math::Matrix4< T >::data().
operator T const *()
template<typename T > gale::math::Matrix4< T >::operator T const * () const inline
Casts this matrix to a pointer of type T const.
As an intended side effect, this also provides indexed data access.
References gale::math::Matrix4< T >::data().
operator()() [1/2]
template<typename T > T& gale::math::Matrix4< T >::operator() (unsigned int const row, unsigned int const column) inline
Returns a reference to the data element located at row and column.
Despite usual in maths, the index starts at 0 (not 1).
References G_ASSERT.
operator()() [2/2]
template<typename T > T const& gale::math::Matrix4< T >::operator() (unsigned int const row, unsigned int const column) const inline
Returns a constant reference to the data element located at row and column.
Despite usual in maths, the index starts at 0 (not 1).
References G_ASSERT.
mulMatVec() [1/2]
template<typename T > Vec gale::math::Matrix4< T >::mulMatVec (Vec const & v) const inline
Multiplies this matrix from the left to column vector v (resulting in a column vector).
References gale::math::Matrix4< T >::c0, gale::math::Matrix4< T >::c1, gale::math::Matrix4< T >::c2, and gale::math::Matrix4< T >::c3.
mulVecMat() [1/2]
template<typename T > Vec gale::math::Matrix4< T >::mulVecMat (Vec const & v) const inline
Multiplies this matrix from the right to row vector v (resulting in a row vector).
References gale::math::Matrix4< T >::c0, gale::math::Matrix4< T >::c1, gale::math::Matrix4< T >::c2, and gale::math::Matrix4< T >::c3.
mulMatVec() [2/2]
template<typename T > Vector<3,T> gale::math::Matrix4< T >::mulMatVec (Vector< 3, T > const & v) const inline
Multiplies this matrix from the left to column vector v (resulting in a column vector) using homogeneous coordinates.
References gale::math::Matrix4< T >::c0, gale::math::Matrix4< T >::c1, gale::math::Matrix4< T >::c2, and gale::math::Matrix4< T >::c3.
mulVecMat() [2/2]
template<typename T > Vector<3,T> gale::math::Matrix4< T >::mulVecMat (Vector< 3, T > const & v) const inline
Multiplies this matrix from the right to row vector v (resulting in a row vector) using homogeneous coordinates.
References gale::math::Matrix4< T >::c0, gale::math::Matrix4< T >::c1, gale::math::Matrix4< T >::c2, and gale::math::Matrix4< T >::c3.
invert()
template<typename T > void gale::math::Matrix4< T >::invert (bool *const result = NULL) inline
Inverts this matrix.
Optionally returns a result indicating whether the matrix' determinant is non-zero and thus the inverse exists.
References abs(), gale::math::Matrix4< T >::adjoint(), gale::math::Matrix4< T >::determinant(), gale::math::Matrix4< T >::interim(), and gale::math::Numerics< T >::ZERO_TOLERANCE().
Friends And Related Function Documentation
operator==
template<typename T > bool operator== (Matrix4< T > const & m, Matrix4< T > const & n) friend
Returns whether all elements in m equal their counterpart in n with regard to a tolerance depending on the precision of data type T.
operator!=
template<typename T > bool operator!= (Matrix4< T > const & m, Matrix4< T > const & n) friend
Returns whether the elements in m are not equal to their counterparts in n with regard to a tolerance depending on the precision of data type T.
operator* [1/2]
template<typename T > Vec operator* (Matrix4< T > const & m, Vec const & v) friend
Multiplies matrix m from the left to column vector v (resulting in a column vector).
operator* [2/2]
template<typename T > Vector<3,T> operator* (Matrix4< T > const & m, Vector< 3, T > const & v) friend
Multiplies matrix m from the left to column vector v (resulting in a column vector) using homogeneous coordinates.
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/matrix4.h (Last modified in 5275de5)