GALE: gale::math::HMatrix4< T > Class Template Reference
gale::math::HMatrix4< T > Class Template Reference
Homogeneous matrix class implementation based on column vectors.
#include <hmatrix4.h>
Classes
struct Factory
Factory methods to easily create commonly used homogeneous matrices.
Public Types
typedef T Type
Definition for external access to the data type.
typedef Vector< 3, T > Vec
Definition of the type of vector used as the columns for the matrix.
Public Member Functions
Constructors
HMatrix4 ()
Create a matrix whose components are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
HMatrix4 (Vec const &c0, Vec const &c1, Vec const &c2, Vec const &c3)
Initialize the column vectors with vectors c0, c1, c2 and c3.
Element access methods
T * data ()
Returns a pointer to the matrix data in memory.
T const * data () const
Returns a constant pointer to the matrix data in memory.
operator T* ()
Casts this matrix to a pointer of type T.
operator T const * () const
Casts this matrix to a pointer of type T const.
T & operator() (unsigned int const row, unsigned int const column)
Returns a reference to the data element located at row and column.
T const & operator() (unsigned int const row, unsigned int const column) const
Returns a constant reference to the data element located at row and column.
Vec & getRightVector ()
Returns a reference to the first column vector which is interpreted to point right in the right-handed coordinate system orientation.
Vec const & getRightVector () const
Returns a constant reference to the first column vector which is interpreted to point right in the right-handed coordinate system orientation.
void setRightVector (Vec const &right)
Assigns a new value to the first column vector which is interpreted to point right in the right-handed coordinate system orientation.
Vec & getUpVector ()
Returns a reference to the second column vector which is interpreted to point up in the right-handed coordinate system orientation.
Vec const & getUpVector () const
Returns a constant reference to the second column vector which is interpreted to point up in the right-handed coordinate system orientation.
void setUpVector (Vec const &up)
Assigns a new value to the second column vector which is interpreted to point up in the right-handed coordinate system orientation.
Vec & getBackwardVector ()
Returns a reference to the third column vector which is interpreted to point backward in the right-handed coordinate system orientation.
Vec const & getBackwardVector () const
Returns a constant reference to the third column vector which is interpreted to point backward in the right-handed coordinate system orientation.
void setBackwardVector (Vec const &backward)
Assigns a new value to the third column vector which is interpreted to point backward in the right-handed coordinate system orientation.
Vec & getPositionVector ()
Returns a reference to the fourth column vector which is interpreted to be the coordinate system position.
Vec const & getPositionVector () const
Returns a constant reference to the fourth column vector which is interpreted to be the coordinate system position.
void setPositionVector (Vec const &position)
Assigns a new value to the fourth column vector which is interpreted to be the coordinate system position.
Arithmetic matrix / vector operators
Vec mulMatVec (Vec const &v) const
Multiplies this matrix from the left to column vector v (resulting in a column vector).
Vec mulVecMat (Vec const &v) const
Multiplies this matrix from the right to row vector v (resulting in a row vector).
Miscellaneous methods
T determinant () const
Returns the determinant of this matrix.
void orthonormalize ()
Orthonormalizes this matrix using a modified Gram-Schmidt algorithm so the column vectors are orthogonal to each other and normalized.
void transpose ()
Transposes the rotation part of this matrix.
void invert (bool *const result=NULL)
Inverts this matrix.
Static Public Member Functions
template<typename RT , class RI >
static HMatrix4 random (RandomBase< RT, RI > &r)
Returns a random orthonormalized 4x4 homogeneous matrix generated by r.
Predefined constants
In order to avoid the so called "static initialization order fiasco", static methods instead of static variables are used here, see http://www.parashift.com/c++-faq-lite/ctors.html#faq-10.14.
static HMatrix4 const & ZERO ()
Returns a matrix which has all components set to 0.
static HMatrix4 const & IDENTITY ()
Returns the identity matrix (regarding multiplication).
Public Attributes
Vec c0
Three components of the first column vector.
Vec c1
Three components of the second column vector.
Vec c2
Three components of the third column vector.
Vec c3
Three components of the fourth column vector.
Private Attributes
T m_c0w
The fourth component of the first column vector (always 0).
T m_c1w
The fourth component of the second column vector (always 0).
T m_c2w
The fourth component of the third column vector (always 0).
T m_c3w
The fourth component of the fourth column vector (always 1).
Friends
Comparison operators
bool operator== (HMatrix4 const &m, HMatrix4 const &n)
Returns whether all elements in m equal their counterpart in n with regard to a tolerance depending on the precision of data type T.
bool operator!= (HMatrix4 const &m, HMatrix4 const &n)
Returns whether the elements in m are not equal to their counterparts in n with regard to a tolerance depending on the precision of data type T.
Convenience operators for named methods
Vec operator* (HMatrix4 const &m, Vec const &v)
Multiplies matrix m from the left to column vector v (resulting in a column vector).
HMatrix4 operator~ (HMatrix4 const &m)
Returns an orthonormalized copy of matrix m.
HMatrix4 operator! (HMatrix4 const &m)
Returns the inverse of matrix m.
Streaming input / output methods
std::istream & operator>> (std::istream &s, HMatrix4 &m)
Reads a matrix from an input stream.
std::ostream & operator<< (std::ostream &s, HMatrix4 const &m)
Writes a matrix to an output stream.
Arithmetic matrix / matrix operators
HMatrix4 const & operator+= (HMatrix4 const &m)
Element-wise increments this matrix by matrix m.
HMatrix4 const & operator-= (HMatrix4 const &m)
Element-wise decrements this matrix by matrix m.
HMatrix4 const & operator*= (HMatrix4 const &m)
Multiplies this matrix by matrix m from the right.
HMatrix4 const & operator/= (HMatrix4 const &m)
Multiplies this matrix by the inverse of matrix m from the right.
HMatrix4 const & operator+ (HMatrix4 const &m)
Returns matrix m unchanged; provided for convenience.
HMatrix4 operator- (HMatrix4 const &m)
Returns the element-wise negation of matrix m.
HMatrix4 operator+ (HMatrix4 const &m, HMatrix4 const &n)
Returns the element-wise sum of matrices m and n.
HMatrix4 operator- (HMatrix4 const &m, HMatrix4 const &n)
Returns the element-wise difference of matrices m and n.
HMatrix4 operator* (HMatrix4 const &m, HMatrix4 const &n)
Returns matrix m multiplied by matrix n from the right.
HMatrix4 operator/ (HMatrix4 const &m, HMatrix4 const &n)
Returns matrix m multiplied by the inverse of matrix n from the right.
Arithmetic matrix / scalar operators
HMatrix4 const & operator*= (T const s)
Multiplies each element of this matrix by a scalar s.
HMatrix4 const & operator/= (T const s)
Divides each element of this matrix by a scalar s.
HMatrix4 operator* (HMatrix4 const &m, T const s)
Multiplies each element of matrix m by a scalar s from the right.
HMatrix4 operator* (T const s, HMatrix4 const &m)
Multiplies each element of matrix m by a scalar s from the left.
HMatrix4 operator/ (HMatrix4 const &m, T const s)
Divides each element of matrix m by a scalar s.
HMatrix4 operator/ (T const s, HMatrix4 const &m)
Divides a scalar s by each element of matrix m.
Detailed Description
template<typename T>
class gale::math::HMatrix4< T >
Homogeneous matrix class implementation based on column vectors.
The matrix is stored as 4x4 numbers organized in column-major order in memory as required by OpenGL, i.e. the matrix entry at row r, 0 <= r <= 3, and column c, 0 <= c <= 3, is located at offset i = c*4 + r. For a nice article about column vs. row vectors see http://fgiesen.wordpress.com/2011/05/04/row-major-vs-column-major-and-gl-es/.
OpenGL example usage:
Quatf q(Vec3f::Z(),45.0f*Constf::DEG_TO_RAD());
HMat4f m=q.getMatrix();
glMultMatrixf(m);
Constructor & Destructor Documentation
HMatrix4()
template<typename T > gale::math::HMatrix4< T >::HMatrix4 () inline
Create a matrix whose components are either not initialized at all or initialized to 0 if GALE_INIT_DATA is defined.
Referenced by gale::math::HMatrix4< T >::Factory::LookAt(), gale::math::HMatrix4< T >::Factory::Rotation(), gale::math::HMatrix4< T >::Factory::RotationX(), gale::math::HMatrix4< T >::Factory::RotationY(), gale::math::HMatrix4< T >::Factory::RotationZ(), gale::math::HMatrix4< T >::Factory::Scaling(), and gale::math::HMatrix4< T >::Factory::Translation().
Member Function Documentation
operator T*()
template<typename T > gale::math::HMatrix4< T >::operator T* () inline
Casts this matrix to a pointer of type T.
As an intended side effect, this also provides indexed data access.
References gale::math::HMatrix4< T >::data().
operator T const *()
template<typename T > gale::math::HMatrix4< T >::operator T const * () const inline
Casts this matrix to a pointer of type T const.
As an intended side effect, this also provides indexed data access.
References gale::math::HMatrix4< T >::data().
operator()() [1/2]
template<typename T > T& gale::math::HMatrix4< T >::operator() (unsigned int const row, unsigned int const column) inline
Returns a reference to the data element located at row and column.
Despite usual in maths, the index starts at 0 (not 1).
References G_ASSERT.
operator()() [2/2]
template<typename T > T const& gale::math::HMatrix4< T >::operator() (unsigned int const row, unsigned int const column) const inline
Returns a constant reference to the data element located at row and column.
Despite usual in maths, the index starts at 0 (not 1).
References G_ASSERT.
getRightVector() [1/2]
template<typename T > Vec& gale::math::HMatrix4< T >::getRightVector () inline
Returns a reference to the first column vector which is interpreted to point right in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c0.
Referenced by gale::wrapgl::Camera::pitch(), gale::wrapgl::Camera::rotate(), and gale::wrapgl::Camera::strafe().
getRightVector() [2/2]
template<typename T > Vec const& gale::math::HMatrix4< T >::getRightVector () const inline
Returns a constant reference to the first column vector which is interpreted to point right in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c0.
setRightVector()
template<typename T > void gale::math::HMatrix4< T >::setRightVector (Vec const & right) inline
Assigns a new value to the first column vector which is interpreted to point right in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c0.
Referenced by gale::wrapgl::Camera::rotate().
getUpVector() [1/2]
template<typename T > Vec& gale::math::HMatrix4< T >::getUpVector () inline
Returns a reference to the second column vector which is interpreted to point up in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c1.
Referenced by gale::wrapgl::Camera::elevate(), gale::wrapgl::DefaultWindow::onMouseEvent(), gale::wrapgl::Camera::rotate(), and gale::wrapgl::Camera::yaw().
getUpVector() [2/2]
template<typename T > Vec const& gale::math::HMatrix4< T >::getUpVector () const inline
Returns a constant reference to the second column vector which is interpreted to point up in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c1.
setUpVector()
template<typename T > void gale::math::HMatrix4< T >::setUpVector (Vec const & up) inline
Assigns a new value to the second column vector which is interpreted to point up in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c1.
Referenced by gale::wrapgl::Camera::rotate().
getBackwardVector() [1/2]
template<typename T > Vec& gale::math::HMatrix4< T >::getBackwardVector () inline
Returns a reference to the third column vector which is interpreted to point backward in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c2.
Referenced by gale::wrapgl::Camera::approach(), gale::wrapgl::Camera::roll(), and gale::wrapgl::Camera::rotate().
getBackwardVector() [2/2]
template<typename T > Vec const& gale::math::HMatrix4< T >::getBackwardVector () const inline
Returns a constant reference to the third column vector which is interpreted to point backward in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c2.
setBackwardVector()
template<typename T > void gale::math::HMatrix4< T >::setBackwardVector (Vec const & backward) inline
Assigns a new value to the third column vector which is interpreted to point backward in the right-handed coordinate system orientation.
References gale::math::HMatrix4< T >::c2.
Referenced by gale::wrapgl::Camera::rotate().
getPositionVector() [1/2]
template<typename T > Vec& gale::math::HMatrix4< T >::getPositionVector () inline
Returns a reference to the fourth column vector which is interpreted to be the coordinate system position.
References gale::math::HMatrix4< T >::c3.
Referenced by gale::wrapgl::Camera::approach(), gale::wrapgl::Camera::elevate(), gale::wrapgl::Camera::getPosition(), and gale::wrapgl::Camera::strafe().
getPositionVector() [2/2]
template<typename T > Vec const& gale::math::HMatrix4< T >::getPositionVector () const inline
Returns a constant reference to the fourth column vector which is interpreted to be the coordinate system position.
References gale::math::HMatrix4< T >::c3.
setPositionVector()
template<typename T > void gale::math::HMatrix4< T >::setPositionVector (Vec const & position) inline
Assigns a new value to the fourth column vector which is interpreted to be the coordinate system position.
References gale::math::HMatrix4< T >::c3.
Referenced by gale::wrapgl::Camera::setPosition().
mulMatVec()
template<typename T > Vec gale::math::HMatrix4< T >::mulMatVec (Vec const & v) const inline
Multiplies this matrix from the left to column vector v (resulting in a column vector).
References gale::math::HMatrix4< T >::c0, gale::math::HMatrix4< T >::c1, gale::math::HMatrix4< T >::c2, and gale::math::HMatrix4< T >::c3.
mulVecMat()
template<typename T > Vec gale::math::HMatrix4< T >::mulVecMat (Vec const & v) const inline
Multiplies this matrix from the right to row vector v (resulting in a row vector).
References gale::math::HMatrix4< T >::c0, gale::math::HMatrix4< T >::c1, gale::math::HMatrix4< T >::c2, gale::math::HMatrix4< T >::c3, and gale::math::HMatrix4< T >::m_c3w.
orthonormalize()
template<typename T > void gale::math::HMatrix4< T >::orthonormalize () inline
Orthonormalizes this matrix using a modified Gram-Schmidt algorithm so the column vectors are orthogonal to each other and normalized.
References gale::math::HMatrix4< T >::c0, gale::math::HMatrix4< T >::c1, gale::math::HMatrix4< T >::c2, and gale::math::Vector< N, T >::normalize().
Referenced by gale::wrapgl::DefaultWindow::onMouseEvent(), and gale::math::HMatrix4< T >::random().
invert()
template<typename T > void gale::math::HMatrix4< T >::invert (bool *const result = NULL) inline
Inverts this matrix.
Optionally returns a result indicating whether the matrix is orthonormal and thus the inverse exists.
References abs(), gale::math::HMatrix4< T >::c0, gale::math::HMatrix4< T >::c1, gale::math::HMatrix4< T >::c2, gale::math::HMatrix4< T >::c3, gale::math::HMatrix4< T >::determinant(), gale::math::Vector< N, T >::length2(), gale::math::HMatrix4< T >::transpose(), and gale::math::Numerics< T >::ZERO_TOLERANCE().
Friends And Related Function Documentation
operator==
template<typename T > bool operator== (HMatrix4< T > const & m, HMatrix4< T > const & n) friend
Returns whether all elements in m equal their counterpart in n with regard to a tolerance depending on the precision of data type T.
operator!=
template<typename T > bool operator!= (HMatrix4< T > const & m, HMatrix4< T > const & n) friend
Returns whether the elements in m are not equal to their counterparts in n with regard to a tolerance depending on the precision of data type T.
operator*
template<typename T > Vec operator* (HMatrix4< T > const & m, Vec const & v) friend
Multiplies matrix m from the left to column vector v (resulting in a column vector).
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/hmatrix4.h (Last modified in 5275de5)