GALE: gale::wrapgl::FrameBufferObject Class Reference
gale::wrapgl::FrameBufferObject Class Reference
This is a bindable OpenGL object implementation for Framebuffer Objects, see http://www.opengl.org/registry/specs/{ARB,EXT}/framebuffer_object.txt.
#include <framebufferobject.h>
Public Member Functions
Methods related to the framebuffer object's target
FrameBufferObject (GLenum const target=GL_FRAMEBUFFER)
Initializes a framebuffer object to become the current read and draw buffer when it is bound.
void bind () const
Binds the framebuffer object to the OpenGL state as the currently set target, making it the current read and / or draw buffer.
GLenum getTarget () const
Returns for which rendering operation the object becomes the target when it is bound.
void setTarget (GLenum const target)
Sets for which rendering operation the object becomes the target when it is bound.
Methods to operate on the object's data
GLint getParameter (GLenum const attachment, GLenum const name) const
Returns the buffer parameter specified by name.
GLenum check () const
Returns the status of the framebuffer to ensure its completeness.
void attach (GLenum const attachment, Texture1D const &texture, GLint const level=0) const
Attaches the given level of the specified 1D texture to the framebuffer image identified by attachment.
void attach (GLenum const attachment, Texture2D const &texture, GLint const level=0) const
Attaches the given level of the specified 2D texture to the framebuffer image identified by attachment.
void attach (GLenum const attachment, Texture3D const &texture, GLint const level=0, GLint const layer=0) const
Attaches the given level and layer of the specified 3D texture to the framebuffer image identified by attachment.
void attach (GLenum const attachment, RenderBufferObject const &buffer)
Attaches the specified buffer to the framebuffer image identified by attachment.
void detach (GLenum const attachment) const
Detaches the framebuffer image identified by attachment.
Public Member Functions inherited from gale::wrapgl::Bindable< GL_FRAMEBUFFER_BINDING, FrameBufferObject >
Bindable ()
Creates a new (initially unbound) OpenGL object.
~Bindable ()
Destroys this OpenGL object.
GLuint handle () const
Returns this object's handle.
bool isCurrent () const
Returns whether this object is in use as part of current OpenGL state.
void bind () const
Binds this object to the OpenGL state, making it the current one.
bool isDirtyState () const
Returns whether the object currently is consistent.
void setDirtyState (bool const state) const
Sets whether the object currently is consistent.
bool isValidHandle () const
Checks whether this object's handle is valid.
Static Private Member Functions
Implementation of the bindable interface
static void createObject (GLuint &handle)
Creates a new (initially unbound) OpenGL object and stores the handle.
static void destroyObject (GLuint const handle)
Destroys the OpenGL object identified by handle.
static void setCurrent (GLuint const handle, GLenum const target=GL_FRAMEBUFFER)
Sets the current binding to the object described by handle.
static bool hasSameType (GLuint const handle)
Checks whether the handle is of this object's type.
Private Attributes
GLenum m_target
Specifies for which rendering operation the object becomes the target when it is bound.
Friends
template<GLenum B, class I >
class Bindable
Additional Inherited Members
Static Public Member Functions inherited from gale::wrapgl::Bindable< GL_FRAMEBUFFER_BINDING, FrameBufferObject >
static GLuint getCurrent ()
Returns the handle of the currently bound object of type B.
static void release ()
Releases this object type from the OpenGL state, restoring the default.
Protected Attributes inherited from gale::wrapgl::Bindable< GL_FRAMEBUFFER_BINDING, FrameBufferObject >
bool m_dirty_state
Indicates whether the object currently represents a valid state vector.
GLuint m_handle
The handle identifying the object.
Detailed Description
This is a bindable OpenGL object implementation for Framebuffer Objects, see http://www.opengl.org/registry/specs/{ARB,EXT}/framebuffer_object.txt.
Constructor & Destructor Documentation
FrameBufferObject()
gale::wrapgl::FrameBufferObject::FrameBufferObject (GLenum const target = GL_FRAMEBUFFER) inline
Initializes a framebuffer object to become the current read and draw buffer when it is bound.
Member Function Documentation
bind()
void gale::wrapgl::FrameBufferObject::bind () const inline
Binds the framebuffer object to the OpenGL state as the currently set target, making it the current read and / or draw buffer.
References gale::wrapgl::Bindable< GL_RENDERBUFFER_BINDING, RenderBufferObject >::m_handle, and gale::wrapgl::RenderBufferObject::setCurrent().
getTarget()
GLenum gale::wrapgl::FrameBufferObject::getTarget () const inline
Returns for which rendering operation the object becomes the target when it is bound.
attach() [1/4]
void gale::wrapgl::FrameBufferObject::attach (GLenum const attachment, Texture1D const & texture, GLint const level = 0) const inline
Attaches the given level of the specified 1D texture to the framebuffer image identified by attachment.
References gale::wrapgl::Bindable< GL_RENDERBUFFER_BINDING, RenderBufferObject >::bind(), G_ASSERT_OPENGL, gale::wrapgl::Bindable< B, I >::handle(), and gale::wrapgl::Texture1D::target().
attach() [2/4]
void gale::wrapgl::FrameBufferObject::attach (GLenum const attachment, Texture2D const & texture, GLint const level = 0) const inline
Attaches the given level of the specified 2D texture to the framebuffer image identified by attachment.
References gale::wrapgl::Bindable< GL_RENDERBUFFER_BINDING, RenderBufferObject >::bind(), G_ASSERT_OPENGL, gale::wrapgl::Bindable< B, I >::handle(), and gale::wrapgl::Texture2D::target().
attach() [3/4]
void gale::wrapgl::FrameBufferObject::attach (GLenum const attachment, Texture3D const & texture, GLint const level = 0, GLint const layer = 0) const inline
Attaches the given level and layer of the specified 3D texture to the framebuffer image identified by attachment.
References gale::wrapgl::Bindable< GL_RENDERBUFFER_BINDING, RenderBufferObject >::bind(), G_ASSERT_OPENGL, gale::wrapgl::Bindable< B, I >::handle(), and gale::wrapgl::Texture3D::target().
attach() [4/4]
void gale::wrapgl::FrameBufferObject::attach (GLenum const attachment, RenderBufferObject const & buffer) inline
Attaches the specified buffer to the framebuffer image identified by attachment.
References G_ASSERT_OPENGL, and gale::wrapgl::Bindable< B, I >::handle().
destroyObject()
static void gale::wrapgl::FrameBufferObject::destroyObject (GLuint const handle) inline static private
Destroys the OpenGL object identified by handle.
If the object is currently bound, the default object becomes current.
References G_ASSERT_OPENGL.
setCurrent()
static void gale::wrapgl::FrameBufferObject::setCurrent (GLuint const handle, GLenum const target = GL_FRAMEBUFFER) inline static private
Sets the current binding to the object described by handle.
If handle is 0, the current object will be unbound.
References G_ASSERT_OPENGL.
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/framebufferobject.h (Last modified in 7a8a3b5)