GALE: gale::global::DynamicArray< T > Class Template Reference
gale::global::DynamicArray< T > Class Template Reference
Simple dynamic array implementation to be used in favor of e.g.
#include <dynamicarray.h>
Public Types
typedef T Type
Definition for external access to the data type.
Public Member Functions
Constructors and destructor
DynamicArray (int const size=0, int const capacity=0)
Creates a dynamic array, optionally of the given size and capacity.
DynamicArray (DynamicArray const &other)
Creates a deep copy of the given dynamic array.
template<int size>
DynamicArray (T const (&array)[size])
Creates a dynamic array from the given static array.
~DynamicArray ()
Destroys all items in the array and frees all memory.
Element access methods
T * data ()
Returns a pointer to the internal data array.
T const * data () const
Returns a constant pointer to the internal data array.
operator T* ()
Casts this array to a pointer of type T.
operator T const * () const
Casts this array to a pointer of type T const.
T & first ()
Returns a reference to the first element in the array.
T & last ()
Returns a reference to the last element in the array.
T const & first () const
Returns a constant reference to the first element in the array.
T const & last () const
Returns a constant reference to the last element in the array.
Initialization / assignment operators
DynamicArray & operator= (DynamicArray const &other)
Deeply copies the other dynamic array to this dynamic array.
meta::ArrayInitializer< T > operator= (T const &value)
Returns an array initializer object for a scalar assignment to be able to use a comma separated list of values for array assignment.
Capacity and size related methods
int getCapacity () const
Returns the array's current capacity.
void setCapacity (int capacity)
Sets the array's capacity if it is not less than its size.
int getSize () const
Returns the array's current size.
void setSize (int size)
Set the new size of the array, adjusts the capacity if required.
Array modification methods
void clear ()
Destroys all items in the array and sets its size to 0.
int insert (T const &item, int position=-1)
Inserts an item at the given position into the array.
int insert (DynamicArray const &array, int position=-1)
Inserts a dynamic array at the given position into the dynamic array.
template<int size>
int insert (T const (&array)[size], int position=-1)
Inserts a static array at the given position into the dynamic array.
int insertSorted (T const &item, bool const forced=false)
Assumes the array to be sorted and inserts item accordingly.
void remove (int begin=-1, int count=1)
Removes count items starting at begin from the array.
Find methods
int find (T const &item) const
Returns the first array index of item, or -1 if it cannot be found.
int findRev (T const &item) const
Returns the last array index of item, or -1 if it cannot be found.
bool findSorted (T const &item, int &index) const
Assumes the array to be sorted and returns whether item could be found and at which index.
Protected Attributes
T * m_data
Pointer to the memory chunk storing the array.
int m_capacity
The array's capacity, i.e. allocated memory, in units of T.
int m_size
The array's size, i.e. used memory, in units of T.
Detailed Description
template<class T>
class gale::global::DynamicArray< T >
Simple dynamic array implementation to be used in favor of e.g.
std::vector for very small programs that cannot use STL due to size constraints. In contrast to std::vector, for efficiency the default constructor is only called on non-built-in types, and objects that contain pointers to themselves are not supported.
Member Function Documentation
operator T*()
template<class T> gale::global::DynamicArray< T >::operator T* () inline
Casts this array to a pointer of type T.
As an intended side effect, this also provides indexed data access.
References gale::global::DynamicArray< T >::data().
operator T const *()
template<class T> gale::global::DynamicArray< T >::operator T const * () const inline
Casts this array to a pointer of type T const.
As an intended side effect, this also provides indexed data access.
References gale::global::DynamicArray< T >::data().
operator=()
template<class T> meta::ArrayInitializer<T> gale::global::DynamicArray< T >::operator= (T const & value) inline
Returns an array initializer object for a scalar assignment to be able to use a comma separated list of values for array assignment.
setCapacity()
template<class T> void gale::global::DynamicArray< T >::setCapacity (int capacity) inline
Sets the array's capacity if it is not less than its size.
Use 0 as the capacity to trim the memory usage to the actual array's size.
Referenced by gale::model::Mesh::Subdivider::assignNeighbors(), gale::global::DynamicArray< IndexArray >::DynamicArray(), and gale::global::DynamicArray< IndexArray >::setSize().
clear()
template<class T> void gale::global::DynamicArray< T >::clear () inline
Destroys all items in the array and sets its size to 0.
The capacity remains unchanged.
Referenced by gale::global::DynamicArray< IndexArray >::~DynamicArray().
insert() [1/3]
template<class T> int gale::global::DynamicArray< T >::insert (T const & item, int position = -1) inline
Inserts an item at the given position into the array.
If position is -1, the item gets appended at the end of the array. Returns the index of the newly added item.
Referenced by gale::model::Mesh::Subdivider::assignNeighbors(), gale::model::Mesh::Subdivider::CatmullClark(), gale::model::Mesh::Subdivider::DooSabin(), gale::global::DynamicArray< IndexArray >::DynamicArray(), gale::global::DynamicArray< IndexArray >::insertSorted(), gale::model::Mesh::Mesh(), gale::model::Mesh::orbit(), gale::model::Mesh::splice(), and gale::model::Mesh::Subdivider::Sqrt3().
insert() [2/3]
template<class T> int gale::global::DynamicArray< T >::insert (DynamicArray< T > const & array, int position = -1) inline
Inserts a dynamic array at the given position into the dynamic array.
If position is -1, the item gets appended at the end of the array. Returns the first index of the newly added array.
insert() [3/3]
template<class T> template<int size> int gale::global::DynamicArray< T >::insert (T const (&) array[size], int position = -1) inline
Inserts a static array at the given position into the dynamic array.
If position is -1, the item gets appended at the end of the array. Returns the first index of the newly added array.
insertSorted()
template<class T> int gale::global::DynamicArray< T >::insertSorted (T const & item, bool const forced = false) inline
Assumes the array to be sorted and inserts item accordingly.
If forced, duplicate entries are be allowed. Returns the index of the newly added item.
remove()
template<class T> void gale::global::DynamicArray< T >::remove (int begin = -1, int count = 1) inline
Removes count items starting at begin from the array.
If begin is negative, item are removed from the end of the array. If count is -1, all remaining items starting at begin are removed.
Referenced by gale::model::Mesh::Subdivider::DooSabin(), and gale::model::Mesh::erase().
findSorted()
template<class T> bool gale::global::DynamicArray< T >::findSorted (T const & item, int & index) const inline
Assumes the array to be sorted and returns whether item could be found and at which index.
If it was not found, index contains the position where it was expected to be found.
Referenced by gale::global::DynamicArray< IndexArray >::insertSorted().
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/global/dynamicarray.h (Last modified in a6c7904)