GALE: gale::wrapgl::VertexBufferObject< T, B > Class Template Reference
gale::wrapgl::VertexBufferObject< T, B > Class Template Reference
This is a bindable OpenGL object implementation for Vertex Buffer Objects of target type T, see http://www.opengl.org/registry/specs/ARB/vertex_buffer_object.txt.
#include <vertexbufferobject.h>
Public Member Functions
Methods to operate on the buffer's data
void getData (GLsizeiptrARB const size, GLvoid *const data, GLintptrARB const offset=0) const
Copies the size number of bytes, optionally starting at offset, from the buffer's contents to data.
void setData (GLenum const usage, GLsizeiptrARB const size, GLvoid const *const data) const
Initializes or sets the buffer's storage to the size number of bytes pointed to by data for the intended usage.
void setData (GLsizeiptrARB const size, GLvoid const *const data, GLintptrARB const offset=0) const
Modifies the buffer's storage to the size number of bytes pointed to by data, optionally starting at the given offset.
GLsizeiptrARB getSize () const
Returns the size of the buffer's storage in bytes.
GLenum getUsageType () const
Returns the usage type of the buffer's storage.
GLenum getAccessType () const
Returns the access type of the buffer's storage.
bool isMapped () const
Returns whether the buffer's storage is currently mapped to client memory.
GLchar * map (GLenum const access) const
Maps the buffer's storage to client memory for direct access using the specified access type, and returns the pointer.
bool unmap () const
Unmaps the buffer's storage from client memory, returns true on success, false otherwise.
GLchar * getBufferPointer () const
If the buffer's storage is currently mapped to client memory, returns the pointer to it, or NULL otherwise.
Public Member Functions inherited from gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >
Bindable ()
Creates a new (initially unbound) OpenGL object.
~Bindable ()
Destroys this OpenGL object.
GLuint handle () const
Returns this object's handle.
bool isCurrent () const
Returns whether this object is in use as part of current OpenGL state.
void bind () const
Binds this object to the OpenGL state, making it the current one.
bool isDirtyState () const
Returns whether the object currently is consistent.
void setDirtyState (bool const state) const
Sets whether the object currently is consistent.
bool isValidHandle () const
Checks whether this object's handle is valid.
Static Public Attributes
static GLenum const TARGET =T
Class constant for external access to the target type.
Private Member Functions
GLint getParameter (GLenum const name) const
Returns the buffer parameter specified by name.
Static Private Member Functions
Implementation of the bindable interface
static void createObject (GLuint &handle)
Creates a new (initially unbound) OpenGL object and stores the handle.
static void destroyObject (GLuint const handle)
Destroys the OpenGL object identified by handle.
static void setCurrent (GLuint const handle)
Sets the current binding to the object described by handle.
static bool hasSameType (GLuint const handle)
Checks whether the handle is of this object's type.
Friends
template<GLenum B, class I >
class Bindable
Additional Inherited Members
Static Public Member Functions inherited from gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >
static GLuint getCurrent ()
Returns the handle of the currently bound object of type B.
static void release ()
Releases this object type from the OpenGL state, restoring the default.
Protected Attributes inherited from gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >
bool m_dirty_state
Indicates whether the object currently represents a valid state vector.
GLuint m_handle
The handle identifying the object.
Detailed Description
template<GLenum T, GLenum B>
class gale::wrapgl::VertexBufferObject< T, B >
This is a bindable OpenGL object implementation for Vertex Buffer Objects of target type T, see http://www.opengl.org/registry/specs/ARB/vertex_buffer_object.txt.
Member Function Documentation
getData()
template<GLenum T, GLenum B> void gale::wrapgl::VertexBufferObject< T, B >::getData (GLsizeiptrARB const size, GLvoid *const data, GLintptrARB const offset = 0) const inline
Copies the size number of bytes, optionally starting at offset, from the buffer's contents to data.
References gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >::bind(), and G_ASSERT_OPENGL.
setData() [1/2]
template<GLenum T, GLenum B> void gale::wrapgl::VertexBufferObject< T, B >::setData (GLenum const usage, GLsizeiptrARB const size, GLvoid const *const data) const inline
Initializes or sets the buffer's storage to the size number of bytes pointed to by data for the intended usage.
References gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >::bind(), and G_ASSERT_OPENGL.
setData() [2/2]
template<GLenum T, GLenum B> void gale::wrapgl::VertexBufferObject< T, B >::setData (GLsizeiptrARB const size, GLvoid const *const data, GLintptrARB const offset = 0) const inline
Modifies the buffer's storage to the size number of bytes pointed to by data, optionally starting at the given offset.
References gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >::bind(), and G_ASSERT_OPENGL.
isMapped()
template<GLenum T, GLenum B> bool gale::wrapgl::VertexBufferObject< T, B >::isMapped () const inline
Returns whether the buffer's storage is currently mapped to client memory.
References gale::wrapgl::VertexBufferObject< T, B >::getParameter().
map()
template<GLenum T, GLenum B> GLchar* gale::wrapgl::VertexBufferObject< T, B >::map (GLenum const access) const inline
Maps the buffer's storage to client memory for direct access using the specified access type, and returns the pointer.
References gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >::bind(), and G_ASSERT_OPENGL.
unmap()
template<GLenum T, GLenum B> bool gale::wrapgl::VertexBufferObject< T, B >::unmap () const inline
Unmaps the buffer's storage from client memory, returns true on success, false otherwise.
References gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >::bind(), and G_ASSERT_OPENGL.
getBufferPointer()
template<GLenum T, GLenum B> GLchar* gale::wrapgl::VertexBufferObject< T, B >::getBufferPointer () const inline
If the buffer's storage is currently mapped to client memory, returns the pointer to it, or NULL otherwise.
References gale::wrapgl::Bindable< B, VertexBufferObject< T, B > >::bind(), and G_ASSERT_OPENGL.
destroyObject()
template<GLenum T, GLenum B> static void gale::wrapgl::VertexBufferObject< T, B >::destroyObject (GLuint const handle) inline static private
Destroys the OpenGL object identified by handle.
If the object is currently bound, the default object becomes current.
References G_ASSERT_OPENGL.
setCurrent()
template<GLenum T, GLenum B> static void gale::wrapgl::VertexBufferObject< T, B >::setCurrent (GLuint const handle) inline static private
Sets the current binding to the object described by handle.
If handle is 0, the current object will be unbound.
References G_ASSERT_OPENGL.
The documentation for this class was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/vertexbufferobject.h (Last modified in 7a8a3b5)