GALE: gale::system::CPUInfo Class Reference
gale::system::CPUInfo Class Reference
Using the x86 CPUID instruction, this class reports detailed processor capabilities.
#include <cpuinfo.h>
Public Member Functions
bool isLittleEndian () const
Checks if this is a little-endian (as opposed to big-endian) machine.
CPUID helper methods
bool hasCPUID () const
Checks for the presence of the CPUID instruction.
unsigned int maxCPUIDStdFunc () const
Returns the highest standard function number supported and fills out the vendor string information.
unsigned int maxCPUIDExtFunc () const
Returns the highest extended function number supported.
Vendor identification methods
char const * vendorString () const
Return the CPU vendor string.
bool isIntel () const
Convenience method that returns whether this is an Intel CPU.
bool isAMD () const
Convenience method that returns whether this is an AMD CPU.
bool isCyrix () const
Convenience method that returns whether this is a Cyrix / VIA CPU.
bool isCentaur () const
Convenience method that returns whether this is a Centaur / VIA CPU.
Methods to determine the number of processing units, see
http://cache-www.intel.com/cd/00/00/27/66/276611_276611.txt
unsigned int processors () const
Returns the number of processors (i.e. CPU sockets).
unsigned int coresPerPhysicalProc () const
Returns the number of processor cores per physical processor.
unsigned int logicalProcsPerCore () const
Returns the number of logical processors per processor core.
Features reported by the standard flags
bool hasFPU () const
Returns whether the processor contains an on-chip Floating-Point Unit.
bool hasVME () const
Returns whether Virtual-8086 Mode Extensions are supported.
bool hasDE () const
Returns whether Debugging Extensions like I/O breakpoints are supported.
bool hasPSE () const
Returns whether the processor supports the 4-MiB Page Size Extension.
bool hasTSC () const
Returns whether a Time-Stamp Counter is available.
bool hasMSR () const
Returns whether Model Specific Registers are implemented.
bool hasPAE () const
Returns whether the Physical Address Extension (more than 32 bits) is supported.
bool hasMCE () const
Returns whether the processor supports the Machine Check Exception.
bool hasCX8 () const
Returns whether the CMPXCHG8B instruction is supported.
bool hasAPIC () const
Returns whether an Advanced Programmable Interrupt Controller is available and enabled.
bool hasSEP () const
Returns whether the processor supports the fast system call (SYSENTER / SYSEXIT) instructions.
bool hasMTRR () const
Returns whether the processor supports the Memory Type Range Registers.
bool hasPGE () const
Returns whether the Page Global Extensions are supported in the page directory / table entries.
bool hasMCA () const
Returns whether the Machine Check Architecture is supported.
bool hasCMOV () const
Returns whether the processor supports conditional move instructions.
bool hasPAT () const
Returns whether the processor supports the Page Attribute Table.
bool hasPSE36 () const
Returns whether the processor allows the Page Size Extension to address physical memory beyond 4 GiB.
bool hasPSN () const
Returns whether the processor has a 96-bit serial number (reserved on AMD).
bool hasCLFSH () const
Returns whether the CLFLUSH instruction is supported.
bool hasDS () const
Returns whether the processor is able to write a history of branch addresses into a Debug Store (reserved on AMD).
bool hasACPI () const
Returns whether the processor implements temperature monitoring and performance modulation under software control (reserved on AMD).
bool hasMMX () const
Returns whether the processor supports the MMX instruction set.
bool hasFXSR () const
Returns whether the fast floating-point save and restore instructions (FXSAVE / FXRSTOR) are supported.
bool hasSSE () const
Returns whether the Streaming SIMD Extension instruction set is supported.
bool hasSSE2 () const
Returns whether the Streaming SIMD Extension 2 instruction set is supported.
bool hasSS () const
Returns whether the processor supports Self-Snooping of its cache to manage conflicting memory types (reserved on AMD).
bool hasHTT () const
Returns whether Multi-Threading capability is present, allowing the processor to operate as multiple logical units (because there either is Hyper-Threading Technology or more than one core per processor available).
bool hasTM () const
Returns whether the processor implements the Thermal Monitor automatic thermal control circuit (reserved on AMD).
bool hasIA64 () const
Returns whether the processor has capabilities of the Intel Itanium processor family and is currently operating in IA32 emulation mode (reserved on AMD).
bool hasPBE () const
Returns whether the processor supports returning from stop-clock state to handle interrupts (reserved on AMD).
bool hasSSE3 () const
Returns whether the Streaming SIMD Extension 3 instruction set is supported.
bool hasDTES64 () const
Returns whether the processor has the ability to write a history of the 64-bit branch to and from addresses into a memory buffer (reserved on AMD).
bool hasMONITOR () const
Returns whether the processor supports the MONITOR and MWAIT instructions.
bool hasDSCPL () const
Returns whether the processor supports extensions to the Debug Store to allow for branch message storage qualified by CPL (reserved on AMD).
bool hasVMX () const
Returns whether the processor supports Intel Virtualization Technology (reserved on AMD).
bool hasSMX () const
Returns whether the processor supports Intel Trusted Execution Technology (reserved on AMD).
bool hasEST () const
Returns whether the processor implements second generation Intel SpeedStep Technology (reserved on AMD).
bool hasTM2 () const
Returns whether the processor implements the Thermal Monitor 2 automatic thermal control circuit (reserved on AMD).
bool hasSSSE3 () const
Returns whether the processor supports the Supplemental Streaming SIMD Extension 3 instructions.
bool hasCID () const
Returns whether the L1 data cache mode can be set to either adaptive mode or shared mode by the BIOS (reserved on AMD).
bool hasCX16 () const
Returns whether the CMPXCHG16B instruction is supported.
bool hasTPR () const
Returns whether the processor supports to disable sending Task Priority messages (reserved on AMD).
bool hasPDCM () const
Returns whether the processor has performance monitoring and debug capabilities (reserved on AMD).
bool hasDCA () const
Returns whether the processor supports Direct Cache Access to prefetch data from a memory mapped device (reserved on AMD).
bool hasSSE41 () const
Returns whether the processor supports the Streaming SIMD Extensions 4.1 instructions.
bool hasSSE42 () const
Returns whether the processor supports the Streaming SIMD Extensions 4.2 instructions (reserved on AMD).
bool hasX2APIC () const
Returns whether the processor supports the x2APIC feature (reserved on AMD).
bool hasMOVBE () const
Returns whether the processor supports the MOVBE instruction (reserved on AMD).
bool hasPOPCNT () const
Returns whether the processor supports the POPCNT instruction.
bool hasXSAVE () const
Returns whether the processor supports the XSAVE / XRSTOR extended states feature (reserved on AMD).
bool hasOSXSAVE () const
Returns whether the processor was enabled by the OS to support extended state management using XSAVE / XRSTOR (reserved on AMD).
Features reported by the extended flags
bool hasSYSCALL () const
Returns whether the processor supports the SYSCALL and SYSRET instructions.
bool hasXDB () const
Returns whether the processor supports the XD Bit to support no-execute page protection in PAE.
bool hasMMXExt () const
Returns whether the processor supports AMD extensions to MMX instructions (reserved on Intel).
bool hasFFXSR () const
Returns whether the processor implements FXSAVE and FXRSTOR instruction optimizations (reserved on Intel).
bool hasRDTSCP () const
Returns whether the processor supports the RDTSCP instruction (reserved on Intel).
bool hasAMD64 () const
Returns whether the processor supports Long Mode to access 64-bit instructions and registers, running 32-bit and 16-bit programs in a compatibility sub-mode.
bool has3DNowExt () const
Returns whether the processor supports AMD extensions to 3DNow! instructions (reserved on Intel).
bool has3DNow () const
Returns whether the 3DNow! instruction set is supported (reserved on Intel).
bool hasLAHF () const
Returns whether the LAHF / SAHF instructions are supported in 64-bit sub-mode.
bool hasCmpLegacy () const
Returns whether the processor's legacy mode is to do multi-processing, i.e.
bool hasSVM () const
Returns whether the processor supports Secure Virtual Machine feature (reserved on Intel).
bool hasExtAPICSpace () const
Returns whether the extended APIC register space is present (reserved on Intel).
bool hasAltMovCr8 () const
Returns whether LOCK MOV CR0 means MOV CR8 (reserved on Intel).
bool hasABM () const
Returns whether advanced bit manipulation via the LZCNT instruction is supported (reserved on Intel).
bool hasSSE4A () const
Returns whether SSE4A instructions are supported (reserved on Intel).
bool hasMisaligedSSE () const
Returns whether misaligned access for SSE instructions is supported (reserved on Intel).
bool has3DNowPrefetch () const
Returns whether the PREFETCH and PREFETCHW instructions are supported (reserved on Intel).
bool hasOSVW () const
Returns whether the OS visible work-around information is supported (reserved on Intel).
bool hasIBS () const
Returns whether instruction based sampling is supported (reserved on Intel).
bool hasSSE5 () const
Returns whether SSE5 instructions are supported (reserved on Intel).
bool hasSKINIT () const
Returns whether SKINIT and STGI are supported (reserved on Intel).
bool hasWDT () const
Returns whether the watchdog timer is supported (reserved on Intel).
Private Member Functions
CPUInfo ()
Make the constructor private so the class cannot be derived from and thus complete the Singleton design pattern.
Private Attributes
char m_vendor [3 *4+1]
Stores the vendor string incl. trailing zero.
unsigned int m_00000001_ebx
CPUID standard miscellaneous flags.
unsigned int m_00000004_eax
CPUID standard cache parameters.
unsigned int m_80000008_ecx
CPUID extended address sizes.
unsigned int m_00000001_edx
CPUID standard feature flags, part 1.
unsigned int m_00000001_ecx
CPUID standard feature flags, part 2.
unsigned int m_80000001_edx
CPUID extended feature flags, part 1.
unsigned int m_80000001_ecx
CPUID extended feature flags, part 2.
Friends
class global::Singleton< CPUInfo >
Additional Inherited Members
Static Public Member Functions inherited from gale::global::Singleton< CPUInfo >
static CPUInfo & the ()
Returns a reference to the one and only instance of this class.
Protected Member Functions inherited from gale::global::Singleton< CPUInfo >
Singleton ()
Prevent the creation of a new singleton instance.
~Singleton ()
Prevent the destruction, e.g. via pointer deletion.
Detailed Description
Using the x86 CPUID instruction, this class reports detailed processor capabilities.
For details consult these documents:
Intel Processor Identification and the CPUID Instruction, see http://www.intel.com/Assets/PDF/appnote/241618.pdf.
AMD CPUID Specification, see http://support.amd.com/us/Processor_TechDocs/25481.pdf.
Constructor & Destructor Documentation
CPUInfo()
gale::system::CPUInfo::CPUInfo () private
Make the constructor private so the class cannot be derived from and thus complete the Singleton design pattern.
References hasCPUID(), m_00000001_ebx, m_00000001_ecx, m_00000001_edx, m_00000004_eax, m_80000001_ecx, m_80000001_edx, m_80000008_ecx, m_vendor, maxCPUIDExtFunc(), and maxCPUIDStdFunc().
Referenced by hasWDT().
Member Function Documentation
maxCPUIDStdFunc()
unsigned int gale::system::CPUInfo::maxCPUIDStdFunc () const
Returns the highest standard function number supported and fills out the vendor string information.
Referenced by CPUInfo(), isLittleEndian(), and logicalProcsPerCore().
hasPAE()
bool gale::system::CPUInfo::hasPAE () const inline
Returns whether the Physical Address Extension (more than 32 bits) is supported.
References m_00000001_edx.
hasAPIC()
bool gale::system::CPUInfo::hasAPIC () const inline
Returns whether an Advanced Programmable Interrupt Controller is available and enabled.
References m_00000001_edx.
hasSEP()
bool gale::system::CPUInfo::hasSEP () const inline
Returns whether the processor supports the fast system call (SYSENTER / SYSEXIT) instructions.
References m_00000001_edx.
hasPGE()
bool gale::system::CPUInfo::hasPGE () const inline
Returns whether the Page Global Extensions are supported in the page directory / table entries.
References m_00000001_edx.
hasPSE36()
bool gale::system::CPUInfo::hasPSE36 () const inline
Returns whether the processor allows the Page Size Extension to address physical memory beyond 4 GiB.
References m_00000001_edx.
hasPSN()
bool gale::system::CPUInfo::hasPSN () const inline
Returns whether the processor has a 96-bit serial number (reserved on AMD).
References m_00000001_edx.
hasDS()
bool gale::system::CPUInfo::hasDS () const inline
Returns whether the processor is able to write a history of branch addresses into a Debug Store (reserved on AMD).
References m_00000001_edx.
hasACPI()
bool gale::system::CPUInfo::hasACPI () const inline
Returns whether the processor implements temperature monitoring and performance modulation under software control (reserved on AMD).
References m_00000001_edx.
hasFXSR()
bool gale::system::CPUInfo::hasFXSR () const inline
Returns whether the fast floating-point save and restore instructions (FXSAVE / FXRSTOR) are supported.
References m_00000001_edx.
hasSSE()
bool gale::system::CPUInfo::hasSSE () const inline
Returns whether the Streaming SIMD Extension instruction set is supported.
References m_00000001_edx.
hasSSE2()
bool gale::system::CPUInfo::hasSSE2 () const inline
Returns whether the Streaming SIMD Extension 2 instruction set is supported.
References m_00000001_edx.
hasSS()
bool gale::system::CPUInfo::hasSS () const inline
Returns whether the processor supports Self-Snooping of its cache to manage conflicting memory types (reserved on AMD).
References m_00000001_edx.
hasHTT()
bool gale::system::CPUInfo::hasHTT () const inline
Returns whether Multi-Threading capability is present, allowing the processor to operate as multiple logical units (because there either is Hyper-Threading Technology or more than one core per processor available).
References m_00000001_edx.
Referenced by coresPerPhysicalProc(), and logicalProcsPerCore().
hasTM()
bool gale::system::CPUInfo::hasTM () const inline
Returns whether the processor implements the Thermal Monitor automatic thermal control circuit (reserved on AMD).
References m_00000001_edx.
hasIA64()
bool gale::system::CPUInfo::hasIA64 () const inline
Returns whether the processor has capabilities of the Intel Itanium processor family and is currently operating in IA32 emulation mode (reserved on AMD).
References m_00000001_edx.
hasPBE()
bool gale::system::CPUInfo::hasPBE () const inline
Returns whether the processor supports returning from stop-clock state to handle interrupts (reserved on AMD).
References m_00000001_edx.
hasSSE3()
bool gale::system::CPUInfo::hasSSE3 () const inline
Returns whether the Streaming SIMD Extension 3 instruction set is supported.
References m_00000001_ecx.
hasDTES64()
bool gale::system::CPUInfo::hasDTES64 () const inline
Returns whether the processor has the ability to write a history of the 64-bit branch to and from addresses into a memory buffer (reserved on AMD).
References m_00000001_ecx.
hasMONITOR()
bool gale::system::CPUInfo::hasMONITOR () const inline
Returns whether the processor supports the MONITOR and MWAIT instructions.
References m_00000001_ecx.
hasDSCPL()
bool gale::system::CPUInfo::hasDSCPL () const inline
Returns whether the processor supports extensions to the Debug Store to allow for branch message storage qualified by CPL (reserved on AMD).
References m_00000001_ecx.
hasVMX()
bool gale::system::CPUInfo::hasVMX () const inline
Returns whether the processor supports Intel Virtualization Technology (reserved on AMD).
References m_00000001_ecx.
hasSMX()
bool gale::system::CPUInfo::hasSMX () const inline
Returns whether the processor supports Intel Trusted Execution Technology (reserved on AMD).
References m_00000001_ecx.
hasEST()
bool gale::system::CPUInfo::hasEST () const inline
Returns whether the processor implements second generation Intel SpeedStep Technology (reserved on AMD).
References m_00000001_ecx.
hasTM2()
bool gale::system::CPUInfo::hasTM2 () const inline
Returns whether the processor implements the Thermal Monitor 2 automatic thermal control circuit (reserved on AMD).
References m_00000001_ecx.
hasSSSE3()
bool gale::system::CPUInfo::hasSSSE3 () const inline
Returns whether the processor supports the Supplemental Streaming SIMD Extension 3 instructions.
References m_00000001_ecx.
hasCID()
bool gale::system::CPUInfo::hasCID () const inline
Returns whether the L1 data cache mode can be set to either adaptive mode or shared mode by the BIOS (reserved on AMD).
References m_00000001_ecx.
hasTPR()
bool gale::system::CPUInfo::hasTPR () const inline
Returns whether the processor supports to disable sending Task Priority messages (reserved on AMD).
References m_00000001_ecx.
hasPDCM()
bool gale::system::CPUInfo::hasPDCM () const inline
Returns whether the processor has performance monitoring and debug capabilities (reserved on AMD).
References m_00000001_ecx.
hasDCA()
bool gale::system::CPUInfo::hasDCA () const inline
Returns whether the processor supports Direct Cache Access to prefetch data from a memory mapped device (reserved on AMD).
References m_00000001_ecx.
hasSSE41()
bool gale::system::CPUInfo::hasSSE41 () const inline
Returns whether the processor supports the Streaming SIMD Extensions 4.1 instructions.
References m_00000001_ecx.
hasSSE42()
bool gale::system::CPUInfo::hasSSE42 () const inline
Returns whether the processor supports the Streaming SIMD Extensions 4.2 instructions (reserved on AMD).
References m_00000001_ecx.
hasMOVBE()
bool gale::system::CPUInfo::hasMOVBE () const inline
Returns whether the processor supports the MOVBE instruction (reserved on AMD).
References m_00000001_ecx.
hasXSAVE()
bool gale::system::CPUInfo::hasXSAVE () const inline
Returns whether the processor supports the XSAVE / XRSTOR extended states feature (reserved on AMD).
References m_00000001_ecx.
hasOSXSAVE()
bool gale::system::CPUInfo::hasOSXSAVE () const inline
Returns whether the processor was enabled by the OS to support extended state management using XSAVE / XRSTOR (reserved on AMD).
References m_00000001_ecx.
hasSYSCALL()
bool gale::system::CPUInfo::hasSYSCALL () const inline
Returns whether the processor supports the SYSCALL and SYSRET instructions.
References m_80000001_edx.
hasXDB()
bool gale::system::CPUInfo::hasXDB () const inline
Returns whether the processor supports the XD Bit to support no-execute page protection in PAE.
References m_80000001_edx.
hasMMXExt()
bool gale::system::CPUInfo::hasMMXExt () const inline
Returns whether the processor supports AMD extensions to MMX instructions (reserved on Intel).
References m_80000001_edx.
hasFFXSR()
bool gale::system::CPUInfo::hasFFXSR () const inline
Returns whether the processor implements FXSAVE and FXRSTOR instruction optimizations (reserved on Intel).
References m_80000001_edx.
hasRDTSCP()
bool gale::system::CPUInfo::hasRDTSCP () const inline
Returns whether the processor supports the RDTSCP instruction (reserved on Intel).
References m_80000001_edx.
hasAMD64()
bool gale::system::CPUInfo::hasAMD64 () const inline
Returns whether the processor supports Long Mode to access 64-bit instructions and registers, running 32-bit and 16-bit programs in a compatibility sub-mode.
References m_80000001_edx.
has3DNowExt()
bool gale::system::CPUInfo::has3DNowExt () const inline
Returns whether the processor supports AMD extensions to 3DNow! instructions (reserved on Intel).
References m_80000001_edx.
has3DNow()
bool gale::system::CPUInfo::has3DNow () const inline
Returns whether the 3DNow! instruction set is supported (reserved on Intel).
References m_80000001_edx.
hasLAHF()
bool gale::system::CPUInfo::hasLAHF () const inline
Returns whether the LAHF / SAHF instructions are supported in 64-bit sub-mode.
References m_80000001_ecx.
hasCmpLegacy()
bool gale::system::CPUInfo::hasCmpLegacy () const inline
Returns whether the processor's legacy mode is to do multi-processing, i.e.
if multiple cores are present (reserved on Intel).
References m_80000001_ecx.
hasSVM()
bool gale::system::CPUInfo::hasSVM () const inline
Returns whether the processor supports Secure Virtual Machine feature (reserved on Intel).
References m_80000001_ecx.
hasExtAPICSpace()
bool gale::system::CPUInfo::hasExtAPICSpace () const inline
Returns whether the extended APIC register space is present (reserved on Intel).
References m_80000001_ecx.
hasABM()
bool gale::system::CPUInfo::hasABM () const inline
Returns whether advanced bit manipulation via the LZCNT instruction is supported (reserved on Intel).
References m_80000001_ecx.
hasMisaligedSSE()
bool gale::system::CPUInfo::hasMisaligedSSE () const inline
Returns whether misaligned access for SSE instructions is supported (reserved on Intel).
References m_80000001_ecx.
has3DNowPrefetch()
bool gale::system::CPUInfo::has3DNowPrefetch () const inline
Returns whether the PREFETCH and PREFETCHW instructions are supported (reserved on Intel).
References m_80000001_ecx.
hasOSVW()
bool gale::system::CPUInfo::hasOSVW () const inline
Returns whether the OS visible work-around information is supported (reserved on Intel).
References m_80000001_ecx.
hasIBS()
bool gale::system::CPUInfo::hasIBS () const inline
Returns whether instruction based sampling is supported (reserved on Intel).
References m_80000001_ecx.
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/system/cpuinfo.h (Last modified in 5275de5)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/cpuinfo.cpp (Last modified in 5275de5)