GALE: gale::wrapgl::RenderSurface Class Reference
gale::wrapgl::RenderSurface Class Reference
This class provides a minimal pixel surface that is suitable for OpenGL rendering.
#include <rendersurface.h>
Classes
struct ContextHandle
A context handle uniquely identifies a render surface.
struct Dimensions
Simple structure to hold the dimensions of a render surface.
Public Types
typedef HWND WindowHandle
Type definition for a window handle the render surface belongs to.
Public Member Functions
RenderSurface (global::AttributeListi const *const context_attr=NULL, global::AttributeListi const *const pixel_attr=NULL, int const samples=8)
Creates a minimal render surface and current render context with the attributes in context_attr.
~RenderSurface ()
Destroys render surface.
WindowHandle const & windowHandle () const
Returns the handle to the window associated with this render surface.
ContextHandle const & contextHandle () const
Returns the handle to the OpenGL context associated with this render surface.
bool makeCurrent ()
Makes this the active OpenGL context for the current thread.
Dimensions dimensions () const
Returns the width and height of this render surface.
Static Public Member Functions
static ContextHandle getCurrent ()
Returns the active OpenGL context for the current thread.
static bool setCurrent (ContextHandle const &handle)
Sets the active OpenGL context for the current thread.
Static Public Attributes
static int const DEFAULT_COLOR_BITS = 24
The color bits to use if not further specified.
static int const DEFAULT_DEPTH_BITS = 24
The depth bits to use if not further specified.
static int const DEFAULT_STENCIL_BITS = 8
The stencil bits to use if not further specified.
Protected Member Functions
bool createDeviceContext (int pixel_format=0)
Creates a minimal device context and associated window with either a default or the specified pixel_format.
void destroyDeviceContext ()
Releases the device context and destroys the associated window.
void destroyRenderContext ()
Deletes the render context only.
virtual LRESULT handleMessage (UINT const uMsg, WPARAM const wParam, LPARAM const lParam)
Handles window messages and forwards them to the event methods.
Protected Attributes
WindowHandle m_window
Handle to the window owning the OpenGL context.
ContextHandle m_context
Handle to the OpenGL context.
Static Protected Attributes
static PIXELFORMATDESCRIPTOR const s_pfd
Pixel format description for the default format.
Static Private Member Functions
static LRESULT CALLBACK WindowProc (WindowHandle hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
Forwards window messages to the class instance's message handler.
Detailed Description
This class provides a minimal pixel surface that is suitable for OpenGL rendering.
It is hidden and has no dimensions initially which predestines it for tasks such as initializing OpenGL extensions.
Constructor & Destructor Documentation
RenderSurface()
gale::wrapgl::RenderSurface::RenderSurface (global::AttributeListi const *const context_attr = NULL, global::AttributeListi const *const pixel_attr = NULL, int const samples = 8)
Creates a minimal render surface and current render context with the attributes in context_attr.
Either a default pixel format or one that matches pixel_attr is used. If multi-sampling is available, the specified number of samples is used.
References gale::global::AttributeList< T, N >::clear(), G_ASSERT, G_ASSERT_CALL, and gale::global::AttributeList< T, N >::insert().
Referenced by setCurrent().
Member Function Documentation
contextHandle()
ContextHandle const& gale::wrapgl::RenderSurface::contextHandle () const inline
Returns the handle to the OpenGL context associated with this render surface.
References m_context.
createDeviceContext()
bool gale::wrapgl::RenderSurface::createDeviceContext (int pixel_format = 0) protected
Creates a minimal device context and associated window with either a default or the specified pixel_format.
The window is initially hidden and has no dimensions. No rendering context is created yet to allow creating one using OpenGL extensions.
Referenced by dimensions().
destroyDeviceContext()
void gale::wrapgl::RenderSurface::destroyDeviceContext () protected
Releases the device context and destroys the associated window.
This is e.g. required if another pixel format should be set for a device context as an application can only set the pixel format of a window one time.
References G_ASSERT_CALL.
Referenced by dimensions(), and ~RenderSurface().
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/rendersurface.h (Last modified in a6c7904)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/rendersurface.cpp (Last modified in 5275de5)