GALE: gale::wrapgl::RenderBufferObject Class Reference
gale::wrapgl::RenderBufferObject Class Reference
This is a bindable OpenGL object implementation for Renderbuffer Objects, see http://www.opengl.org/registry/specs/{ARB,EXT}/framebuffer_object.txt.
#include <framebufferobject.h>
Public Member Functions
Methods to operate on the object's data
void setStorage (GLsizei const width, GLsizei const height, GLenum const format, GLsizei const samples=0) const
Initializes or sets the object's storage to the given width, height and format, optionally with multi-sampling using the specified number of samples enabled.
GLsizei getWidth () const
Returns the width of the object's storage.
GLsizei getHeight () const
Returns the height of the object's storage.
GLenum getFormat () const
Returns the format of the object's storage.
GLint getRedBits () const
Returns the actual (not necessarily requested) number of bits for the red color component.
GLint getGreenBits () const
Returns the actual (not necessarily requested) number of bits for the green color component.
GLint getBlueBits () const
Returns the actual (not necessarily requested) number of bits for the blue color component.
GLint getAlphaBits () const
Returns the actual (not necessarily requested) number of bits for the alpha color component.
GLint getDepthBits () const
Returns the actual (not necessarily requested) number of bits for the depth buffer component.
GLint getStencilBits () const
Returns the actual (not necessarily requested) number of bits for the stencil buffer component.
GLsizei getSamples () const
Returns the actual (not necessarily requested) number of samples used for multi-sampling.
Public Member Functions inherited from gale::wrapgl::Bindable< GL_RENDERBUFFER_BINDING, RenderBufferObject >
Bindable ()
Creates a new (initially unbound) OpenGL object.
~Bindable ()
Destroys this OpenGL object.
GLuint handle () const
Returns this object's handle.
bool isCurrent () const
Returns whether this object is in use as part of current OpenGL state.
void bind () const
Binds this object to the OpenGL state, making it the current one.
bool isDirtyState () const
Returns whether the object currently is consistent.
void setDirtyState (bool const state) const
Sets whether the object currently is consistent.
bool isValidHandle () const
Checks whether this object's handle is valid.
Private Member Functions
GLint getParameter (GLenum const name) const
Returns the buffer parameter specified by name.
Static Private Member Functions
static void initFallback ()
Maps ARB_framebuffer_object function pointers to EXT_framebuffer_* function pointers as a fallback.
Implementation of the bindable interface
static void createObject (GLuint &handle)
Creates a new (initially unbound) OpenGL object and stores the handle.
static void destroyObject (GLuint const handle)
Destroys the OpenGL object identified by handle.
static void setCurrent (GLuint const handle)
Sets the current binding to the object described by handle.
static bool hasSameType (GLuint const handle)
Checks whether the handle is of this object's type.
Friends
template<GLenum B, class I >
class Bindable
class FrameBufferObject
Additional Inherited Members
Static Public Member Functions inherited from gale::wrapgl::Bindable< GL_RENDERBUFFER_BINDING, RenderBufferObject >
static GLuint getCurrent ()
Returns the handle of the currently bound object of type B.
static void release ()
Releases this object type from the OpenGL state, restoring the default.
Protected Attributes inherited from gale::wrapgl::Bindable< GL_RENDERBUFFER_BINDING, RenderBufferObject >
bool m_dirty_state
Indicates whether the object currently represents a valid state vector.
GLuint m_handle
The handle identifying the object.
Detailed Description
This is a bindable OpenGL object implementation for Renderbuffer Objects, see http://www.opengl.org/registry/specs/{ARB,EXT}/framebuffer_object.txt.
Member Function Documentation
setStorage()
void gale::wrapgl::RenderBufferObject::setStorage (GLsizei const width, GLsizei const height, GLenum const format, GLsizei const samples = 0) const inline
Initializes or sets the object's storage to the given width, height and format, optionally with multi-sampling using the specified number of samples enabled.
References gale::wrapgl::Bindable< GL_RENDERBUFFER_BINDING, RenderBufferObject >::bind(), and G_ASSERT_OPENGL.
getRedBits()
GLint gale::wrapgl::RenderBufferObject::getRedBits () const inline
Returns the actual (not necessarily requested) number of bits for the red color component.
References getParameter().
getGreenBits()
GLint gale::wrapgl::RenderBufferObject::getGreenBits () const inline
Returns the actual (not necessarily requested) number of bits for the green color component.
References getParameter().
getBlueBits()
GLint gale::wrapgl::RenderBufferObject::getBlueBits () const inline
Returns the actual (not necessarily requested) number of bits for the blue color component.
References getParameter().
getAlphaBits()
GLint gale::wrapgl::RenderBufferObject::getAlphaBits () const inline
Returns the actual (not necessarily requested) number of bits for the alpha color component.
References getParameter().
getDepthBits()
GLint gale::wrapgl::RenderBufferObject::getDepthBits () const inline
Returns the actual (not necessarily requested) number of bits for the depth buffer component.
References getParameter().
getStencilBits()
GLint gale::wrapgl::RenderBufferObject::getStencilBits () const inline
Returns the actual (not necessarily requested) number of bits for the stencil buffer component.
References getParameter().
getSamples()
GLsizei gale::wrapgl::RenderBufferObject::getSamples () const inline
Returns the actual (not necessarily requested) number of samples used for multi-sampling.
References getParameter().
destroyObject()
static void gale::wrapgl::RenderBufferObject::destroyObject (GLuint const handle) inline static private
Destroys the OpenGL object identified by handle.
If the object is currently bound, the default object becomes current.
References G_ASSERT_OPENGL.
setCurrent()
static void gale::wrapgl::RenderBufferObject::setCurrent (GLuint const handle) inline static private
Sets the current binding to the object described by handle.
If handle is 0, the current object will be unbound.
References G_ASSERT_OPENGL.
Referenced by gale::wrapgl::FrameBufferObject::bind().
initFallback()
void gale::wrapgl::RenderBufferObject::initFallback () static private
Maps ARB_framebuffer_object function pointers to EXT_framebuffer_* function pointers as a fallback.
Referenced by createObject(), gale::wrapgl::FrameBufferObject::createObject(), and hasSameType().
The documentation for this class was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/wrapgl/framebufferobject.h (Last modified in 7a8a3b5)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/framebufferobject.cpp (Last modified in a6c7904)