GALE: gale::math Namespace Reference
gale::math Namespace Reference
Namespace for mathematical code.
Classes
struct ScaleBias
Transformation class that applies first a scale and then a bias to a value.
struct BiasScale
Transformation class that applies first a bias and then a scale to a value.
struct ColorChannel
Helper class with only a single template parameter.
class Color
Color representation based on an RGB(A)-tuple.
class ColorModel
Base class for color model representations different than RGB.
class ColorModelRYB
An RYB color model representation, see http://threekings.tk/mirror/ryb_TR.pdf.
class ColorSpace
Base class for color spaces based on the RGB color model.
class ColorSpaceHSV
An HSV (also known as HSB) color space representation, see http://en.wikipedia.org/wiki/List_of_color_spaces_and_their_uses#HSV.
struct Constants
Definition of data type specific mathematical constants.
struct Numerics
Definition of data type specific numeric limits.
union FP32
A union to access the components of a 32-bit float.
union FP16
A union to access the components of a 16-bit "half" float.
struct Formula
Functor base class for implementing formulas that map R1 to R1.
struct FormulaR2R3
Functor base class for implementing formulas that map R2 to R3.
struct ConstantFormula
Functor for a constant formula.
struct SuperFormula
Functor for the generalized Superformula as described by J.
class HMatrix4
Homogeneous matrix class implementation based on column vectors.
class Interpolator
A collection of interpolation (and approximation) methods.
class Matrix4
Matrix class implementation based on column vectors.
class Quaternion
Quaternion implementation based on a scalar for the real number part and a vector for the imaginary number part.
class RandomBase
Random number generator template base class for the data type specified by the T template argument.
struct RandomEcuyerImpl
A random number generator based on the maximally equidistributed combined Tausworthe generator by L'Ecuyer.
struct RandomMotherImpl
Multiply-with-carry random number generator as invented by George Marsaglia and implemented by Agner Fog, see http://www.agner.org/random/mother/.
class TupleBase
Tuple base class implementation with N elements of type T.
class Tuple
Tuple class implementation as an example how to derive from TupleBase.
class Vector
Vector class implementation based on a tuple, featuring common linear algebra and math operations specialized on computer graphics.
Typedefs
Convenience type definitions
typedef BiasScale< double > BiasScaled
typedef BiasScale< float > BiasScalef
typedef ScaleBias< double > ScaleBiasd
typedef ScaleBias< float > ScaleBiasf
typedef Quaternion< double > Quatd
typedef Quaternion< float > Quatf
Type definitions for use as OpenGL colors
typedef Color< 3, double > Col3d
typedef Color< 3, float > Col3f
typedef Color< 3, int > Col3i
typedef Color< 3, unsigned int > Col3ui
typedef Color< 3, short > Col3s
typedef Color< 3, unsigned short > Col3us
typedef Color< 3, signed char > Col3b
typedef Color< 3, unsigned char > Col3ub
typedef Color< 4, double > Col4d
typedef Color< 4, float > Col4f
typedef Color< 4, int > Col4i
typedef Color< 4, unsigned int > Col4ui
typedef Color< 4, short > Col4s
typedef Color< 4, unsigned short > Col4us
typedef Color< 4, signed char > Col4b
typedef Color< 4, unsigned char > Col4ub
Type definitions for mathematical constants
typedef Constants< double > Constd
typedef Constants< float > Constf
Type definitions for numeric limits
typedef Numerics< double > Numd
typedef Numerics< float > Numf
typedef Numerics< int > Numi
typedef Numerics< unsigned int > Numui
typedef Numerics< short > Nums
typedef Numerics< unsigned short > Numus
typedef Numerics< signed char > Numb
typedef Numerics< unsigned char > Numub
Type definitions for use as OpenGL matrices
typedef HMatrix4< double > HMat4d
typedef HMatrix4< float > HMat4f
typedef Matrix4< double > Mat4d
typedef Matrix4< float > Mat4f
Type definitions for convenience
typedef RandomBase< g_real64,
RandomEcuyerImpl > RandomEcuyerd
typedef RandomBase< g_real32,
RandomEcuyerImpl > RandomEcuyerf
typedef RandomBase< g_real64,
RandomMotherImpl > RandomMotherd
typedef RandomBase< g_real32,
RandomMotherImpl > RandomMotherf
typedef Tuple< 3, double > Tup3d
typedef Tuple< 3, float > Tup3f
typedef Tuple< 3, int > Tup3i
typedef Tuple< 3, unsigned int > Tup3ui
typedef Tuple< 3, short > Tup3s
typedef Tuple< 3, unsigned short > Tup3us
typedef Tuple< 3, signed char > Tup3b
typedef Tuple< 3, unsigned char > Tup3ub
typedef Tuple< 4, double > Tup4d
typedef Tuple< 4, float > Tup4f
typedef Tuple< 4, int > Tup4i
typedef Tuple< 4, unsigned int > Tup4ui
typedef Tuple< 4, short > Tup4s
typedef Tuple< 4, unsigned short > Tup4us
typedef Tuple< 4, signed char > Tup4b
typedef Tuple< 4, unsigned char > Tup4ub
Type definitions for use as OpenGL vertices
typedef Vector< 2, double > Vec2d
typedef Vector< 2, float > Vec2f
typedef Vector< 2, int > Vec2i
typedef Vector< 2, short > Vec2s
typedef Vector< 3, double > Vec3d
typedef Vector< 3, float > Vec3f
typedef Vector< 3, int > Vec3i
typedef Vector< 3, short > Vec3s
typedef Vector< 4, double > Vec4d
typedef Vector< 4, float > Vec4f
typedef Vector< 4, int > Vec4i
typedef Vector< 4, short > Vec4s
Functions
template<class T , typename I >
static T lerp (T const &a, T const &b, I const &s)
Linearly interpolates between a and b based on s.
template<class T , typename I >
static T cubic (T const &a, T const &b, I const &s)
Cubically interpolates between a and b based on s.
Extremes determination related functions
template<typename T >
T clamp (T const x, T const a, T const b)
Clamps x to range [a,b], where a <= b.
template<typename T >
T clampSafe (T const x, T const a, T const b)
Clamps x to range [a,b] or range [b,a].
template<typename T >
T wrap (T x, T const range)
Wraps x to [0,range[.
template<typename T >
T wrap (T x, T const a, T const b)
Wraps x to range [a,b], where a <= b.
template<typename T >
T wrapSafe (T x, T const a, T const b)
Wraps x to range [a,b] or range [b,a].
template<typename T >
T min (T const a, T const b)
Returns the minimum value among a and b.
template<typename T >
T min (T const a, T const b, T const c)
Returns the minimum value among a, b and c.
template<typename T >
T min (T const a, T const b, T const c, T const d)
Returns the minimum value among a, b, c and d.
template<typename T >
T max (T const a, T const b)
Returns the maximum value among a and b.
template<typename T >
T max (T const a, T const b, T const c)
Returns the maximum value among a, b and c.
template<typename T >
T max (T const a, T const b, T const c, T const d)
Returns the maximum value among a, b, c and d.
template<typename T >
T sgn (T const x)
Returns the sign of x, or 0 if x is 0.
Floating-point rounding related functions
G_INLINE int roundToZero (float const f)
Rounds the 32-bit floating point value f to the nearest integer (to the even one in case of ambiguity).
G_INLINE long long roundToZero (double const d)
Rounds the 64-bit floating point value d to the nearest integer towards zero (truncating the number).
Floating-point conversion related functions
G_INLINE FP32 convertHalfToFloat (FP16 h)
Converts the given 16-bit "half" float h to a 32-bit float, see https://gist.github.com/2144712#L218.
G_INLINE FP16 convertFloatToHalf (FP32 f)
Converts the given 32-bit float f to a 16-bit "half" float, see https://gist.github.com/2156668#L153.
Bit juggling functions
unsigned int countLeadingZeroBits (unsigned int x)
Returns the number of leading (most significant) zero bits in x.
unsigned int countSetBits (unsigned int x)
Returns the number of set bits in x.
unsigned int mod3 (unsigned int x)
Returns the remainder of x divided by 3.
Power-Of-2 (POT) related functions
bool isPowerOf2 (unsigned int const x)
Returns whether x is an exact power of two.
int indexLSBSet (unsigned int x)
Returns the position of the least significant bit set in x (the least significant bit has index 0).
int indexMSBSet (unsigned int x)
Returns the position of the most significant bit set in x (the least significant bit has index 0).
unsigned int ceilPow2 (unsigned int const x)
Returns the smallest power of 2 that is greater than or equal to x, except for x=0 and x>2147483648 which returns 0.
unsigned int floorPow2 (unsigned int const x)
Returns the largest power of 2 that is smaller than or equal to x, except for x=0 which returns 0.
Detailed Description
Namespace for mathematical code.
Function Documentation
G_INLINE int gale::math::roundToZero (float const f)
Rounds the 32-bit floating point value f to the nearest integer (to the even one in case of ambiguity).
This is the default rounding mode on x86 platforms, so the floating-point control word is not modified. Rounds the 64-bit floating point value d to the nearest integer (to the even one in case of ambiguity). This is the default rounding mode on x86 platforms, so the floating-point control word is not modified. Rounds the 32-bit floating point value f to the nearest integer towards zero (truncating the number). This is the default ANSI C rounding mode; use this method instead of a cast to an integer as it is faster.
Referenced by gale::math::Interpolator::getInterval(), and gale::math::ColorSpaceHSV::toRGB().
G_INLINE long long gale::math::roundToZero (double const d)
Rounds the 64-bit floating point value d to the nearest integer towards zero (truncating the number).
This is the default ANSI C rounding mode; use this method instead of a cast to an integer as it is faster.
G_INLINE FP32 gale::math::convertHalfToFloat (FP16 h)
Converts the given 16-bit "half" float h to a 32-bit float, see https://gist.github.com/2144712#L218.
References gale::math::FP32::f, gale::math::FP32::u, and gale::math::FP16::u.
G_INLINE FP16 gale::math::convertFloatToHalf (FP32 f)
Converts the given 32-bit float f to a 16-bit "half" float, see https://gist.github.com/2156668#L153.
References gale::math::FP32::f, gale::math::FP32::u, and gale::math::FP16::u.
int gale::math::indexLSBSet (unsigned int x) inline
Returns the position of the least significant bit set in x (the least significant bit has index 0).
int gale::math::indexMSBSet (unsigned int x) inline
Returns the position of the most significant bit set in x (the least significant bit has index 0).
Referenced by ceilPow2(), and floorPow2().
unsigned int gale::math::ceilPow2 (unsigned int const x) inline
Returns the smallest power of 2 that is greater than or equal to x, except for x=0 and x>2147483648 which returns 0.
References indexMSBSet().
unsigned int gale::math::floorPow2 (unsigned int const x) inline
Returns the largest power of 2 that is smaller than or equal to x, except for x=0 which returns 0.
References indexMSBSet().
template<class T , typename I > static T gale::math::lerp (T const & a, T const & b, I const & s) static
Linearly interpolates between a and b based on s.
For performance reasons, s is not clamped to [0,1].
Referenced by gale::math::Interpolator::Cosine(), gale::math::Interpolator::Linear(), and gale::model::Mesh::Subdivider::Loop().
template<class T , typename I > static T gale::math::cubic (T const & a, T const & b, I const & s) static
Cubically interpolates between a and b based on s.
For performance reasons, s is not clamped to [0,1].
Referenced by gale::math::ColorModelRYB::toRGB().
Donations are appreciated via
GALE is generously hosted by