GALE: gale::math::HMatrix4< T >::Factory Struct Reference
gale::math::HMatrix4< T >::Factory Struct Reference
Factory methods to easily create commonly used homogeneous matrices.
#include <hmatrix4.h>
Static Public Member Functions
static HMatrix4 RotationX (T const angle)
Creates a rotation matrix about the x-axis for the given angle in radians.
static HMatrix4 RotationY (T const angle)
Creates a rotation matrix about the y-axis for the given angle in radians.
static HMatrix4 RotationZ (T const angle)
Creates a rotation matrix about the z-axis for the given angle in radians.
static HMatrix4 Rotation (Vec const &axis, T const angle)
Creates a rotation matrix about the given normalized axis for the given angle in radians.
static HMatrix4 Translation (Vec const &direction, T const factor=1)
Creates a translation matrix along the given direction, optionally scaled by factor.
static HMatrix4 Scaling (T const x, T const y, T const z)
Creates a scaling matrix for the given factors along the x, y and z axes.
static HMatrix4 LookAt (Vec const &target, Vec const &position, Vec up)
Creates a matrix that makes a camera look at target from position, with up facing upwards (if it is collinear to the view direction, another arbitrary vector is used).
Detailed Description
template<typename T>
struct gale::math::HMatrix4< T >::Factory
Factory methods to easily create commonly used homogeneous matrices.
Member Function Documentation
RotationX()
template<typename T > static HMatrix4 gale::math::HMatrix4< T >::Factory::RotationX (T const angle) inline static
Creates a rotation matrix about the x-axis for the given angle in radians.
References gale::math::HMatrix4< T >::HMatrix4(), gale::math::Vector< 3, T >::X(), and gale::math::Vector< 3, T >::ZERO().
RotationY()
template<typename T > static HMatrix4 gale::math::HMatrix4< T >::Factory::RotationY (T const angle) inline static
Creates a rotation matrix about the y-axis for the given angle in radians.
References gale::math::HMatrix4< T >::HMatrix4(), gale::math::Vector< 3, T >::Y(), and gale::math::Vector< 3, T >::ZERO().
RotationZ()
template<typename T > static HMatrix4 gale::math::HMatrix4< T >::Factory::RotationZ (T const angle) inline static
Creates a rotation matrix about the z-axis for the given angle in radians.
References gale::math::HMatrix4< T >::HMatrix4(), gale::math::Vector< 3, T >::Z(), and gale::math::Vector< 3, T >::ZERO().
Referenced by gale::model::Mesh::Factory::MoebiusStrip().
Rotation()
template<typename T > static HMatrix4 gale::math::HMatrix4< T >::Factory::Rotation (Vec const & axis, T const angle) inline static
Creates a rotation matrix about the given normalized axis for the given angle in radians.
References gale::math::Vector< N, T >::getX(), gale::math::Vector< N, T >::getY(), gale::math::Vector< N, T >::getZ(), gale::math::HMatrix4< T >::HMatrix4(), and gale::math::Vector< 3, T >::ZERO().
Referenced by gale::wrapgl::DefaultWindow::onMouseEvent().
Translation()
template<typename T > static HMatrix4 gale::math::HMatrix4< T >::Factory::Translation (Vec const & direction, T const factor = 1) inline static
Creates a translation matrix along the given direction, optionally scaled by factor.
References gale::math::HMatrix4< T >::HMatrix4(), gale::math::Vector< 3, T >::X(), gale::math::Vector< 3, T >::Y(), and gale::math::Vector< 3, T >::Z().
Scaling()
template<typename T > static HMatrix4 gale::math::HMatrix4< T >::Factory::Scaling (T const x, T const y, T const z) inline static
Creates a scaling matrix for the given factors along the x, y and z axes.
References gale::math::HMatrix4< T >::HMatrix4(), and gale::math::Vector< 3, T >::ZERO().
LookAt()
template<typename T > static HMatrix4 gale::math::HMatrix4< T >::Factory::LookAt (Vec const & target, Vec const & position, Vec up) inline static
Creates a matrix that makes a camera look at target from position, with up facing upwards (if it is collinear to the view direction, another arbitrary vector is used).
References gale::math::HMatrix4< T >::HMatrix4(), gale::math::Vector< N, T >::isCollinear(), and gale::math::Vector< N, T >::orthoVector().
Referenced by gale::wrapgl::Camera::align().
The documentation for this struct was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/hmatrix4.h (Last modified in 5275de5)