GALE: gale::model::Mesh::Factory::Shape Struct Reference
gale::model::Mesh::Factory::Shape Struct Reference
Methods to create shapes, e.g. for use as extrusion contours.
#include <mesh.h>
Static Public Member Functions
static void Ellipse (VectorArray &shape, int const segs, float const w, float const h)
Returns an array of vectors on an ellipse with width w and height h, divided into segs segments.
static void Heart (VectorArray &shape, int const segs)
Returns an array of vectors on a heart shape as published at http://iquilezles.org/blog/?p=1181.
static void Supershape (VectorArray &shape, int const segs, float const m, float const n1, float const n2, float const n3, float const a=1.0f, float const b=1.0f)
Returns an array of vectors as calculated by the Superformula, see http://local.wasp.uwa.edu.au/~pbourke/geometry/supershape/.
Detailed Description
Methods to create shapes, e.g. for use as extrusion contours.
Member Function Documentation
Ellipse()
void gale::model::Mesh::Factory::Shape::Ellipse (VectorArray & shape, int const segs, float const w, float const h) static
Returns an array of vectors on an ellipse with width w and height h, divided into segs segments.
References gale::math::Constants< T >::PI(), and gale::global::DynamicArray< T >::setSize().
Heart()
void gale::model::Mesh::Factory::Shape::Heart (VectorArray & shape, int const segs) static
Returns an array of vectors on a heart shape as published at http://iquilezles.org/blog/?p=1181.
References abs(), gale::math::Constants< T >::PI(), and gale::global::DynamicArray< T >::setSize().
Supershape()
void gale::model::Mesh::Factory::Shape::Supershape (VectorArray & shape, int const segs, float const m, float const n1, float const n2, float const n3, float const a = 1.0f, float const b = 1.0f) static
Returns an array of vectors as calculated by the Superformula, see http://local.wasp.uwa.edu.au/~pbourke/geometry/supershape/.
References gale::math::Constants< T >::PI(), and gale::global::DynamicArray< T >::setSize().
The documentation for this struct was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/model/mesh.h (Last modified in 5275de5)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/mesh_factory.cpp (Last modified in a6c7904)