GALE: gale::math::BiasScale< T > Struct Template Reference
gale::math::BiasScale< T > Struct Template Reference
Transformation class that applies first a bias and then a scale to a value.
#include <biasscale.h>
Public Types
typedef T Type
Definition for external access to the data type.
Public Member Functions
Constructors
BiasScale (T const bias=0, T const scale=1)
Initializes the transformation to the given bias and scale which are the identity by default.
BiasScale (ScaleBias< T > const &other)
Initializes the transformation from a transformation that applies the scale first and then the bias.
Static Public Member Functions
Predefined constants
In order to avoid the so called "static initialization order fiasco", static methods instead of static variables are used here, see http://www.parashift.com/c++-faq-lite/ctors.html#faq-10.14.
static BiasScale const & IDENTITY ()
Returns the identity transformation that does not alter the value.
Public Attributes
T bias
The bias value that is added to the operand value.
T scale
The scale value that is multiplied with the operand value.
Friends
Convenience operators for named methods
BiasScale operator & (BiasScale const &a, BiasScale const &b)
Returns the concatenation of transformations a and b.
BiasScale operator! (BiasScale const &other)
Returns the inverse of transformation other so that its concatenation with the original transformation would result in no-operation.
Miscellaneous methods
bool isNOP () const
Returns whether this transformation is the identity and thus performs a no-operation.
T evaluate (T const x) const
Evaluates the transformation for value x.
void concat (BiasScale const &other)
Concatenates the other transformation to this transformation.
void invert ()
Inverts this transformation so that its concatenation with the original transformation would result in no-operation.
bool operator== (BiasScale const &a, BiasScale const &b)
Returns whether transformation a equals transformation b.
Detailed Description
template<typename T>
struct gale::math::BiasScale< T >
Transformation class that applies first a bias and then a scale to a value.
Constructor & Destructor Documentation
BiasScale() [1/2]
template<typename T> gale::math::BiasScale< T >::BiasScale (T const bias = 0, T const scale = 1) inline
Initializes the transformation to the given bias and scale which are the identity by default.
BiasScale() [2/2]
template<typename T > gale::math::BiasScale< T >::BiasScale (ScaleBias< T > const & other) inline explicit
Initializes the transformation from a transformation that applies the scale first and then the bias.
References gale::math::BiasScale< T >::bias, gale::math::ScaleBias< T >::bias, gale::math::BiasScale< T >::scale, and gale::math::ScaleBias< T >::scale.
Member Function Documentation
isNOP()
template<typename T> bool gale::math::BiasScale< T >::isNOP () const inline
Returns whether this transformation is the identity and thus performs a no-operation.
References gale::math::BiasScale< T >::IDENTITY().
invert()
template<typename T > void gale::math::BiasScale< T >::invert () inline
Inverts this transformation so that its concatenation with the original transformation would result in no-operation.
References gale::math::BiasScale< T >::bias, gale::meta::OpCmpEqual::evaluate(), gale::math::BiasScale< T >::IDENTITY(), and gale::math::BiasScale< T >::scale.
Referenced by gale::math::BiasScale< T >::concat().
Friends And Related Function Documentation
operator!
template<typename T> BiasScale operator! (BiasScale< T > const & other) friend
Returns the inverse of transformation other so that its concatenation with the original transformation would result in no-operation.
The documentation for this struct was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/biasscale.h (Last modified in 5275de5)