GALE: gale::math::Matrix4< T >::Factory Struct Reference
gale::math::Matrix4< T >::Factory Struct Reference
Factory methods to easily create commonly used matrices.
#include <matrix4.h>
Static Public Member Functions
static Matrix4 OrthographicProjection (double const clip_left, double const clip_right, double const clip_bottom, double const clip_top, double const clip_near=-1.0, double const clip_far=1.0)
Creates an orthographic projection matrix.
static Matrix4 PerspectiveProjection (int const view_width, int const view_height, double const fov=Constd::PI() *0.25, double const clip_near=0.001, double const clip_far=1000.0)
Creates a perspective projection matrix for a viewport of the given view_width and view_height, a vertical field of view of fov and clipping planes located at clip_near and clip_far.
static Matrix4 Projection (Vector< 3, T > const &n, Vector< 3, T > const &v, bool p=true)
Creates a generic projection matrix onto the plane given by normal n as seen from viewpoint v.
Detailed Description
template<typename T>
struct gale::math::Matrix4< T >::Factory
Factory methods to easily create commonly used matrices.
Member Function Documentation
OrthographicProjection()
template<typename T > static Matrix4 gale::math::Matrix4< T >::Factory::OrthographicProjection (double const clip_left, double const clip_right, double const clip_bottom, double const clip_top, double const clip_near = -1.0, double const clip_far = 1.0) inline static
Creates an orthographic projection matrix.
The intersection points of clip_left / clip_bottom and clip_right / clip_top on the near clipping plane are mapped to the lower left and upper right viewport corners respectively.
References gale::math::Matrix4< T >::Matrix4().
PerspectiveProjection()
template<typename T > static Matrix4 gale::math::Matrix4< T >::Factory::PerspectiveProjection (int const view_width, int const view_height, double const fov = Constd::PI()*0.25, double const clip_near = 0.001, double const clip_far = 1000.0) inline static
Creates a perspective projection matrix for a viewport of the given view_width and view_height, a vertical field of view of fov and clipping planes located at clip_near and clip_far.
References gale::math::Matrix4< T >::Matrix4().
Referenced by gale::wrapgl::Camera::Camera(), gale::wrapgl::Camera::setFarClipping(), gale::wrapgl::Camera::setFOV(), and gale::wrapgl::Camera::setNearClipping().
Projection()
template<typename T > static Matrix4 gale::math::Matrix4< T >::Factory::Projection (Vector< 3, T > const & n, Vector< 3, T > const & v, bool p = true) inline static
Creates a generic projection matrix onto the plane given by normal n as seen from viewpoint v.
If p is true, the projection is perspective, else it is orthographic. For details, see http://www.cs.iastate.edu/~cs577/handouts/projection.pdf
References gale::math::Vector< N, T >::getX(), gale::math::Vector< N, T >::getY(), gale::math::Vector< N, T >::getZ(), and gale::math::Matrix4< T >::IDENTITY().
The documentation for this struct was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/math/matrix4.h (Last modified in 5275de5)