GALE: gale::meta::LoopFwd< NUM, OP > Struct Template Reference
gale::meta::LoopFwd< NUM, OP > Struct Template Reference
Meta-template forward loop implementation; iterates ascendingly over NUM elements in at least one array, evaluating OP on the elements.
#include <loops.h>
Public Types
enum { index =NUM-1 }
Static Public Member Functions
template<typename A , typename B >
static G_INLINE void iterate (A *const a, B const &b)
Iterates over a destination array applying a scalar.
template<typename A , typename B >
static G_INLINE void iterate (A *const a, B const *const b)
Iterates over a destination array and a source array.
template<typename A , typename B , typename C >
static G_INLINE void iterate (A *const a, B const *const b, C const *const c)
Iterates over a destination array and two source arrays.
template<typename A , typename B , typename C , typename D >
static G_INLINE void iterate (A *const a, B const *const b, C const *const c, D const &d)
Iterates over a destination array and two source arrays applying a scalar.
template<typename A >
static G_INLINE A iterate (A const *const a)
Iterates over a single array evaluating a scalar.
template<typename A >
static G_INLINE A iterateAbsValues (A const *const a)
Iterates over a single array of absolute values evaluating a scalar.
template<typename A , typename B >
static G_INLINE A iterateCombAdd (A const *const a, B const *const b)
Iterates over two arrays adding evaluated values.
template<typename A , typename B >
static G_INLINE bool iterateCondAnd (A const *const a, B const *const b)
Iterates over two arrays evaluating an "and" condition.
template<typename A , typename B >
static G_INLINE void iterateIndexMask (A *const a, B const &b, A const set=1, A const clear=0)
Iterates over a destination array a setting its elements according to the bit mask b to either the value of set or clear.
Detailed Description
template<unsigned int NUM, class OP>
struct gale::meta::LoopFwd< NUM, OP >
Meta-template forward loop implementation; iterates ascendingly over NUM elements in at least one array, evaluating OP on the elements.
Member Enumeration Documentation
anonymous enum
template<unsigned int NUM, class OP> anonymous enum
Enumerator
index
Stores the array index to use in this recursion.
Member Function Documentation
iterate()
template<unsigned int NUM, class OP> template<typename A , typename B , typename C , typename D > static G_INLINE void gale::meta::LoopFwd< NUM, OP >::iterate (A *const a, B const *const b, C const *const c, D const & d) inline static
Iterates over a destination array and two source arrays applying a scalar.
References gale::meta::LoopFwd< NUM, OP >::index, and gale::meta::LoopFwd< NUM, OP >::iterate().
iterateIndexMask()
template<unsigned int NUM, class OP> template<typename A , typename B > static G_INLINE void gale::meta::LoopFwd< NUM, OP >::iterateIndexMask (A *const a, B const & b, A const set = 1, A const clear = 0) inline static
Iterates over a destination array a setting its elements according to the bit mask b to either the value of set or clear.
References gale::meta::LoopFwd< NUM, OP >::index.
Referenced by gale::math::Color< N, T >::Color(), and gale::math::Vector< 3, T >::Vector().
The documentation for this struct was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/meta/loops.h (Last modified in a6c7904)