GALE: gale::model::Mesh Struct Reference
gale::model::Mesh Struct Reference
A vertex-vertex mesh data structure implementation as described at http://en.wikipedia.org/wiki/Polygon_mesh#Vertex-vertex_meshes.
#include <mesh.h>
Classes
class Factory
Factory class to create procedural meshes.
class Subdivider
Class to subdivide meshes using different algorithms, for an overview see http://en.wikipedia.org/wiki/Subdivision_surface.
Public Types
typedef global::DynamicArray< math::Vec3f > VectorArray
Array of vectors as usable e.g. by glVertexPointer().
typedef global::DynamicArray< unsigned int > IndexArray
Array of indices as usable e.g. by glDrawElements().
typedef global::DynamicArray< IndexArray > IndexTable
Array of arrays to store vertex neighbors or polygon indices.
Public Member Functions
Mesh (int const num_vertices=0)
Creates a mesh with num_vertices uninitialized vertices.
Mesh (VectorArray const &vertex_array)
Creates a mesh, copying the vertices from the given dynamic vertex_array.
template<size_t size>
Mesh (math::Vec3f const (&vertex_array)[size])
Creates a mesh, copying the vertices from the given static vertex_array.
int check () const
Performs a simple brute-force check of the neighborhood information.
Selection operations
int nextTo (int const xi, int const vi, int const steps=1) const
Returns the index of the vertex following xi in the neighborhood of vi, both given as indices into the vertex array.
int prevTo (int const xi, int const vi, int const steps=1) const
Returns the index of the vertex preceding xi in the neighborhood of vi, both given as indices into the vertex array.
int orbit (int ai, int bi, IndexArray &polygon) const
Given an oriented edge from ai to bi, returns the number of vertices that make up the edge's face, and their indices in polygon.
Editing operations
int insert (int const ai, int const bi, math::Vec3f const &x)
Inserts a new vertex x on the edge between ai and bi and returns its index in the vertex array.
void splice (int const ai, int const xi, int const vi, bool const after=true)
Inserts ai after or before xi in the neighborhood of vi.
void erase (int const xi, int const vi)
Removes xi from the neighborhood of vi.
Topological properties
int numVertices () const
Returns the number of vertices in the mesh.
int numEdges () const
Returns the number of edges in the mesh.
int numFaces () const
Returns the number of faces in the mesh.
Public Attributes
VectorArray vertices
Array of vertex positions.
IndexTable neighbors
Array of arrays of neighboring vertex indices.
Detailed Description
A vertex-vertex mesh data structure implementation as described at http://en.wikipedia.org/wiki/Polygon_mesh#Vertex-vertex_meshes.
Member Function Documentation
nextTo()
int gale::model::Mesh::nextTo (int const xi, int const vi, int const steps = 1) const
Returns the index of the vertex following xi in the neighborhood of vi, both given as indices into the vertex array.
Optionally, this is repeated the given number of steps.
References gale::global::DynamicArray< T >::find(), and gale::global::DynamicArray< T >::getSize().
Referenced by gale::model::Mesh::Subdivider::assignNeighbors(), gale::model::Mesh::Subdivider::Butterfly(), gale::model::Mesh::Subdivider::CatmullClark(), gale::model::Mesh::Subdivider::DooSabin(), gale::model::Mesh::Subdivider::Loop(), Mesh(), and gale::model::Mesh::Subdivider::Sqrt3().
prevTo()
int gale::model::Mesh::prevTo (int const xi, int const vi, int const steps = 1) const
Returns the index of the vertex preceding xi in the neighborhood of vi, both given as indices into the vertex array.
Optionally, this is repeated the given number of steps.
References gale::global::DynamicArray< T >::find(), and gale::global::DynamicArray< T >::getSize().
Referenced by gale::model::Mesh::Subdivider::assignNeighbors(), gale::model::Mesh::Subdivider::Butterfly(), gale::model::Mesh::Subdivider::CatmullClark(), gale::model::Mesh::Subdivider::DooSabin(), gale::model::Mesh::Subdivider::Loop(), Mesh(), and gale::model::Mesh::Subdivider::Sqrt3().
orbit()
int gale::model::Mesh::orbit (int ai, int bi, IndexArray & polygon) const
Given an oriented edge from ai to bi, returns the number of vertices that make up the edge's face, and their indices in polygon.
References gale::global::DynamicArray< T >::getSize(), gale::global::DynamicArray< T >::insert(), and gale::global::DynamicArray< T >::setSize().
Referenced by gale::wrapgl::PreparedMesh::compile(), gale::model::Mesh::Subdivider::DooSabin(), and Mesh().
insert()
int gale::model::Mesh::insert (int const ai, int const bi, math::Vec3f const & x)
Inserts a new vertex x on the edge between ai and bi and returns its index in the vertex array.
References gale::global::DynamicArray< T >::find().
Referenced by gale::model::Mesh::Subdivider::Butterfly(), gale::model::Mesh::Subdivider::CatmullClark(), gale::model::Mesh::Subdivider::Loop(), Mesh(), and gale::model::Mesh::Subdivider::Polyhedral().
numFaces()
int gale::model::Mesh::numFaces () const inline
Returns the number of faces in the mesh.
As the Euler formula is used, the result is only valid for polyhedra that are topologically equivalent to a sphere (i.e. that do not contain any holes).
References check(), numEdges(), and numVertices().
check()
int gale::model::Mesh::check () const
Performs a simple brute-force check of the neighborhood information.
Returns -1 on success or the vertex index causing the error.
References gale::global::DynamicArray< T >::getSize().
Referenced by numFaces().
The documentation for this struct was generated from the following files:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/model/mesh.h (Last modified in 5275de5)
C:/Users/sebastian/Development/GitHub/gale/gale2/source/mesh.cpp (Last modified in a6c7904)