GALE: gale::math::ScaleBias< T > Struct Template Reference
gale::math::ScaleBias< T > Struct Template Reference
Transformation class that applies first a scale and then a bias to a value.
#include <biasscale.h>
Public Types
typedef T Type
Definition for external access to the data type.
Public Member Functions
Constructors
ScaleBias (T const scale=1, T const bias=0)
Initializes the transformation to the given scale and bias which are the identity by default.
ScaleBias (BiasScale< T > const &other)
Initializes the transformation from a transformation that applies the bias first and then the scale.
Static Public Member Functions
Predefined constants
In order to avoid the so called "static initialization order fiasco", static methods instead of static variables are used here, see http://www.parashift.com/c++-faq-lite/ctors.html#faq-10.14.
static ScaleBias const & IDENTITY ()
Returns the identity transformation that does not alter the value.
Public Attributes
T scale
The scale value that is multiplied with the operand value.
T bias
The bias value that is added to the operand value.
Friends
Convenience operators for named methods
ScaleBias operator& (ScaleBias const &a, ScaleBias const &b)
Returns the concatenation of transformations a and b.
ScaleBias operator! (ScaleBias const &other)
Returns the inverse of transformation other so that its concatenation with the original transformation would result in no-operation.
Miscellaneous methods
bool isNOP () const
Returns whether this transformation is the identity and thus performs a no-operation.
T evaluate (T const x) const
Evaluates the transformation for value x.
void concat (ScaleBias const &other)
Concatenates the other transformation to this transformation.
void invert ()
Inverts this transformation so its concatenation with the original transformation would result in no-operation.
bool operator== (ScaleBias const &a, ScaleBias const &b)
Returns whether transformation a equals transformation b.
Detailed Description
template<typename T>
struct gale::math::ScaleBias< T >
Transformation class that applies first a scale and then a bias to a value.
Constructor & Destructor Documentation
template<typename T> gale::math::ScaleBias< T >::ScaleBias (T const scale = 1, T const bias = 0) inline
Initializes the transformation to the given scale and bias which are the identity by default.
template<typename T> gale::math::ScaleBias< T >::ScaleBias (BiasScale< T > const & other) inline explicit
Initializes the transformation from a transformation that applies the bias first and then the scale.
References gale::math::BiasScale< T >::bias, gale::math::ScaleBias< T >::bias, gale::math::BiasScale< T >::scale, and gale::math::ScaleBias< T >::scale.
Member Function Documentation
template<typename T> bool gale::math::ScaleBias< T >::isNOP () const inline
Returns whether this transformation is the identity and thus performs a no-operation.
References gale::math::ScaleBias< T >::IDENTITY().
template<typename T> void gale::math::ScaleBias< T >::invert () inline
Inverts this transformation so its concatenation with the original transformation would result in no-operation.
References gale::math::ScaleBias< T >::bias, gale::meta::OpCmpEqual::evaluate(), gale::math::ScaleBias< T >::IDENTITY(), and gale::math::ScaleBias< T >::scale.
Friends And Related Function Documentation
template<typename T> ScaleBias operator! (ScaleBias< T > const & other) friend
Returns the inverse of transformation other so that its concatenation with the original transformation would result in no-operation.
The documentation for this struct was generated from the following file:
include/gale/math/biasscale.h (Last modified in b7b3e5b)
Donations are appreciated via
GALE is generously hosted by