GALE: gale::meta::OpCmpEqual Struct Reference
gale::meta::OpCmpEqual Struct Reference
Boolean absolute "equal" comparison operator.
#include <operators.h>
Static Public Member Functions
template<typename T >
static G_INLINE bool evaluate (T const &a, T const &b, T const &tolerance=math::Numerics< T >::ZERO_TOLERANCE())
Returns whether a equals b with regard to an absolute tolerance which by default depends on the precision of data type T.
Detailed Description
Boolean absolute "equal" comparison operator.
Member Function Documentation
evaluate()
template<typename T > static G_INLINE bool gale::meta::OpCmpEqual::evaluate (T const & a, T const & b, T const & tolerance = math::Numerics<T>::ZERO_TOLERANCE()) inline static
Returns whether a equals b with regard to an absolute tolerance which by default depends on the precision of data type T.
References abs().
Referenced by gale::math::BiasScale< T >::invert(), gale::math::ScaleBias< T >::invert(), gale::math::Vector< 3, T >::isCollinear(), gale::model::AABB::isEmpty(), and gale::model::Mesh::Factory::populateNeighborhood().
The documentation for this struct was generated from the following file:
C:/Users/sebastian/Development/GitHub/gale/gale2/include/gale/meta/operators.h (Last modified in 611d94c)